/* ============================================================
   AI Efficiency Test — банк сценариев. window.AIE_QUESTIONS

   Формат элемента:
     id, block: "core" | роль, dim: ведущее измерение,
     prompt: {en,ru}   — сценарий из реальной работы
     options: [{ id, text:{en,ru},
                 s: { dimension: -2..2, ... }   — баллы по измерениям
                 lean: -1 | 0 | 1               — недо-делегирование / баланс / пере-доверие
                 why: {en,ru}                   — разбор на экране результатов
               }]
   Ровно один вариант в каждом вопросе — лучший (сумма s максимальна).
   Правдоподобные ловушки важнее очевидно глупых вариантов: в каждом
   вопросе есть хотя бы один вариант, который ВЫГЛЯДИТ ответственным,
   но проверкой не является (например «попросить ИИ добавить источники»).
   ============================================================ */
window.AIE_QUESTIONS = [

/* ======================= CORE (все роли) ======================= */

{ id: "C1", block: "core", dim: "verification",
  prompt: { en: "An AI draft of your competitive analysis contains six specific market-share figures. No sources. The deck goes to the board tomorrow morning.",
            ru: "ИИ-черновик конкурентного анализа содержит шесть конкретных цифр по долям рынка. Источников нет. Завтра утром — совет директоров." },
  options: [
    { id: "a", lean: 1, s: { verification: -2, risk: -1 },
      text: { en: "Ship it — it's clearly a draft and the board knows that.",
              ru: "Отправить как есть — это же черновик, совет это понимает." },
      why: { en: "Nobody downstream treats a number in a board deck as a draft. A figure with no provenance is a liability with your name on it.",
             ru: "Никто дальше по цепочке не считает цифру в совете «черновиком». Цифра без происхождения — это ваша личная ответственность." } },
    { id: "b", lean: 1, s: { verification: -1 },
      text: { en: "Ask the AI to add sources for each figure, then ship.",
              ru: "Попросить ИИ добавить источники к каждой цифре и отправить." },
      why: { en: "The classic trap. A model that can invent a number can invent a citation for it — and a fake source is worse than none, because it stops others from checking.",
             ru: "Классическая ловушка. Модель, выдумавшая цифру, выдумает и ссылку на неё — а фальшивый источник хуже отсутствующего: он останавливает чужую проверку." } },
    { id: "c", lean: 0, s: { verification: 2, delegation: 1, risk: 1 },
      text: { en: "Check each figure against a primary source; keep the structure and argument, drop or mark every number you can't confirm.",
              ru: "Проверить каждую цифру по первоисточнику; структуру и аргументацию оставить, а все неподтверждённые числа убрать или пометить." },
      why: { en: "Right split of labour: the draft's real value was the structure and the argument, which cost you nothing to get. The numbers are the part only you can stand behind.",
             ru: "Верное разделение труда: ценность черновика — структура и аргументация, они достались бесплатно. Цифры — та часть, за которую можете отвечать только вы." } },
    { id: "d", lean: -1, s: { delegation: -1, iteration: -1, verification: 1 },
      text: { en: "Discard the draft and rebuild the analysis from scratch yourself.",
              ru: "Выбросить черновик и собрать анализ с нуля самому." },
      why: { en: "Safe but wasteful. You threw away the scaffolding along with the bad numbers — and you'll rebuild the same structure by hand tonight.",
             ru: "Безопасно, но расточительно. Вместе с плохими цифрами выброшен каркас — и сегодня ночью вы соберёте ту же структуру руками." } },
  ] },

{ id: "C2", block: "core", dim: "delegation",
  prompt: { en: "Your team missed a committed date. You have to tell a customer who is already angry, and the relationship matters.",
            ru: "Команда сорвала обещанный срок. Нужно сообщить клиенту, который уже раздражён, а отношения с ним важны." },
  options: [
    { id: "a", lean: 1, s: { delegation: -2, risk: -1 },
      text: { en: "Have the AI write the message and send it — it phrases these things better than you do under stress.",
              ru: "Пусть ИИ напишет письмо, и отправить — под стрессом он формулирует лучше вас." },
      why: { en: "Generic apology prose is exactly what a frustrated customer reads as not being taken seriously. Also: the accountability is yours either way, so the judgement should be too.",
             ru: "Обобщённые извинения — ровно то, что раздражённый клиент читает как «меня не восприняли всерьёз». И ответственность всё равно ваша, значит и решение должно быть вашим." } },
    { id: "b", lean: 0, s: { delegation: 2, context: 1 },
      text: { en: "Decide yourself what to say and concede; use AI to pressure-test it — what will they object to, what am I burying — then write it in your own words.",
              ru: "Самому решить, что сказать и что признать; через ИИ проверить позицию — где возразят, что я прячу — и написать своими словами." },
      why: { en: "Best use of AI in a human moment: as an adversary who rehearses you, not as a ghostwriter. The judgement, the concession and the voice stay yours.",
             ru: "Лучшее применение ИИ в человеческой ситуации: как оппонент для репетиции, а не как литературный негр. Решение, уступка и голос остаются вашими." } },
    { id: "c", lean: -1, s: { delegation: 0, iteration: -1 },
      text: { en: "Don't involve AI at all — this is a human conversation.",
              ru: "Не привлекать ИИ вообще — это человеческий разговор." },
      why: { en: "Defensible, and far better than option A. But you gave up a free rehearsal: 'what's the strongest objection to this message' costs two minutes and often changes it.",
             ru: "Позиция разумная и много лучше варианта A. Но вы отказались от бесплатной репетиции: «какое самое сильное возражение на это письмо» стоит две минуты и часто меняет текст." } },
    { id: "d", lean: 1, s: { delegation: -1, risk: -2 },
      text: { en: "Paste the full customer thread and contract into a consumer AI tool and ask for the best recovery strategy.",
              ru: "Вставить всю переписку с клиентом и договор в общедоступный ИИ-сервис и спросить стратегию спасения." },
      why: { en: "Two failures at once: a customer contract in an unvetted tool, and strategy outsourced on a relationship whose history only you know.",
             ru: "Два провала сразу: договор клиента в непроверенном сервисе и стратегия, отданная наружу по отношениям, историю которых знаете только вы." } },
  ] },

{ id: "C3", block: "core", dim: "context",
  prompt: { en: "The AI's first draft of your document is technically fine and completely generic — it could be about any company.",
            ru: "Первый ИИ-черновик документа технически нормальный и абсолютно общий — он мог бы быть про любую компанию." },
  options: [
    { id: "a", lean: 1, s: { context: -1, iteration: -1 },
      text: { en: "Re-prompt: 'make it more specific and less generic'.",
              ru: "Переспросить: «сделай конкретнее и менее обобщённо»." },
      why: { en: "The model has nothing specific to be specific with. You'll get more confident-sounding generic text, which is worse — it hides the emptiness.",
             ru: "Модели нечем быть конкретной. Вы получите более уверенно звучащий общий текст — и это хуже: он маскирует пустоту." } },
    { id: "b", lean: 0, s: { context: 2, leverage: 1 },
      text: { en: "Paste in the raw material: real constraints, the actual numbers, quotes from your users, and one past document you consider good.",
              ru: "Дать сырьё: реальные ограничения, настоящие цифры, цитаты пользователей и один прошлый документ, который вы считаете хорошим." },
      why: { en: "Generic output is almost always an input problem, not a model problem. The past good document is the highest-leverage item — it transfers taste, which is hard to describe.",
             ru: "Обобщённый вывод почти всегда проблема входа, а не модели. Самый сильный элемент — прошлый хороший документ: он передаёт вкус, который трудно описать словами." } },
    { id: "c", lean: -1, s: { context: 0, delegation: -1, iteration: -1 },
      text: { en: "Give up on the draft and write the document yourself.",
              ru: "Отказаться от черновика и написать документ самому." },
      why: { en: "You may end up here, and that's fine — but not before spending the five minutes on context, which is usually what the whole problem was.",
             ru: "Возможно, вы к этому и придёте, и это нормально — но не раньше пяти минут на контекст, в которых обычно и была вся проблема." } },
    { id: "d", lean: 1, s: { context: -1, verification: -1 },
      text: { en: "Keep it — generic is a safe default and nobody reads these closely anyway.",
              ru: "Оставить — обобщённое безопасно, всё равно такие документы никто внимательно не читает." },
      why: { en: "If that's true, the document shouldn't exist. Writing things nobody reads is the least efficient thing on this whole test.",
             ru: "Если это правда, документа не должно существовать. Писать то, что никто не читает, — самое неэффективное из всего в этом тесте." } },
  ] },

{ id: "C4", block: "core", dim: "iteration",
  prompt: { en: "You've re-prompted eight times over forty minutes. Each answer is wrong in a slightly different way. The task itself would take you about an hour by hand.",
            ru: "Восемь переспросов за сорок минут. Каждый ответ неверен чуть по-новому. Сама задача руками заняла бы примерно час." },
  options: [
    { id: "a", lean: 1, s: { iteration: -2 },
      text: { en: "Keep going — you're clearly close, and starting over wastes the forty minutes.",
              ru: "Продолжать — вы явно близко, а начать заново значит потерять сорок минут." },
      why: { en: "Sunk cost, and 'wrong in a different way each time' is the signal that you're not converging. The forty minutes are gone whatever you do next.",
             ru: "Ошибка невозвратных затрат, а «неверно каждый раз по-новому» — признак, что сходимости нет. Сорок минут потеряны в любом случае." } },
    { id: "b", lean: 0, s: { iteration: 2, delegation: 1, context: 1 },
      text: { en: "Stop. Decide whether the task decomposes — hand over the mechanical part, do the judgement part yourself.",
              ru: "Остановиться. Понять, разбирается ли задача на части — механическую отдать, содержательную сделать самому." },
      why: { en: "Repeated near-misses usually mean one task is actually two: a part the model can do and a part that needs something it doesn't have. Splitting beats re-prompting.",
             ru: "Повторяющиеся «почти» обычно значат, что задача на самом деле две: одна для модели, вторая требует того, чего у неё нет. Разделить лучше, чем переспрашивать." } },
    { id: "c", lean: -1, s: { iteration: 1, delegation: -1 },
      text: { en: "Abandon AI for this and do the whole hour by hand.",
              ru: "Бросить ИИ на этой задаче и сделать весь час руками." },
      why: { en: "Correct instinct — time-boxing — applied bluntly. You stopped the bleeding but kept the mechanical parts you could still have delegated.",
             ru: "Инстинкт верный — тайм-бокс, — но применён грубо. Кровотечение остановили, но оставили себе механические части, которые всё ещё можно было отдать." } },
    { id: "d", lean: 1, s: { iteration: -1, verification: -1 },
      text: { en: "Take the least-wrong version and fix it up — it's 80% there.",
              ru: "Взять наименее плохую версию и подправить — она процентов на 80 готова." },
      why: { en: "Editing subtly-wrong output is often slower than writing it fresh, and it leaves the errors you didn't notice. 'Looks 80% done' is not the same as 'is 80% done'.",
             ru: "Править тонко-неверное часто дольше, чем написать заново, и остаются незамеченные ошибки. «Выглядит на 80%» — не то же, что «готово на 80%»." } },
  ] },

{ id: "C5", block: "core", dim: "risk",
  prompt: { en: "To get a good answer you'd need to paste in a file containing unreleased financials and a list of named customers.",
            ru: "Чтобы получить хороший ответ, нужно вставить файл с неопубликованными финансами и списком клиентов поимённо." },
  options: [
    { id: "a", lean: 1, s: { risk: -2 },
      text: { en: "Paste it — chats are private and it's a huge time saver.",
              ru: "Вставить — чаты приватные, а экономия времени огромная." },
      why: { en: "'Private' is a product setting, not a legal guarantee. Unreleased financials plus named customers is the combination that turns a productivity story into an incident report.",
             ru: "«Приватно» — настройка продукта, а не юридическая гарантия. Неопубликованные финансы плюс имена клиентов — то сочетание, которое превращает историю про продуктивность в инцидент." } },
    { id: "b", lean: 0, s: { risk: 2, delegation: 1 },
      text: { en: "Use the tool your company has actually cleared, or strip the identifiers and keep the shape of the data.",
              ru: "Использовать инструмент, который компания официально разрешила, либо убрать идентификаторы, сохранив форму данных." },
      why: { en: "Both halves matter: the approved tool handles the legal side, and anonymising teaches you that the model almost never needed the names to answer the question.",
             ru: "Важны обе половины: разрешённый инструмент закрывает юридическую сторону, а обезличивание показывает, что имена модели для ответа почти никогда не были нужны." } },
    { id: "c", lean: -1, s: { risk: 1, delegation: -1 },
      text: { en: "Drop the task — if it needs that data, AI can't help.",
              ru: "Отказаться от задачи — раз нужны такие данные, ИИ тут не помощник." },
      why: { en: "Safe, and sometimes right. But most such tasks survive anonymisation intact, so this often trades a real gain for a risk you could have removed in two minutes.",
             ru: "Безопасно и иногда верно. Но большинство таких задач переживают обезличивание без потерь — то есть вы меняете реальную выгоду на риск, который снимался за две минуты." } },
    { id: "d", lean: 1, s: { risk: -1, verification: -1 },
      text: { en: "Paste it but ask the model not to remember or train on it.",
              ru: "Вставить, но попросить модель не запоминать и не обучаться на этом." },
      why: { en: "An instruction in the prompt does not control what the vendor stores or how the request is logged. Retention is a contract setting, not something you can ask for mid-conversation.",
             ru: "Инструкция в запросе не управляет тем, что хранит поставщик и как логируется обращение. Ретеншен — настройка договора, а не просьба в середине диалога." } },
  ] },

{ id: "C6", block: "core", dim: "leverage",
  prompt: { en: "The same report is due every Monday. For three months you've produced it in a fresh chat, re-explaining the format each time.",
            ru: "Один и тот же отчёт нужен каждый понедельник. Три месяца вы делаете его в новом чате, каждый раз заново объясняя формат." },
  options: [
    { id: "a", lean: 0, s: { leverage: -1 },
      text: { en: "It works and takes twenty minutes — leave it alone.",
              ru: "Работает и занимает двадцать минут — не трогать." },
      why: { en: "Twenty minutes a week is a day a year, and the re-explaining is the part with no value in it. Not a disaster; just the clearest unclaimed gain on the list.",
             ru: "Двадцать минут в неделю — это день в год, и объяснение формата — та часть, в которой нет никакой ценности. Не катастрофа, просто самый очевидный неподобранный выигрыш." } },
    { id: "b", lean: 0, s: { leverage: 2, context: 1 },
      text: { en: "Write the format and rules down once as a reusable prompt or template, and share it so the rest of the team stops re-inventing it.",
              ru: "Один раз записать формат и правила как переиспользуемый промпт или шаблон и отдать команде, чтобы не изобретали заново." },
      why: { en: "This is where individual AI use turns into organisational efficiency. The sharing matters more than the saving — you're removing the same twenty minutes from several calendars.",
             ru: "Здесь личное использование ИИ превращается в эффективность организации. Передача важнее экономии: вы убираете те же двадцать минут из нескольких календарей." } },
    { id: "c", lean: 1, s: { leverage: 0, verification: -2 },
      text: { en: "Automate it end-to-end so the report generates and sends itself with no one reading it.",
              ru: "Автоматизировать полностью, чтобы отчёт формировался и отправлялся сам, без чтения." },
      why: { en: "Automating the drafting is right; automating away the last human read is how a wrong number ships every Monday until someone notices in month four.",
             ru: "Автоматизировать подготовку — правильно; убрать последний человеческий взгляд — способ отправлять неверную цифру каждый понедельник, пока на четвёртый месяц кто-то не заметит." } },
    { id: "d", lean: -1, s: { leverage: -2, delegation: -1 },
      text: { en: "Go back to writing it by hand — at least then you know what's in it.",
              ru: "Вернуться к ручному варианту — так хотя бы знаешь, что внутри." },
      why: { en: "Knowing what's in it is a verification need, and verification doesn't require doing the typing. You can read a generated report closely in far less time than writing one.",
             ru: "«Знать, что внутри» — это потребность в проверке, а проверка не требует набирать текст руками. Внимательно прочитать сгенерированный отчёт быстрее, чем написать его." } },
  ] },

{ id: "C7", block: "core", dim: "risk",
  prompt: { en: "Something you shipped contains an error. It came from AI output you passed on without catching it.",
            ru: "В том, что вы выпустили, есть ошибка. Она пришла из ИИ-ответа, который вы передали дальше, не поймав её." },
  options: [
    { id: "a", lean: 0, s: { risk: 2, verification: 1 },
      text: { en: "It's your error. Fix it, and change the check that would have caught it.",
              ru: "Это ваша ошибка. Исправить и поменять ту проверку, которая должна была её поймать." },
      why: { en: "The only tenable position, and the second half is what separates a professional from someone who merely apologises: the process changes, not just the artefact.",
             ru: "Единственная состоятельная позиция, и вторая половина отличает профессионала от того, кто просто извинился: меняется процесс, а не только сам артефакт." } },
    { id: "b", lean: 1, s: { risk: -2 },
      text: { en: "Flag that this part was AI-generated so people calibrate their trust accordingly.",
              ru: "Пометить, что этот кусок сгенерирован ИИ, чтобы люди соответственно калибровали доверие." },
      why: { en: "Disclosure is good practice up front; used after an error it's a way of moving blame to a tool that can't hold any. You reviewed it, so you own it.",
             ru: "Раскрытие — хорошая практика заранее; после ошибки это способ переложить вину на инструмент, который её нести не может. Вы это пропустили — вы и отвечаете." } },
    { id: "c", lean: -1, s: { risk: 0, delegation: -2, leverage: -1 },
      text: { en: "Stop using AI for this category of work entirely.",
              ru: "Полностью перестать использовать ИИ для такого класса задач." },
      why: { en: "An over-correction that costs you the wins too. One escaped error means the checking step was missing or too weak — that's a fixable process gap, not a verdict on the tool.",
             ru: "Гиперкоррекция, которая забирает и выигрыши. Одна пропущенная ошибка означает, что шага проверки не было или он был слабым, — это чинимый провал процесса, а не приговор инструменту." } },
    { id: "d", lean: 1, s: { risk: -1, verification: -1 },
      text: { en: "Add a blanket disclaimer to future outputs and carry on as before.",
              ru: "Добавить общий дисклеймер к будущим материалам и работать как раньше." },
      why: { en: "A disclaimer changes nothing about whether the next number is right. It transfers a little reputational risk and zero actual risk.",
             ru: "Дисклеймер никак не влияет на то, верна ли следующая цифра. Он переносит немного репутационного риска и ноль фактического." } },
  ] },

{ id: "C8", block: "core", dim: "delegation",
  prompt: { en: "Four tasks are on your desk. Which is the WORST fit for AI right now?",
            ru: "На столе четыре задачи. Какая ХУЖЕ всего подходит для ИИ прямо сейчас?" },
  options: [
    { id: "a", lean: 0, s: { delegation: 2, risk: 1 },
      text: { en: "Choosing which of two teams absorbs a painful cut, given their history and who is about to quit.",
              ru: "Решить, какая из двух команд примет на себя болезненное сокращение, зная их историю и кто вот-вот уволится." },
      why: { en: "Correct. The deciding inputs — politics, history, who is fragile right now — are things the model has no access to and you cannot safely write down. Judgement on private context is the last thing to delegate.",
             ru: "Верно. Решающие входные данные — политика, история, кто сейчас хрупок — недоступны модели, и записать их безопасно нельзя. Решение на приватном контексте отдают последним." } },
    { id: "b", lean: -1, s: { delegation: -2 },
      text: { en: "Summarising four hundred support tickets into recurring themes.",
              ru: "Свести четыреста тикетов поддержки к повторяющимся темам." },
      why: { en: "This is close to the ideal AI task, not the worst: high volume, pattern-shaped, and cheap to spot-check by reading a sample from each cluster. Calling it a bad fit is leaving a day of work on the table.",
             ru: "Это почти идеальная задача для ИИ, а не худшая: большой объём, форма паттерна, дешёвая выборочная проверка. Считать её неподходящей — значит терять день работы." } },
    { id: "c", lean: -1, s: { delegation: -2 },
      text: { en: "Turning your rough bullet points into a structured first draft.",
              ru: "Превратить ваши черновые тезисы в структурированный первый черновик." },
      why: { en: "Also a strong fit, not a weak one — you supplied the thinking, the model supplies the prose, and you can see immediately whether it kept your meaning.",
             ru: "Тоже сильное попадание, а не слабое: мысль ваша, изложение от модели, и сразу видно, сохранился ли смысл." } },
    { id: "d", lean: 1, s: { delegation: -2, risk: -1 },
      text: { en: "None of them — with a good enough prompt all four are fine for AI.",
              ru: "Никакая — при достаточно хорошем промпте все четыре нормально решаются ИИ." },
      why: { en: "Prompting cannot supply information the model doesn't have. No phrasing gives it your org's politics or who is about to resign, and a confident answer built on that absence is the most expensive kind.",
             ru: "Промпт не может дать модели то, чего у неё нет. Никакая формулировка не передаст политику вашей организации и то, кто вот-вот уволится, — а уверенный ответ на этой пустоте самый дорогой." } },
  ] },

/* ======================= PRODUCT MANAGER ======================= */

{ id: "P1", block: "pm", dim: "verification",
  prompt: { en: "You ask AI to synthesise 120 user interviews. It returns five crisp themes with percentages attached to each.",
            ru: "Вы просите ИИ свести 120 интервью с пользователями. Он возвращает пять чётких тем с процентами по каждой." },
  options: [
    { id: "a", lean: 1, s: { verification: -2, risk: -1 },
      text: { en: "Take the themes and the percentages into the roadmap review.",
              ru: "Взять темы и проценты на ревью роадмапа." },
      why: { en: "The themes are probably useful; the percentages are the dangerous part. Precise-looking quantification of qualitative data is where AI output most often launders a guess into a fact.",
             ru: "Темы, скорее всего, полезны; опасны именно проценты. Точная на вид квантификация качественных данных — место, где ИИ чаще всего превращает догадку в «факт»." } },
    { id: "b", lean: 0, s: { verification: 2, context: 1, delegation: 1 },
      text: { en: "Keep the themes, drop the percentages, and read a sample of interviews per theme to confirm the theme is real and not an artefact of phrasing.",
              ru: "Темы оставить, проценты убрать и прочитать выборку интервью по каждой теме — убедиться, что тема реальна, а не артефакт формулировок." },
      why: { en: "Clustering is genuinely what the machine is good at. Sampling back to raw quotes is the cheap check that catches both invented themes and merged-but-different problems.",
             ru: "Кластеризация — как раз сильная сторона машины. Возврат к сырым цитатам по выборке — дешёвая проверка, ловящая и выдуманные темы, и склейку разных проблем в одну." } },
    { id: "c", lean: -1, s: { delegation: -2, iteration: -1 },
      text: { en: "Re-read all 120 interviews yourself and build the themes by hand.",
              ru: "Перечитать все 120 интервью самому и собрать темы руками." },
      why: { en: "This is the single biggest unclaimed time saving in the PM job, and human coders introduce their own consistency problems over 120 documents.",
             ru: "Это крупнейшая неподобранная экономия времени в работе продакта, а на 120 документах человек-кодировщик и сам теряет консистентность." } },
    { id: "d", lean: 1, s: { verification: -1 },
      text: { en: "Ask the AI how confident it is in each theme and use that to decide.",
              ru: "Спросить у ИИ, насколько он уверен в каждой теме, и по этому решать." },
      why: { en: "Self-reported confidence is generated text like everything else; it correlates with fluency, not with correctness. It feels like verification and isn't.",
             ru: "Самооценка уверенности — такой же сгенерированный текст; она коррелирует с гладкостью, а не с правильностью. Ощущается как проверка, но ею не является." } },
  ] },

{ id: "P2", block: "pm", dim: "delegation",
  prompt: { en: "You paste your backlog in and ask AI to prioritise it with RICE. It returns a ranked table with reach, impact and confidence filled in.",
            ru: "Вы вставляете бэклог и просите ИИ приоритизировать по RICE. Возвращается ранжированная таблица с заполненными reach, impact и confidence." },
  options: [
    { id: "a", lean: 1, s: { delegation: -2, verification: -2 },
      text: { en: "Use the ranking — the framework was applied consistently, which is more than most teams manage.",
              ru: "Использовать ранжирование — фреймворк применён последовательно, что удаётся не каждой команде." },
      why: { en: "Consistently applied to invented inputs. The model had no access to your reach numbers, so it produced plausible ones — and RICE's output is only as good as those.",
             ru: "Последовательно применён к выдуманным входам. У модели не было ваших цифр охвата, поэтому она выдала правдоподобные — а результат RICE не лучше своих входов." } },
    { id: "b", lean: 0, s: { delegation: 2, context: 2, verification: 1 },
      text: { en: "Keep the structure, replace every reach and confidence number with one from your analytics or a named source, and re-rank.",
              ru: "Структуру оставить, каждое число reach и confidence заменить на взятое из аналитики или названного источника и переранжировать." },
      why: { en: "The right division: scoring frameworks are mechanical and worth delegating, the estimates behind them are evidence and must be sourced. Doing this also exposes which items nobody can size.",
             ru: "Верное разделение: механику фреймворка отдать стоит, оценки за ним — это доказательства, у них должен быть источник. Заодно вскроется, какие пункты никто не может оценить." } },
    { id: "c", lean: -1, s: { delegation: -1, leverage: -1 },
      text: { en: "Prioritisation is a judgement call — do the whole thing in a spreadsheet as usual.",
              ru: "Приоритизация — вопрос суждения; сделать всё в таблице как обычно." },
      why: { en: "Judgement belongs to you, but the tabulation and the consistency checking don't. You're paying with your evenings for something mechanical.",
             ru: "Суждение ваше, но сведение таблицы и проверка консистентности — нет. Вы платите вечерами за механическую работу." } },
    { id: "d", lean: 1, s: { delegation: -1, risk: -1 },
      text: { en: "Take it to the stakeholder meeting as the AI's neutral, unbiased view.",
              ru: "Принести на встречу со стейкхолдерами как нейтральный, непредвзятый взгляд ИИ." },
      why: { en: "There is no neutral view — the model reproduced whichever framing your prompt carried. Presenting it as objective borrows an authority nothing earned.",
             ru: "Нейтрального взгляда не существует — модель воспроизвела ту рамку, что несла ваша постановка. Подавать это как объективность — занимать авторитет, который никто не заработал." } },
  ] },

{ id: "P3", block: "pm", dim: "verification",
  prompt: { en: "Your A/B test readout is due. AI reads the results table and reports that the variant wins, with the result described as statistically significant.",
            ru: "Нужен разбор A/B-теста. ИИ читает таблицу результатов и сообщает, что вариант выигрывает, а результат статистически значим." },
  options: [
    { id: "a", lean: 1, s: { verification: -2 },
      text: { en: "Ship the variant — significance is the bar and it cleared it.",
              ru: "Раскатывать вариант — планка в значимости, она пройдена." },
      why: { en: "'Significant' is a word the model can produce without doing the arithmetic, and even a correct p-value says nothing about whether the test ran long enough or the metric was the right one.",
             ru: "«Значимо» — слово, которое модель выдаёт без арифметики, а даже верный p-value ничего не говорит о том, достаточно ли крутился тест и та ли это метрика." } },
    { id: "b", lean: 0, s: { verification: 2, delegation: 1 },
      text: { en: "Recompute the test yourself, check sample size and duration against the plan, and look at whether the guardrail metrics moved.",
              ru: "Пересчитать тест самому, сверить размер выборки и длительность с планом и посмотреть, не сдвинулись ли защитные метрики." },
      why: { en: "Statistics are checkable in minutes, and this is one of the few places where the verification is fully mechanical — so there is no excuse for skipping it. Guardrails are what the summary will never volunteer.",
             ru: "Статистику можно перепроверить за минуты — и это один из немногих случаев, где проверка полностью механическая, а значит оправданий пропустить её нет. Про защитные метрики резюме никогда не скажет само." } },
    { id: "c", lean: 1, s: { verification: -1, iteration: -1 },
      text: { en: "Ask the AI to double-check its own analysis.",
              ru: "Попросить ИИ перепроверить собственный анализ." },
      why: { en: "It will usually agree with itself, and when it doesn't you have two answers and no way to choose. Self-review is not independent review.",
             ru: "Обычно он согласится сам с собой, а если нет — у вас два ответа и никакого способа выбрать. Самопроверка не является независимой проверкой." } },
    { id: "d", lean: -1, s: { delegation: -1, verification: 1 },
      text: { en: "Don't let AI near experiment data; have the data scientist do the whole readout.",
              ru: "Не подпускать ИИ к данным эксперимента; пусть весь разбор делает дата-сайентист." },
      why: { en: "Safe, but it wastes a genuinely good use — drafting the narrative and the caveats around numbers you've already verified — and it puts a queue between you and every readout.",
             ru: "Безопасно, но теряется по-настоящему хорошее применение — собрать нарратив и оговорки вокруг уже проверенных цифр, — и между вами и каждым разбором появляется очередь." } },
  ] },

{ id: "P4", block: "pm", dim: "context",
  prompt: { en: "You need a PRD for a feature you've discussed with engineering for two weeks. You have notes, constraints and three open questions.",
            ru: "Нужен PRD по фиче, которую вы две недели обсуждали с инженерами. Есть заметки, ограничения и три открытых вопроса." },
  options: [
    { id: "a", lean: 1, s: { context: -1, delegation: -1 },
      text: { en: "Describe the feature in two sentences and let AI produce the full PRD.",
              ru: "Описать фичу в двух предложениях и дать ИИ выпустить полный PRD." },
      why: { en: "You'll get a document that answers none of the three open questions and quietly invents positions on them, which is worse than leaving them open.",
             ru: "Получится документ, который не отвечает ни на один из трёх открытых вопросов и при этом тихо выдумывает по ним позицию, — это хуже, чем оставить их открытыми." } },
    { id: "b", lean: 0, s: { context: 2, delegation: 1, verification: 1 },
      text: { en: "Give it the notes, the constraints and a past PRD as a model; keep the open questions marked open and answer them with engineering.",
              ru: "Дать заметки, ограничения и прошлый PRD как образец; открытые вопросы оставить помеченными и закрыть их с инженерами." },
      why: { en: "Maximum leverage with the judgement preserved. Explicitly keeping unknowns as unknowns is the discipline that AI drafting most often erodes — fluent prose hates an admitted gap.",
             ru: "Максимальный рычаг с сохранением суждения. Явно держать неизвестное неизвестным — та дисциплина, которую ИИ-черновики размывают чаще всего: гладкий текст не терпит признанных пробелов." } },
    { id: "c", lean: -1, s: { delegation: -2, iteration: -1 },
      text: { en: "Write the PRD yourself from the notes — the thinking is already done anyway.",
              ru: "Написать PRD самому по заметкам — мышление всё равно уже проделано." },
      why: { en: "Exactly because the thinking is done, this is the cheapest possible delegation: you're only paying for transcription and structure.",
             ru: "Именно потому, что мышление проделано, это самое дешёвое возможное делегирование: вы платите только за изложение и структуру." } },
    { id: "d", lean: 1, s: { context: 1, verification: -2 },
      text: { en: "Give it everything, then send the output straight to engineering for review.",
              ru: "Дать всё и сразу отправить результат инженерам на ревью." },
      why: { en: "Good context, no checkpoint. You're spending your team's attention on catching errors you could have caught in one read, and it costs you credibility each time.",
             ru: "Контекст хороший, контрольной точки нет. Вы тратите внимание команды на ошибки, которые ловятся одним чтением, и каждый раз платите за это доверием." } },
  ] },

{ id: "P5", block: "pm", dim: "risk",
  prompt: { en: "AI drafts customer-facing release notes describing what the feature does and implying a guarantee about data handling.",
            ru: "ИИ готовит публичные release notes: что делает фича, с намёком на гарантию по обработке данных." },
  options: [
    { id: "a", lean: 0, s: { risk: 2, verification: 1 },
      text: { en: "Check every claim against what the system actually does, and route anything that reads as a promise past legal.",
              ru: "Сверить каждое утверждение с тем, что система реально делает, и всё, что читается как обещание, провести через юристов." },
      why: { en: "Public claims about data handling are commitments, not copy. The model writes reassuring sentences by default — reassurance is exactly the register that creates obligations.",
             ru: "Публичные утверждения про обработку данных — это обязательства, а не текст. Модель по умолчанию пишет успокаивающе, а успокаивающий регистр как раз и создаёт обязательства." } },
    { id: "b", lean: 1, s: { risk: -2 },
      text: { en: "Publish — release notes are marketing copy and nobody reads them that closely.",
              ru: "Публиковать — release notes это маркетинговый текст, никто не читает так внимательно." },
      why: { en: "Regulators, enterprise customers and opposing counsel read them exactly that closely, and a published promise is durable in a way the draft never felt.",
             ru: "Регуляторы, корпоративные клиенты и юристы противной стороны читают именно так внимательно, а опубликованное обещание живёт куда дольше, чем ощущался черновик." } },
    { id: "c", lean: 1, s: { risk: -1, verification: -1 },
      text: { en: "Ask the AI to remove anything legally risky, then publish.",
              ru: "Попросить ИИ убрать всё юридически рискованное и опубликовать." },
      why: { en: "The model has no idea what your jurisdiction, contracts and past public statements commit you to. It will remove the obviously scary words and leave the actual exposure.",
             ru: "Модель не знает, к чему вас обязывают юрисдикция, договоры и прошлые публичные заявления. Она уберёт очевидно страшные слова и оставит настоящий риск." } },
    { id: "d", lean: -1, s: { risk: 1, delegation: -1 },
      text: { en: "Write all customer-facing copy by hand as a standing rule.",
              ru: "Как правило, весь публичный текст писать руками." },
      why: { en: "Over-broad. The efficient rule is narrower: draft freely, but treat every factual and every promissory sentence as requiring a source or a reviewer.",
             ru: "Слишком широко. Эффективное правило уже: черновик — свободно, но каждое фактическое и каждое обещающее предложение требует источника или ревьюера." } },
  ] },

{ id: "P6", block: "pm", dim: "leverage",
  prompt: { en: "You've found a prompt that reliably turns messy discovery notes into a structured opportunity brief. It saves you an hour each time.",
            ru: "Вы нашли промпт, который надёжно превращает сырые заметки дискавери в структурированный бриф возможности. Экономит час каждый раз." },
  options: [
    { id: "a", lean: 0, s: { leverage: 2, verification: 1 },
      text: { en: "Put it in the team's shared space with a note on where it fails and what to check before trusting the output.",
              ru: "Положить в общее пространство команды с пометкой, где он ломается и что проверять, прежде чем доверять результату." },
      why: { en: "The failure note is what makes sharing safe rather than viral. Spreading a prompt without its limits spreads a trap along with the tool.",
             ru: "Заметка про сбои — то, что делает передачу безопасной, а не вирусной. Раздать промпт без его границ — раздать вместе с инструментом и ловушку." } },
    { id: "b", lean: 0, s: { leverage: 0 },
      text: { en: "Keep using it yourself; others will find their own way.",
              ru: "Пользоваться самому; остальные найдут свой способ." },
      why: { en: "An hour a week for one person versus for six. This is the difference between being personally fast and making the function fast.",
             ru: "Час в неделю у одного против часа у шестерых. Это и есть разница между «я быстрый» и «функция быстрая»." } },
    { id: "c", lean: 1, s: { leverage: 1, verification: -2 },
      text: { en: "Share it as a finished tool so juniors can produce briefs without needing to review them.",
              ru: "Раздать как готовый инструмент, чтобы джуны делали брифы, не проверяя результат." },
      why: { en: "You've scaled the output and removed the judgement. Juniors are precisely the people least able to spot where this prompt quietly goes wrong.",
             ru: "Вы масштабировали выход и убрали суждение. Джуны — ровно те, кто хуже всех заметит, где этот промпт тихо ошибается." } },
    { id: "d", lean: -1, s: { leverage: -1, iteration: -1 },
      text: { en: "Rewrite the prompt from scratch every time to keep your thinking sharp.",
              ru: "Каждый раз переписывать промпт заново, чтобы не терять остроту мышления." },
      why: { en: "Sharpness comes from the discovery and the decisions, not from retyping instructions. This spends attention on the one part that carries none.",
             ru: "Острота берётся из дискавери и решений, а не из перенабора инструкций. Здесь внимание тратится ровно на ту часть, где его ценность нулевая." } },
  ] },

{ id: "P7", block: "pm", dim: "context",
  prompt: { en: "AI proposes a feature that would clearly help users. It also happens to cut directly against a strategic bet your CEO made publicly last quarter.",
            ru: "ИИ предлагает фичу, которая явно помогла бы пользователям. Она же прямо противоречит стратегической ставке, которую CEO публично сделал в прошлом квартале." },
  options: [
    { id: "a", lean: 0, s: { context: 2, delegation: 1 },
      text: { en: "Treat it as a signal worth understanding — work out why the user need points away from the bet, then take that tension to the CEO rather than the feature.",
              ru: "Отнестись как к сигналу: понять, почему потребность пользователя уводит от ставки, и нести к CEO это противоречие, а не саму фичу." },
      why: { en: "The model surfaced a real tension precisely because it didn't know the politics. That naivety is the value — but the thing worth escalating is the conflict, not a feature request.",
             ru: "Модель вскрыла реальное противоречие именно потому, что не знала политики. Эта наивность и есть ценность — но эскалировать стоит конфликт, а не заявку на фичу." } },
    { id: "b", lean: -1, s: { context: -1, delegation: -1 },
      text: { en: "Discard it — the AI doesn't know our strategy, so its suggestions aren't usable.",
              ru: "Отбросить — ИИ не знает нашу стратегию, значит его предложения неприменимы." },
      why: { en: "Discarding every suggestion that conflicts with the current bet is how a strategy stops being testable. Not knowing the politics is a feature in idea generation.",
             ru: "Отбрасывать всё, что спорит с текущей ставкой, — способ сделать стратегию непроверяемой. Незнание политики в генерации идей — это плюс." } },
    { id: "c", lean: 1, s: { context: -1, risk: -1 },
      text: { en: "Put it in the roadmap — user value should win and the AI has no reason to be biased.",
              ru: "Поставить в роадмап — польза пользователю важнее, а у ИИ нет причин быть предвзятым." },
      why: { en: "Unbiased is not the same as informed. Shipping against a public commitment without surfacing the conflict first is a political error you'll pay for personally.",
             ru: "Непредвзятый — не значит осведомлённый. Пойти против публичного обязательства, не проговорив конфликт, — политическая ошибка, за которую заплатите лично вы." } },
    { id: "d", lean: 1, s: { context: -1, verification: -1 },
      text: { en: "Ask the AI whether it conflicts with the strategy, and go with its verdict.",
              ru: "Спросить у ИИ, противоречит ли это стратегии, и поступить по его вердикту." },
      why: { en: "You're asking a system without the relevant information to arbitrate the question you already answered correctly yourself.",
             ru: "Вы просите систему без нужной информации рассудить вопрос, на который сами уже ответили верно." } },
  ] },

{ id: "P8", block: "pm", dim: "iteration",
  prompt: { en: "It's 4pm. A one-page summary of a decision is needed by 6pm. The AI draft is structurally right but the tone is wrong for this audience.",
            ru: "16:00. К 18:00 нужна страница с резюме решения. ИИ-черновик структурно верный, но тон не тот для этой аудитории." },
  options: [
    { id: "a", lean: 0, s: { iteration: 2, delegation: 1 },
      text: { en: "Rewrite the tone yourself — it's the part you're fastest at and the part that carries the relationship.",
              ru: "Тон переписать самому — это то, что у вас получается быстрее всего и то, что несёт отношения." },
      why: { en: "Correct economics. Structure is slow for humans and fast for models; tone for a specific audience is the reverse. Play each to its strength and you're done in twenty minutes.",
             ru: "Верная экономика. Структура для человека медленная, для модели быстрая; тон под конкретную аудиторию — наоборот. Каждому своё — и вы закончите за двадцать минут." } },
    { id: "b", lean: 1, s: { iteration: -1 },
      text: { en: "Describe the tone you want and regenerate until it lands.",
              ru: "Описать нужный тон и перегенерировать, пока не попадёт." },
      why: { en: "Tone for a specific room is hard to specify and easy to demonstrate. You'll spend the two hours approximating something you could have typed.",
             ru: "Тон для конкретной комнаты трудно описать и легко показать. Вы потратите два часа на приближение к тому, что могли бы просто напечатать." } },
    { id: "c", lean: 1, s: { iteration: -1, verification: -1 },
      text: { en: "Send it as is — structure matters more than tone and the deadline is real.",
              ru: "Отправить как есть — структура важнее тона, а дедлайн реальный." },
      why: { en: "For a decision summary, tone is how seriously the decision gets taken. Wrong register to this audience can cost you the decision you're summarising.",
             ru: "В резюме решения тон определяет, насколько серьёзно решение воспримут. Неверный регистр для этой аудитории может стоить вам самого решения." } },
    { id: "d", lean: -1, s: { iteration: -2, delegation: -1 },
      text: { en: "Start over and write the whole page yourself.",
              ru: "Начать заново и написать всю страницу самому." },
      why: { en: "You'd be discarding the part that was already right. With two hours left, rebuilding the structure is the risk you don't need to take.",
             ru: "Вы выбросите то, что уже верно. За два часа до срока пересборка структуры — риск, который брать незачем." } },
  ] },

/* ======================= SYSTEM ANALYST ======================= */

{ id: "S1", block: "sa", dim: "verification",
  prompt: { en: "AI generates an OpenAPI spec from your description of an endpoint. It looks clean and complete.",
            ru: "ИИ генерирует OpenAPI-спеку по вашему описанию эндпоинта. Выглядит чисто и полно." },
  options: [
    { id: "a", lean: 0, s: { verification: 2, delegation: 1 },
      text: { en: "Review it specifically for error codes, idempotency, pagination limits and auth scopes — the parts a happy-path description never mentions.",
              ru: "Просмотреть именно на коды ошибок, идемпотентность, лимиты пагинации и скоупы авторизации — то, чего не бывает в описании happy path." },
      why: { en: "Models reproduce the shape of specs they've seen, which means a plausible happy path and thin failure semantics. Knowing exactly which sections to distrust is what makes this fast rather than a full re-read.",
             ru: "Модели воспроизводят форму виденных спек: правдоподобный happy path и жидкая семантика отказов. Знание, каким разделам не доверять, и делает проверку быстрой вместо полного перечитывания." } },
    { id: "b", lean: 1, s: { verification: -2, risk: -1 },
      text: { en: "Hand it to the backend team — they'll catch anything wrong during implementation.",
              ru: "Отдать бэкенду — они поймают всё неверное в ходе реализации." },
      why: { en: "They'll catch what breaks the build, not what's silently under-specified. An unmentioned error case becomes an undefined behaviour that surfaces in production.",
             ru: "Они поймают то, что ломает сборку, а не то, что молча недоописано. Неупомянутый случай ошибки становится неопределённым поведением, которое всплывёт в проде." } },
    { id: "c", lean: -1, s: { delegation: -2 },
      text: { en: "Write specs by hand — generated ones can't be trusted.",
              ru: "Писать спеки руками — генерированным нельзя доверять." },
      why: { en: "Spec writing is heavily boilerplate, and your hand-written version has the same happy-path bias plus typos. The answer is targeted review, not abstinence.",
             ru: "В спеках много рутины, а ваш ручной вариант имеет тот же перекос в happy path плюс опечатки. Ответ — прицельное ревью, а не отказ." } },
    { id: "d", lean: 1, s: { verification: -1 },
      text: { en: "Ask the AI to validate its own spec against best practice.",
              ru: "Попросить ИИ проверить свою спеку на соответствие лучшим практикам." },
      why: { en: "It will confirm it. Run it through an actual validator and a contract test instead — those fail on things no amount of self-assessment surfaces.",
             ru: "Он подтвердит. Прогоните через настоящий валидатор и контрактный тест — они падают на том, чего самооценка не вскрывает никогда." } },
  ] },

{ id: "S2", block: "sa", dim: "risk",
  prompt: { en: "You need a number from production. AI writes you a SQL query that looks correct.",
            ru: "Нужна цифра из продакшена. ИИ пишет вам SQL-запрос, который выглядит корректно." },
  options: [
    { id: "a", lean: 0, s: { risk: 2, verification: 2 },
      text: { en: "Run it read-only on a replica, check the row count and plan against your expectation, and reconcile the result against a number you already know.",
              ru: "Выполнить только на чтение на реплике, сверить план и число строк с ожиданием и сверить результат с уже известной цифрой." },
      why: { en: "The reconciliation is the step people skip. A query can be syntactically perfect, run fast and still answer a subtly different question than the one you asked.",
             ru: "Именно сверку чаще всего пропускают. Запрос может быть синтаксически идеальным, быстрым — и отвечать на чуть другой вопрос, чем вы задали." } },
    { id: "b", lean: 1, s: { risk: -2, verification: -1 },
      text: { en: "Run it on production — it's a SELECT, so the worst case is a wrong number.",
              ru: "Выполнить на проде — это SELECT, худший случай просто неверная цифра." },
      why: { en: "An unbounded join on a production table is an outage, not a wrong number. And a wrong number that reaches a decision is not a mild worst case.",
             ru: "Неограниченный join по продакшен-таблице — это инцидент, а не «неверная цифра». Да и неверная цифра, доехавшая до решения, — не мягкий худший случай." } },
    { id: "c", lean: 1, s: { verification: -1 },
      text: { en: "Check the syntax carefully, and if it parses cleanly, trust the result.",
              ru: "Внимательно проверить синтаксис и, если разбирается чисто, доверять результату." },
      why: { en: "Syntax is the one thing that can't be subtly wrong — it either runs or it doesn't. The dangerous errors are in join cardinality and filter semantics, which parse perfectly.",
             ru: "Синтаксис — единственное, что не может быть «тонко неверным»: либо выполняется, либо нет. Опасные ошибки в кардинальности join и семантике фильтров, и они разбираются идеально." } },
    { id: "d", lean: -1, s: { delegation: -2, iteration: -1 },
      text: { en: "Write the query yourself — it's faster than reviewing someone else's.",
              ru: "Написать запрос самому — быстрее, чем ревьюить чужой." },
      why: { en: "True for simple queries, false for the analytical ones where the real time goes. And your own query needs exactly the same reconciliation before you trust the number.",
             ru: "Верно для простых запросов и неверно для аналитических, где и уходит время. И ваш собственный запрос требует ровно той же сверки, прежде чем доверять цифре." } },
  ] },

{ id: "S3", block: "sa", dim: "context",
  prompt: { en: "You're specifying an integration with an internal legacy system. It has no documentation and several behaviours that surprise everyone who touches it.",
            ru: "Вы описываете интеграцию с внутренней легаси-системой. Документации нет, а поведение в нескольких местах удивляет всех, кто с ней сталкивается." },
  options: [
    { id: "a", lean: 1, s: { context: -2, verification: -1 },
      text: { en: "Describe what the system is supposed to do and let AI write the integration spec.",
              ru: "Описать, что система должна делать, и дать ИИ написать спеку интеграции." },
      why: { en: "You'll get a spec for the system as designed, not as built — and the whole difficulty of this integration lives in the gap between those two.",
             ru: "Получится спека для системы, какой её задумывали, а не какой построили, — а вся сложность интеграции живёт ровно в этом зазоре." } },
    { id: "b", lean: 0, s: { context: 2, verification: 1, delegation: 1 },
      text: { en: "Capture real request and response payloads, the actual schema and the known surprises first, then have AI draft the spec around that evidence.",
              ru: "Сначала собрать реальные запросы и ответы, фактическую схему и известные сюрпризы, и уже вокруг этих фактов дать ИИ собрать спеку." },
      why: { en: "Observed behaviour is the only reliable documentation for an undocumented system. Gathering it is the expensive part — but it's also the part that makes the delegation safe.",
             ru: "Наблюдаемое поведение — единственная надёжная документация недокументированной системы. Собрать его дорого, но именно это делает делегирование безопасным." } },
    { id: "c", lean: -1, s: { delegation: -1, leverage: -1 },
      text: { en: "Write the whole spec by hand — AI can't know an undocumented system.",
              ru: "Написать всю спеку руками — ИИ не может знать недокументированную систему." },
      why: { en: "Correct premise, wrong conclusion. Once you've gathered the payloads, turning them into a structured spec is exactly the mechanical work worth handing over.",
             ru: "Посылка верна, вывод нет. Как только вы собрали пейлоады, превращение их в структурированную спеку — ровно та механика, которую стоит отдать." } },
    { id: "d", lean: 1, s: { context: -1, risk: -1 },
      text: { en: "Ask AI what surprises are typical for systems of this kind and spec around those.",
              ru: "Спросить у ИИ, какие сюрпризы типичны для таких систем, и заложиться на них." },
      why: { en: "You'll get a generic list of legacy pathologies. Useful as a checklist of what to go and look for — dangerous as a substitute for looking.",
             ru: "Получите общий список легаси-патологий. Полезно как чек-лист, что пойти проверить, — опасно как замена самой проверки." } },
  ] },

{ id: "S4", block: "sa", dim: "delegation",
  prompt: { en: "Requirements are due for a feature. Three stakeholders disagree about what the feature is for, and they haven't been in a room together.",
            ru: "Нужны требования по фиче. Трое стейкхолдеров расходятся в том, зачем она, и вместе в одной комнате не были." },
  options: [
    { id: "a", lean: 1, s: { delegation: -2, context: -1 },
      text: { en: "Feed all three positions to AI and ask it to produce a reconciled set of requirements.",
              ru: "Скормить ИИ все три позиции и попросить свести их в согласованный набор требований." },
      why: { en: "It will produce a document that papers over the disagreement with compatible-sounding language. The conflict then surfaces in QA, or in production, at ten times the cost.",
             ru: "Получится документ, который прикроет разногласие совместимо звучащими формулировками. Конфликт всплывёт на QA или в проде — вдесятеро дороже." } },
    { id: "b", lean: 0, s: { delegation: 2, context: 1 },
      text: { en: "Get them in a room and force the conflict into the open; use AI to prepare by sharpening the trade-off into two or three concrete either-ors.",
              ru: "Собрать их вместе и вывести конфликт наружу; ИИ использовать для подготовки — заострить компромисс в два-три конкретных «либо-либо»." },
      why: { en: "Elicitation is the part of analysis that cannot be delegated, because the information doesn't exist in writing yet. AI's real contribution here is making the disagreement impossible to avoid.",
             ru: "Выявление требований — та часть анализа, которую делегировать нельзя: информации ещё не существует в письменном виде. Настоящий вклад ИИ здесь — сделать разногласие неизбежным для обсуждения." } },
    { id: "c", lean: -1, s: { delegation: 0, iteration: -1 },
      text: { en: "Interview each of them again separately and write everything up yourself.",
              ru: "Переговорить с каждым отдельно ещё раз и всё выписать самому." },
      why: { en: "Sequential private interviews are how the disagreement stayed hidden in the first place. More documentation of three incompatible views doesn't resolve them.",
             ru: "Последовательные приватные интервью — именно то, как разногласие и осталось скрытым. Больше документации трёх несовместимых мнений их не примиряет." } },
    { id: "d", lean: 1, s: { delegation: -1, risk: -1 },
      text: { en: "Have AI pick the most technically sound interpretation and proceed with that.",
              ru: "Пусть ИИ выберет самую технически здравую трактовку, и работать по ней." },
      why: { en: "You've let a tool make a business decision that three accountable humans couldn't agree on, and none of them has bought into the result.",
             ru: "Вы позволили инструменту принять бизнес-решение, по которому не смогли договориться трое отвечающих людей, и ни один из них не согласился с результатом." } },
  ] },

{ id: "S5", block: "sa", dim: "verification",
  prompt: { en: "Production is throwing an error nobody recognises. You paste the stack trace in and AI gives you a confident, coherent root cause.",
            ru: "В проде ошибка, которую никто не узнаёт. Вы вставляете стек-трейс, и ИИ выдаёт уверенную, связную первопричину." },
  options: [
    { id: "a", lean: 0, s: { verification: 2, iteration: 1 },
      text: { en: "Treat it as the first hypothesis to test, and go find the evidence that confirms or kills it before changing anything.",
              ru: "Считать это первой гипотезой для проверки и найти подтверждающие или опровергающие факты, прежде чем что-то менять." },
      why: { en: "This is the single most valuable framing in debugging with AI: it generates hypotheses well and confirms them not at all. Coherence is cheap; evidence is what you need.",
             ru: "Самая ценная рамка при отладке с ИИ: гипотезы он порождает хорошо, а подтверждать не умеет вовсе. Связность стоит дёшево; нужны факты." } },
    { id: "b", lean: 1, s: { verification: -2, risk: -2 },
      text: { en: "Apply the suggested fix — production is down and the explanation makes sense.",
              ru: "Применить предложенное исправление — прод лежит, а объяснение выглядит логично." },
      why: { en: "A plausible wrong fix during an incident costs you the thing you have least of: time, plus a changed system that's now harder to diagnose.",
             ru: "Правдоподобное неверное исправление во время инцидента стоит того, чего у вас меньше всего: времени, — плюс система изменилась и диагностировать её стало труднее." } },
    { id: "c", lean: 1, s: { verification: -1 },
      text: { en: "Ask for three possible causes and pick the one it rates most likely.",
              ru: "Попросить три возможные причины и выбрать ту, которую он считает вероятнее." },
      why: { en: "Three hypotheses is better than one. Choosing between them on the model's own likelihood rating instead of on evidence throws away the improvement.",
             ru: "Три гипотезы лучше одной. Но выбирать между ними по самооценке модели, а не по фактам, — значит выбросить всё преимущество." } },
    { id: "d", lean: -1, s: { delegation: -1, iteration: -1 },
      text: { en: "Ignore it and debug from first principles — AI explanations of errors are unreliable.",
              ru: "Проигнорировать и отлаживать с нуля — ИИ-объяснения ошибок ненадёжны." },
      why: { en: "Unreliable as answers, valuable as leads — especially for an unfamiliar error where your own first hypothesis may be slower to arrive and no better founded.",
             ru: "Ненадёжны как ответы, ценны как зацепки — особенно для незнакомой ошибки, где ваша собственная первая гипотеза придёт позже и обоснована будет не лучше." } },
  ] },

{ id: "S6", block: "sa", dim: "delegation",
  prompt: { en: "Thirty test cases are needed from a list of acceptance criteria before Friday.",
            ru: "К пятнице нужно тридцать тест-кейсов по списку критериев приёмки." },
  options: [
    { id: "a", lean: 0, s: { delegation: 2, verification: 1, leverage: 1 },
      text: { en: "Generate them, then check coverage criterion by criterion and add the edge cases that come from knowing this system.",
              ru: "Сгенерировать, затем проверить покрытие по каждому критерию и добавить краевые случаи, которые знаешь только ты по этой системе." },
      why: { en: "Near-perfect fit: mechanical, high-volume, and verifiable by mapping back to the criteria. The system-specific edge cases are the part you're paid for, and generation buys you the time to think about them.",
             ru: "Почти идеальное попадание: механика, объём и проверяемость сверкой с критериями. Краевые случаи, специфичные для системы, — то, за что вам платят, и генерация освобождает время именно на них." } },
    { id: "b", lean: 1, s: { delegation: 1, verification: -2 },
      text: { en: "Generate them and hand them to QA — thirty cases is more than we'd have written anyway.",
              ru: "Сгенерировать и отдать QA — тридцать кейсов больше, чем мы бы написали сами." },
      why: { en: "Volume without coverage. Generated suites cluster on the same few behaviours and can miss a criterion entirely, which is worse than a smaller suite you know the shape of.",
             ru: "Объём без покрытия. Сгенерированные наборы кучкуются вокруг нескольких поведений и могут целиком пропустить критерий — это хуже, чем меньший набор, форму которого вы знаете." } },
    { id: "c", lean: -1, s: { delegation: -2, iteration: -1 },
      text: { en: "Write all thirty by hand — you'll think more carefully that way.",
              ru: "Написать все тридцать руками — так продумаешь внимательнее." },
      why: { en: "By case twenty you are not thinking carefully, you are typing. Careful thought is a limited budget; spend it on the edge cases, not on the obvious ones.",
             ru: "К двадцатому кейсу вы уже не думаете внимательно, а печатаете. Внимание — ограниченный бюджет; тратьте его на краевые случаи, а не на очевидные." } },
    { id: "d", lean: 1, s: { delegation: 0, verification: -1 },
      text: { en: "Generate them and ask AI to confirm they fully cover the criteria.",
              ru: "Сгенерировать и попросить ИИ подтвердить, что они полностью покрывают критерии." },
      why: { en: "Asking the author to mark its own coverage. Mapping cases to criteria is a two-column table you can check in five minutes — do it yourself.",
             ru: "Вы просите автора самому оценить своё покрытие. Сопоставление кейсов и критериев — таблица в две колонки, проверяемая за пять минут; сделайте это сами." } },
  ] },

{ id: "S7", block: "sa", dim: "context",
  prompt: { en: "AI proposes a data model for a new domain. It is clean, well normalised and textbook-correct.",
            ru: "ИИ предлагает модель данных для новой предметной области. Чистая, хорошо нормализованная, как в учебнике." },
  options: [
    { id: "a", lean: 0, s: { context: 2, verification: 1 },
      text: { en: "Test it against the queries and write patterns you actually have, plus the volumes you expect.",
              ru: "Проверить её на реальных запросах и паттернах записи, а также на ожидаемых объёмах." },
      why: { en: "Textbook-correct means optimised for an abstract notion of tidiness, not for your access patterns. A model is only right relative to what will be asked of it.",
             ru: "«Как в учебнике» значит оптимизировано под абстрактную аккуратность, а не под ваши паттерны доступа. Модель верна только относительно того, что у неё будут спрашивать." } },
    { id: "b", lean: 1, s: { context: -1, verification: -1 },
      text: { en: "Adopt it — normalisation is best practice and it's cleaner than what we'd have designed.",
              ru: "Принять — нормализация это лучшая практика, и это чище того, что спроектировали бы мы." },
      why: { en: "Best practice absent context is how you get a beautiful schema that needs six joins for your most frequent read. Cleanliness is not the objective function.",
             ru: "Лучшая практика без контекста — путь к красивой схеме, где самое частое чтение требует шести join. Чистота — не та функция, которую вы оптимизируете." } },
    { id: "c", lean: -1, s: { delegation: -1 },
      text: { en: "Design it yourself — data models are too consequential to delegate.",
              ru: "Спроектировать самому — модели данных слишком значимы, чтобы их делегировать." },
      why: { en: "Consequential means it deserves review, not that a first draft can't be generated. A proposal to argue with often beats a blank page, if you argue with it properly.",
             ru: "Значимость требует ревью, а не запрета на черновик. Предложение, с которым можно спорить, часто лучше пустого листа — если спорить всерьёз." } },
    { id: "d", lean: 1, s: { context: -1, iteration: -1 },
      text: { en: "Ask AI to also generate the migration and the indexes, then review it all at once.",
              ru: "Попросить ИИ заодно сгенерировать миграцию и индексы и отревьюить всё разом." },
      why: { en: "You've multiplied the output of an unvalidated foundation. Indexes derived from the wrong model encode the wrong assumptions more deeply and cost more to undo.",
             ru: "Вы размножили результат на непроверенном фундаменте. Индексы, выведенные из неверной модели, закрепляют неверные допущения глубже, и откатывать их дороже." } },
  ] },

{ id: "S8", block: "sa", dim: "leverage",
  prompt: { en: "Every spec you write needs the same sections: error handling, non-functional requirements, rollback, observability. You keep forgetting one of them.",
            ru: "В каждой вашей спеке нужны одни и те же разделы: обработка ошибок, нефункциональные требования, откат, наблюдаемость. Один вы стабильно забываете." },
  options: [
    { id: "a", lean: 0, s: { leverage: 2, verification: 1 },
      text: { en: "Build a checked template and use AI to fill it — and to flag which sections are still empty or hand-waved.",
              ru: "Сделать выверенный шаблон и заполнять его через ИИ — плюс отмечать, какие разделы пусты или заполнены общими словами." },
      why: { en: "Checklists beat memory, and the flagging step turns a passive template into something that actively catches the omission you keep making. This is leverage on a personal failure mode.",
             ru: "Чек-лист надёжнее памяти, а шаг с отметками превращает пассивный шаблон в механизм, активно ловящий именно ваш повторяющийся пропуск. Это рычаг на личном провале." } },
    { id: "b", lean: 1, s: { leverage: 1, verification: -2 },
      text: { en: "Have AI write all four sections from the feature description each time.",
              ru: "Каждый раз просить ИИ написать все четыре раздела по описанию фичи." },
      why: { en: "Generated non-functional requirements are the emptiest text in software — 'the system should be highly available' satisfies the template and specifies nothing.",
             ru: "Сгенерированные нефункциональные требования — самый пустой текст в разработке: «система должна быть высокодоступной» закрывает шаблон и не определяет ничего." } },
    { id: "c", lean: -1, s: { leverage: -1 },
      text: { en: "Keep a paper checklist and fill everything in manually.",
              ru: "Держать бумажный чек-лист и всё заполнять вручную." },
      why: { en: "The checklist half is right and solves the actual problem. You're just leaving the drafting saving on the table.",
             ru: "Половина с чек-листом верна и решает реальную проблему. Вы просто отказываетесь от экономии на черновике." } },
    { id: "d", lean: 1, s: { leverage: 0, risk: -1 },
      text: { en: "Drop the sections you keep forgetting — if they're always forgotten, they're not load-bearing.",
              ru: "Убрать разделы, которые вы забываете: раз про них всегда забывают, значит они не несущие." },
      why: { en: "Rollback and observability are exactly the sections whose absence costs nothing until the night it costs everything. Forgotten is not the same as unnecessary.",
             ru: "Откат и наблюдаемость — ровно те разделы, отсутствие которых ничего не стоит до той ночи, когда стоит всего. «Забывают» не равно «не нужно»." } },
  ] },

/* ======================= PROJECT MANAGER ======================= */

{ id: "J1", block: "pjm", dim: "verification",
  prompt: { en: "AI produces a full project plan from your scope description — tasks, sequence, dependencies and durations.",
            ru: "ИИ выдаёт полный план проекта по вашему описанию скоупа — задачи, последовательность, зависимости и длительности." },
  options: [
    { id: "a", lean: 1, s: { verification: -2, risk: -1 },
      text: { en: "Baseline it and share with the sponsor — it's more thorough than what you'd have built.",
              ru: "Зафиксировать как базовый план и показать спонсору — он подробнее того, что вы бы собрали." },
      why: { en: "You've just committed your team to durations invented by a system that has never met them. The thoroughness is real and makes the fabricated numbers more convincing, not less.",
             ru: "Вы только что обязали команду сроками, которые выдумала система, никогда её не видевшая. Подробность реальна и делает выдуманные цифры убедительнее, а не наоборот." } },
    { id: "b", lean: 0, s: { verification: 2, delegation: 1, context: 1 },
      text: { en: "Keep the task breakdown and the dependency graph as a starting point; replace every duration with an estimate from the people doing the work.",
              ru: "Разбиение задач и граф зависимостей оставить как отправную точку; каждую длительность заменить оценкой тех, кто будет это делать." },
      why: { en: "The clean split. Structure and dependencies are recombination, which models do well and are cheap for you to check. Durations are a property of specific people in a specific context — there is no way to generate them.",
             ru: "Чистое разделение. Структура и зависимости — это рекомбинация, модели с ней справляются, а вам проверить дёшево. Длительности — свойство конкретных людей в конкретном контексте, сгенерировать их нельзя никак." } },
    { id: "c", lean: -1, s: { delegation: -2 },
      text: { en: "Discard it and build the plan in the usual workshop with the team.",
              ru: "Отбросить и собрать план на обычном воркшопе с командой." },
      why: { en: "The workshop is right and irreplaceable. But walking in with a draft breakdown to attack is faster and produces better coverage than starting from an empty board.",
             ru: "Воркшоп верен и незаменим. Но прийти с черновым разбиением, которое можно рвать, быстрее и даёт лучшее покрытие, чем старт с пустой доски." } },
    { id: "d", lean: 1, s: { verification: -1, iteration: -1 },
      text: { en: "Ask AI to add buffers to the durations to make them safe.",
              ru: "Попросить ИИ добавить буферы к длительностям, чтобы сроки стали безопасными." },
      why: { en: "Padding an invented number gives you a larger invented number. Buffer sizing only means something when it's calibrated against how this team has actually estimated before.",
             ru: "Добавить запас к выдуманному числу — получить большее выдуманное число. Размер буфера осмыслен только когда откалиброван по тому, как эта команда оценивала раньше." } },
  ] },

{ id: "J2", block: "pjm", dim: "leverage",
  prompt: { en: "The weekly status report is assembled by hand from Jira, three Slack threads and two spreadsheets. It takes you most of Thursday.",
            ru: "Еженедельный статус собирается руками из Jira, трёх тредов в Slack и двух таблиц. Уходит почти весь четверг." },
  options: [
    { id: "a", lean: 0, s: { leverage: 2, verification: 1, delegation: 1 },
      text: { en: "Automate the collection and the first draft; keep a human pass over the risks and the 'what this means' paragraph.",
              ru: "Автоматизировать сбор и первый черновик; человеческий проход оставить на рисках и абзаце «что это значит»." },
      why: { en: "Data assembly is the part that costs a day and carries no judgement. The interpretation paragraph is the only part anyone actually reads for a decision — and the only part that can be wrong in an expensive way.",
             ru: "Сбор данных — та часть, что стоит дня и не содержит суждения. Абзац с интерпретацией — единственное, что читают ради решения, и единственное, что может ошибиться дорого." } },
    { id: "b", lean: 1, s: { leverage: 1, verification: -2 },
      text: { en: "Automate the whole thing including the commentary, and have it post itself.",
              ru: "Автоматизировать целиком вместе с комментарием и публиковать автоматически." },
      why: { en: "Generated commentary regresses to reassuring neutrality, which is the opposite of what a status report is for. A report that never says 'this is going wrong' trains people to stop reading it.",
             ru: "Сгенерированный комментарий скатывается к успокаивающей нейтральности — ровно противоположному смыслу статуса. Отчёт, который никогда не говорит «здесь плохо», приучает его не читать." } },
    { id: "c", lean: -1, s: { leverage: -2 },
      text: { en: "Keep doing it by hand — assembling it is how you actually learn the project's state.",
              ru: "Продолжать руками — именно в сборке вы и узнаёте реальное состояние проекта." },
      why: { en: "A real argument, and the reason not to fully automate. But you can read an assembled draft closely in twenty minutes and get the same understanding, with the rest of Thursday back.",
             ru: "Аргумент настоящий, и именно поэтому нельзя автоматизировать целиком. Но внимательно прочитать собранный черновик — двадцать минут и то же понимание, а четверг возвращается." } },
    { id: "d", lean: 1, s: { leverage: 0, risk: -1 },
      text: { en: "Have AI summarise the Slack threads including the private channels for completeness.",
              ru: "Попросить ИИ свести треды в Slack, включая закрытые каналы, для полноты." },
      why: { en: "Completeness at the cost of moving content out of the context people chose for it. Private-channel candour ends the moment it starts appearing in reports.",
             ru: "Полнота ценой выноса содержимого из того контекста, который люди для него выбрали. Откровенность закрытых каналов заканчивается в тот момент, когда попадает в отчёты." } },
  ] },

{ id: "J3", block: "pjm", dim: "context",
  prompt: { en: "You ask AI for a risk register. It returns twenty well-formed risks: scope creep, key-person dependency, integration delays, unclear requirements.",
            ru: "Вы просите у ИИ реестр рисков. Возвращается двадцать аккуратных рисков: расползание скоупа, зависимость от ключевого человека, задержки интеграции, неясные требования." },
  options: [
    { id: "a", lean: 1, s: { context: -2, verification: -1 },
      text: { en: "Adopt the register — it's more complete than the one you'd have written under time pressure.",
              ru: "Принять реестр — он полнее того, что вы бы написали в спешке." },
      why: { en: "Complete and generic. Every project has these twenty; none of them is why yours will fail. A register of universal risks creates the paperwork of risk management without any of its value.",
             ru: "Полный и общий. Эти двадцать есть у любого проекта; ни один из них не станет причиной провала именно вашего. Реестр универсальных рисков создаёт бумажную работу управления рисками без его пользы." } },
    { id: "b", lean: 0, s: { context: 2, delegation: 1 },
      text: { en: "Use it as a prompt for the team: which of these is actually live for us, and what are the three risks specific to this project that aren't on the list?",
              ru: "Использовать как затравку для команды: какие из этих реально живые у нас и какие три специфичных именно для этого проекта риска в список не попали?" },
      why: { en: "The generic list earns its place as a warm-up that gets people talking. The value is entirely in question two, and only the team can answer it.",
             ru: "Общий список оправдан как разогрев, который заставляет людей заговорить. Вся ценность во втором вопросе, и ответить на него может только команда." } },
    { id: "c", lean: -1, s: { context: 0, iteration: -1 },
      text: { en: "Ignore it and run the risk workshop from a blank page as usual.",
              ru: "Проигнорировать и провести воркшоп по рискам с чистого листа как обычно." },
      why: { en: "Defensible, but a blank page in a risk workshop produces silence for the first ten minutes. A list to react to is a cheap way to buy those minutes back.",
             ru: "Позиция разумная, но чистый лист на воркшопе по рискам даёт десять минут молчания. Список, на который можно реагировать, — дешёвый способ вернуть эти минуты." } },
    { id: "d", lean: 1, s: { context: -1, verification: -1 },
      text: { en: "Ask AI to also score each risk's probability and impact.",
              ru: "Попросить ИИ заодно оценить вероятность и влияние каждого риска." },
      why: { en: "Now the generic risks have invented numbers attached, which will be summed into a heat map and presented as analysis. Precision applied to fiction reads as rigour.",
             ru: "Теперь у общих рисков появились выдуманные числа, которые сложатся в тепловую карту и будут поданы как анализ. Точность, применённая к выдумке, читается как строгость." } },
  ] },

{ id: "J4", block: "pjm", dim: "delegation",
  prompt: { en: "A senior engineer has been quietly missing commitments for three weeks. You need to address it.",
            ru: "Сильный инженер три недели тихо срывает обязательства. Нужно с этим разобраться." },
  options: [
    { id: "a", lean: 0, s: { delegation: 2, risk: 1 },
      text: { en: "Have the conversation yourself, starting from questions rather than conclusions; prepare by listing what you actually know versus what you're assuming.",
              ru: "Поговорить лично, начав с вопросов, а не с выводов; подготовиться, выписав, что вы реально знаете, а что домысливаете." },
      why: { en: "Three weeks of quiet slipping from someone senior usually means something you don't know yet — burnout, a blocker they're embarrassed by, something outside work. The preparation is delegable; the conversation is not.",
             ru: "Три недели тихих срывов у сильного человека обычно означают то, чего вы ещё не знаете: выгорание, блокер, за который стыдно, что-то вне работы. Подготовку делегировать можно, разговор — нет." } },
    { id: "b", lean: 1, s: { delegation: -2, risk: -2 },
      text: { en: "Ask AI to analyse their Jira history and tell you what's going wrong.",
              ru: "Попросить ИИ разобрать его историю в Jira и сказать, что идёт не так." },
      why: { en: "Ticket data cannot see the cause, only the symptom — and building a case about a named individual from surveillance-shaped analysis poisons the conversation before it starts.",
             ru: "Данные тикетов видят симптом, а не причину, — а собирать досье на конкретного человека через анализ в логике слежки отравляет разговор ещё до его начала." } },
    { id: "c", lean: 1, s: { delegation: -1, risk: -1 },
      text: { en: "Have AI draft the performance conversation script and follow it.",
              ru: "Попросить ИИ написать сценарий разговора о результативности и идти по нему." },
      why: { en: "A script makes you a worse listener, and listening is the entire job here. You'll be waiting for your next line instead of hearing the reason.",
             ru: "Сценарий делает вас худшим слушателем, а слушать здесь и есть вся работа. Вы будете ждать свою следующую реплику вместо того, чтобы услышать причину." } },
    { id: "d", lean: -1, s: { delegation: -1, iteration: -1 },
      text: { en: "Wait another sprint — it may resolve itself and you don't want to misjudge it.",
              ru: "Подождать ещё спринт — может, рассосётся, а ошибиться в оценке не хочется." },
      why: { en: "Not an AI question at all, which is the point: the efficiency loss here is delay, not tooling. Three weeks is already long enough that the cost is compounding.",
             ru: "Это вообще не вопрос про ИИ, и в этом суть: потеря эффективности здесь в промедлении, а не в инструментах. Три недели — уже достаточно, чтобы издержки начали накапливаться." } },
  ] },

{ id: "J5", block: "pjm", dim: "verification",
  prompt: { en: "AI summarises a two-hour planning call into decisions and action items with owners and dates.",
            ru: "ИИ сводит двухчасовую планёрку в решения и задачи с владельцами и сроками." },
  options: [
    { id: "a", lean: 0, s: { verification: 2, leverage: 1 },
      text: { en: "Check the owners and dates against what was actually agreed, then send it to the room to correct before it becomes the record.",
              ru: "Сверить владельцев и сроки с тем, о чём реально договорились, и отправить участникам на правку, прежде чем это станет протоколом." },
      why: { en: "Transcription and structuring are an excellent fit. Attribution is where it fails: models routinely assign an action to whoever spoke last about it rather than whoever accepted it.",
             ru: "Расшифровка и структурирование — отличное попадание. Ломается атрибуция: модели регулярно приписывают задачу тому, кто говорил о ней последним, а не тому, кто её взял." } },
    { id: "b", lean: 1, s: { verification: -2, risk: -1 },
      text: { en: "Post it straight to the channel as the minutes — it's more accurate than anyone's memory.",
              ru: "Сразу опубликовать в канал как протокол — это точнее, чем чья-либо память." },
      why: { en: "More complete than memory, not more accurate about commitment. A wrongly assigned owner in a published record is rarely corrected and quietly becomes the truth.",
             ru: "Полнее памяти, но не точнее в части обязательств. Неверно назначенный владелец в опубликованном протоколе редко исправляется и тихо становится истиной." } },
    { id: "c", lean: -1, s: { delegation: -2 },
      text: { en: "Write the minutes yourself from your own notes.",
              ru: "Написать протокол самому по собственным заметкам." },
      why: { en: "Your notes are a lossy summary made while you were also facilitating. This is one of the clearest wins available in the role.",
             ru: "Ваши заметки — потерянное резюме, сделанное параллельно с ведением встречи. Это один из самых очевидных выигрышей в этой роли." } },
    { id: "d", lean: 1, s: { verification: -1, risk: -1 },
      text: { en: "Record every call by default and generate minutes automatically without telling participants.",
              ru: "По умолчанию записывать все звонки и генерировать протоколы автоматически, не сообщая участникам." },
      why: { en: "Undisclosed recording is a consent and, in many places, a legal problem — and people who suspect it stop saying the useful things.",
             ru: "Запись без уведомления — вопрос согласия, а во многих юрисдикциях и закона; к тому же люди, подозревающие запись, перестают говорить полезное." } },
  ] },

{ id: "J6", block: "pjm", dim: "context",
  prompt: { en: "Four teams have interlocking dependencies. You ask AI to map them and find the critical path.",
            ru: "У четырёх команд переплетённые зависимости. Вы просите ИИ построить карту и найти критический путь." },
  options: [
    { id: "a", lean: 0, s: { context: 2, verification: 1 },
      text: { en: "Have each team state its own dependencies first, then use AI to reconcile the four lists and surface the contradictions between them.",
              ru: "Сначала пусть каждая команда сама назовёт свои зависимости, затем через ИИ свести четыре списка и вскрыть противоречия между ними." },
      why: { en: "The contradictions are the deliverable. Team A believing B owes them something B has never heard of is the dependency that breaks the plan, and reconciling lists is exactly mechanical enough to delegate.",
             ru: "Противоречия и есть результат. Команда A, уверенная, что B ей что-то должна, о чём B не слышала, — та самая зависимость, что ломает план; а сведение списков достаточно механично, чтобы его отдать." } },
    { id: "b", lean: 1, s: { context: -2 },
      text: { en: "Describe the four workstreams and let AI infer the dependency graph.",
              ru: "Описать четыре потока работ и дать ИИ вывести граф зависимостей." },
      why: { en: "It will infer the dependencies that logically ought to exist. Real ones come from a shared library nobody documented and a person on holiday in week six.",
             ru: "Он выведет зависимости, которые логически должны быть. Настоящие берутся из общей библиотеки, которую никто не задокументировал, и человека, ушедшего в отпуск на шестой неделе." } },
    { id: "c", lean: -1, s: { context: 0, iteration: -1 },
      text: { en: "Map it by hand in a workshop — cross-team dependencies are too political for a tool.",
              ru: "Построить карту руками на воркшопе — межкомандные зависимости слишком политичны для инструмента." },
      why: { en: "The workshop is right; refusing the reconciliation step means you'll spend it arguing about whose list is correct rather than about the contradictions themselves.",
             ru: "Воркшоп верен; но отказ от сведения списков означает, что на нём будут спорить, чей список правильный, а не о самих противоречиях." } },
    { id: "d", lean: 1, s: { context: -1, verification: -1 },
      text: { en: "Accept the AI's critical path and manage the project to it.",
              ru: "Принять критический путь от ИИ и вести проект по нему." },
      why: { en: "A critical path is only as good as the durations and dependencies under it, both of which the model guessed. Managing to a fictional path means optimising the wrong things.",
             ru: "Критический путь не лучше лежащих под ним длительностей и зависимостей, а их модель угадала. Вести проект по вымышленному пути — оптимизировать не то." } },
  ] },

{ id: "J7", block: "pjm", dim: "risk",
  prompt: { en: "You must escalate a slipping date to a sponsor who reacts badly to bad news. You want the message to land without triggering a blow-up.",
            ru: "Нужно эскалировать сдвиг срока спонсору, который плохо реагирует на плохие новости. Хочется донести, не спровоцировав взрыв." },
  options: [
    { id: "a", lean: 0, s: { risk: 2, delegation: 1, context: 1 },
      text: { en: "Decide the facts and the ask yourself, use AI to stress-test the framing and predict objections, then send it in your own voice.",
              ru: "Факты и запрос определить самому, через ИИ проверить подачу и спрогнозировать возражения, отправить своим голосом." },
      why: { en: "Objection prediction is genuinely useful and costs two minutes. What can't be delegated is the judgement about how much to soften — soften too far and the sponsor doesn't realise they need to act.",
             ru: "Прогноз возражений реально полезен и стоит двух минут. Делегировать нельзя решение, насколько смягчать: пересмягчите — и спонсор не поймёт, что нужно действовать." } },
    { id: "b", lean: 1, s: { risk: -2, verification: -1 },
      text: { en: "Have AI write the whole escalation diplomatically and send it.",
              ru: "Попросить ИИ написать всю эскалацию дипломатично и отправить." },
      why: { en: "Default diplomatic register buries the severity. The sponsor reads a calm note, takes no action, and the blow-up simply moves to the day the date is actually missed.",
             ru: "Дипломатичный регистр по умолчанию прячет серьёзность. Спонсор прочитает спокойную записку, ничего не сделает, а взрыв просто переедет на день, когда срок реально сорвётся." } },
    { id: "c", lean: 1, s: { risk: -2 },
      text: { en: "Ask AI how to phrase it so the delay sounds less severe than it is.",
              ru: "Спросить у ИИ, как сформулировать, чтобы задержка звучала мягче, чем она есть." },
      why: { en: "You've asked for help misleading your sponsor. Beyond the ethics, it destroys the only asset that makes future escalations work — your reports being believed.",
             ru: "Вы попросили помочь ввести спонсора в заблуждение. Помимо этики, это уничтожает единственный актив, на котором держатся будущие эскалации, — доверие к вашим словам." } },
    { id: "d", lean: -1, s: { risk: 0, iteration: -1 },
      text: { en: "Skip the writing and raise it verbally — text always goes wrong with this person.",
              ru: "Не писать, а поднять устно — с этим человеком текст всегда выходит боком." },
      why: { en: "Reasonable for the conversation, but a slipping date needs a written record of what was known when. Do both: verbal first, written confirmation after.",
             ru: "Для разговора разумно, но сдвиг срока требует письменного следа: что и когда было известно. Делайте оба: сначала устно, потом письменное подтверждение." } },
  ] },

{ id: "J8", block: "pjm", dim: "iteration",
  prompt: { en: "You're preparing a retrospective for a team that has had a rough quarter. AI offers to generate the agenda, the prompts and a synthesis of the last three retros.",
            ru: "Вы готовите ретро для команды после тяжёлого квартала. ИИ предлагает сгенерировать повестку, вопросы и сводку трёх прошлых ретро." },
  options: [
    { id: "a", lean: 0, s: { iteration: 2, delegation: 1, leverage: 1 },
      text: { en: "Take the synthesis of past retros — that's real work — and design the room yourself, because the issue this quarter is whether people will say anything at all.",
              ru: "Взять сводку прошлых ретро — это настоящая работа — а саму встречу спроектировать самому: вопрос этого квартала в том, заговорит ли команда вообще." },
      why: { en: "Correct split under time pressure. The synthesis is the part that's laborious and checkable; psychological safety in a bad quarter depends on choices only someone in the room can make.",
             ru: "Верное разделение в условиях нехватки времени. Сводка — трудоёмкая и проверяемая часть; психологическая безопасность после тяжёлого квартала зависит от решений, которые примет только человек в комнате." } },
    { id: "b", lean: 1, s: { iteration: -1, delegation: -2 },
      text: { en: "Take all three — agenda, prompts and synthesis — you're short on time and it's a standard format.",
              ru: "Взять все три — повестку, вопросы и сводку: времени мало, а формат стандартный." },
      why: { en: "A standard format is exactly wrong after a rough quarter. Generic prompts signal that this is a process being completed, which is the fastest way to get a silent room.",
             ru: "Стандартный формат — ровно то, что не нужно после тяжёлого квартала. Общие вопросы сигналят «мы закрываем процесс», а это кратчайший путь к молчащей комнате." } },
    { id: "c", lean: -1, s: { iteration: -1, leverage: -2 },
      text: { en: "Decline all of it and prepare from scratch — retros are a human ritual.",
              ru: "Отказаться от всего и готовиться с нуля — ретро это человеческий ритуал." },
      why: { en: "The ritual argument covers the facilitation, not the reading of three past documents. That part is where the pattern nobody has noticed is hiding.",
             ru: "Аргумент про ритуал покрывает ведение встречи, но не чтение трёх прошлых документов. Именно там и прячется закономерность, которую никто не заметил." } },
    { id: "d", lean: 1, s: { risk: -2, delegation: -1 },
      text: { en: "Feed in the team's chat history so the synthesis reflects what people really felt.",
              ru: "Подать историю переписок команды, чтобы сводка отражала, что люди чувствовали на самом деле." },
      why: { en: "Mining private conversations to prepare a session about psychological safety is self-defeating, and it will be found out.",
             ru: "Перерывать личные переписки ради подготовки встречи о психологической безопасности — саморазрушительно, и об этом узнают." } },
  ] },

];
