/* ============================================================
   MMAT — question bank (10 independent forms)

   All items are ORIGINAL, written in the spirit of the McQuaig
   Mental Agility Test: short verbal / numerical / logical
   problems of increasing difficulty. Not the real instrument.

   Schema (consumed by app.js):
     cat     : "verbal" | "numerical" | "logical"
     topic   : human label for the sub-type
     prompt  : question text (may contain inline HTML)
     options : array of 3–5 answer strings
     answer  : index of the correct option
     explain : one-line worked answer shown in review
   ============================================================ */
window.MMAT = {
  config: { durationSec: 900 }, // 15 minutes per form

  categories: {
    verbal:    { label: "Verbal",    color: "#5aa9e6" },
    numerical: { label: "Numerical", color: "#46c98b" },
    logical:   { label: "Logical",   color: "#d9b25a" },
  },

  tests: [
    /* ===================== TEST 1 ===================== */
    {
      id: "form-1", name: "Test 1", blurb: "A balanced warm-up across vocabulary, number patterns and everyday reasoning.",
      questions: [
        { cat: "verbal", topic: "Synonym", prompt: "Choose the word closest in meaning to <span class='mono'>ABUNDANT</span>.", options: ["Plentiful", "Scarce", "Fragile", "Hidden"], answer: 0, explain: "Abundant means present in large quantities — plentiful." },
        { cat: "verbal", topic: "Synonym", prompt: "Choose the word closest in meaning to <span class='mono'>RELUCTANT</span>.", options: ["Eager", "Unwilling", "Hostile", "Curious"], answer: 1, explain: "Reluctant means hesitant or unwilling to act." },
        { cat: "verbal", topic: "Synonym", prompt: "Choose the word closest in meaning to <span class='mono'>CANDID</span>.", options: ["Secretive", "Frank", "Nervous", "Clumsy"], answer: 1, explain: "Candid means open and frank." },
        { cat: "verbal", topic: "Antonym", prompt: "Choose the OPPOSITE of <span class='mono'>EXPAND</span>.", options: ["Stretch", "Inflate", "Contract", "Widen"], answer: 2, explain: "To expand is to grow larger; its opposite is to contract." },
        { cat: "verbal", topic: "Antonym", prompt: "Choose the OPPOSITE of <span class='mono'>GENEROUS</span>.", options: ["Kind", "Stingy", "Wealthy", "Cheerful"], answer: 1, explain: "A generous person gives freely; a stingy one does not." },
        { cat: "verbal", topic: "Analogy", prompt: "Hand is to Glove as Foot is to ___", options: ["Sock", "Toe", "Leg", "Floor"], answer: 0, explain: "A glove covers the hand as a sock covers the foot." },
        { cat: "verbal", topic: "Analogy", prompt: "Kitten is to Cat as Puppy is to ___", options: ["Dog", "Cub", "Foal", "Calf"], answer: 0, explain: "A kitten is a young cat; a puppy is a young dog." },
        { cat: "verbal", topic: "Analogy", prompt: "Author is to Book as Composer is to ___", options: ["Symphony", "Stage", "Piano", "Audience"], answer: 0, explain: "An author creates a book as a composer creates a symphony." },
        { cat: "verbal", topic: "Analogy", prompt: "Thermometer is to Temperature as Clock is to ___", options: ["Speed", "Time", "Weight", "Distance"], answer: 1, explain: "A thermometer measures temperature; a clock measures time." },
        { cat: "verbal", topic: "Odd one out", prompt: "Which word does NOT belong with the others?", options: ["Rose", "Tulip", "Daisy", "Oak"], answer: 3, explain: "Rose, tulip and daisy are flowers; an oak is a tree." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>3, 6, 9, 12, ?</span>", options: ["13", "14", "15", "18"], answer: 2, explain: "Add 3 each time: 12 + 3 = 15." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>2, 4, 8, 16, ?</span>", options: ["24", "30", "32", "64"], answer: 2, explain: "Each term doubles: 16 × 2 = 32." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>1, 4, 9, 16, ?</span>", options: ["20", "24", "25", "36"], answer: 2, explain: "These are squares: 1², 2², 3², 4², 5² = 25." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>5, 10, 20, 40, ?</span>", options: ["60", "70", "80", "100"], answer: 2, explain: "Each term doubles: 40 × 2 = 80." },
        { cat: "numerical", topic: "Word problem", prompt: "A dozen pens cost $9. How much do 4 pens cost?", options: ["$2", "$3", "$4", "$6"], answer: 1, explain: "$9 ÷ 12 = $0.75 each; 4 × $0.75 = $3." },
        { cat: "numerical", topic: "Word problem", prompt: "A train travels 60 miles in one hour. How far does it go in 2.5 hours?", options: ["120", "135", "150", "180"], answer: 2, explain: "60 × 2.5 = 150 miles." },
        { cat: "numerical", topic: "Arithmetic", prompt: "What is 15% of 200?", options: ["15", "20", "30", "45"], answer: 2, explain: "0.15 × 200 = 30." },
        { cat: "numerical", topic: "Word problem", prompt: "A shirt marked $40 is discounted 25%. What is the sale price?", options: ["$30", "$32", "$35", "$15"], answer: 0, explain: "25% of $40 is $10; $40 − $10 = $30." },
        { cat: "numerical", topic: "Arithmetic", prompt: "What is 17 + 28 + 35?", options: ["70", "75", "80", "85"], answer: 2, explain: "17 + 28 = 45; 45 + 35 = 80." },
        { cat: "logical", topic: "Letter series", prompt: "What comes next?  <span class='mono'>A, C, E, G, ?</span>", options: ["H", "I", "J", "K"], answer: 1, explain: "Skip one letter each step: G → I." },
        { cat: "logical", topic: "Logic", prompt: "All roses are flowers. Some flowers fade quickly. Which must be true?", options: ["All roses fade quickly", "Some roses fade quickly", "All flowers are roses", "None of these necessarily follows"], answer: 3, explain: "The 'fast-fading' flowers need not include any roses, so nothing certain follows." },
        { cat: "logical", topic: "Logic", prompt: "If today is Wednesday, what day will it be in 5 days?", options: ["Sunday", "Monday", "Tuesday", "Saturday"], answer: 1, explain: "Wed → Thu, Fri, Sat, Sun, Mon (5 days) = Monday." },
        { cat: "logical", topic: "Logic", prompt: "Tom is taller than Sam. Sam is taller than Bob. Who is shortest?", options: ["Tom", "Sam", "Bob", "Cannot tell"], answer: 2, explain: "Order is Tom > Sam > Bob, so Bob is shortest." },
        { cat: "logical", topic: "Logic", prompt: "In a row, the cat sits left of the dog, and the dog sits left of the fox. Which animal is in the middle?", options: ["Cat", "Dog", "Fox", "Cannot tell"], answer: 1, explain: "Order left→right is cat, dog, fox; the dog is in the middle." },
        { cat: "logical", topic: "Classification", prompt: "Which number does NOT belong?", options: ["9", "16", "24", "25"], answer: 2, explain: "9, 16 and 25 are perfect squares; 24 is not." },
      ],
    },

    /* ===================== TEST 2 ===================== */
    {
      id: "form-2", name: "Test 2", blurb: "More analogies and multi-step number patterns with a logic finish.",
      questions: [
        { cat: "verbal", topic: "Synonym", prompt: "Choose the word closest in meaning to <span class='mono'>FRAGILE</span>.", options: ["Sturdy", "Delicate", "Heavy", "Smooth"], answer: 1, explain: "Fragile means easily broken — delicate." },
        { cat: "verbal", topic: "Synonym", prompt: "Choose the word closest in meaning to <span class='mono'>HASTY</span>.", options: ["Careful", "Hurried", "Lazy", "Quiet"], answer: 1, explain: "Hasty means done in a hurry." },
        { cat: "verbal", topic: "Synonym", prompt: "Choose the word closest in meaning to <span class='mono'>VACANT</span>.", options: ["Busy", "Empty", "Locked", "Bright"], answer: 1, explain: "Vacant means unoccupied or empty." },
        { cat: "verbal", topic: "Antonym", prompt: "Choose the OPPOSITE of <span class='mono'>ANCIENT</span>.", options: ["Old", "Modern", "Historic", "Ruined"], answer: 1, explain: "Ancient means very old; modern is its opposite." },
        { cat: "verbal", topic: "Antonym", prompt: "Choose the OPPOSITE of <span class='mono'>TRANSPARENT</span>.", options: ["Clear", "Opaque", "Fragile", "Visible"], answer: 1, explain: "Transparent lets light through; opaque blocks it." },
        { cat: "verbal", topic: "Analogy", prompt: "Bird is to Nest as Bee is to ___", options: ["Hive", "Honey", "Flower", "Web"], answer: 0, explain: "A bird lives in a nest as a bee lives in a hive." },
        { cat: "verbal", topic: "Analogy", prompt: "Pen is to Write as Knife is to ___", options: ["Cut", "Sharp", "Metal", "Kitchen"], answer: 0, explain: "A pen is used to write; a knife is used to cut." },
        { cat: "verbal", topic: "Analogy", prompt: "Hot is to Cold as Up is to ___", options: ["Down", "High", "Top", "Over"], answer: 0, explain: "Hot/cold and up/down are pairs of opposites." },
        { cat: "verbal", topic: "Analogy", prompt: "Doctor is to Patient as Teacher is to ___", options: ["School", "Student", "Lesson", "Book"], answer: 1, explain: "A doctor serves a patient as a teacher serves a student." },
        { cat: "verbal", topic: "Odd one out", prompt: "Which word does NOT belong with the others?", options: ["Copper", "Gold", "Iron", "Granite"], answer: 3, explain: "Copper, gold and iron are metals; granite is a rock." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>7, 14, 21, 28, ?</span>", options: ["30", "33", "35", "42"], answer: 2, explain: "Add 7 each time: 28 + 7 = 35." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>100, 90, 80, 70, ?</span>", options: ["50", "55", "60", "65"], answer: 2, explain: "Subtract 10 each time: 70 − 10 = 60." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>1, 2, 4, 7, 11, ?</span>", options: ["14", "15", "16", "18"], answer: 2, explain: "Differences grow 1, 2, 3, 4, 5: 11 + 5 = 16." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>3, 6, 12, 24, ?</span>", options: ["36", "42", "48", "60"], answer: 2, explain: "Each term doubles: 24 × 2 = 48." },
        { cat: "numerical", topic: "Arithmetic", prompt: "What is 12 × 8?", options: ["84", "96", "104", "108"], answer: 1, explain: "12 × 8 = 96." },
        { cat: "numerical", topic: "Arithmetic", prompt: "What is half of 250?", options: ["100", "120", "125", "150"], answer: 2, explain: "250 ÷ 2 = 125." },
        { cat: "numerical", topic: "Word problem", prompt: "A car uses 5 litres of fuel per 100 km. How many litres for 400 km?", options: ["15", "20", "25", "40"], answer: 1, explain: "400 km is 4 × 100 km, so 4 × 5 = 20 litres." },
        { cat: "numerical", topic: "Word problem", prompt: "If 3 apples cost $1.20, what is the cost of 1 apple?", options: ["$0.30", "$0.40", "$0.50", "$0.60"], answer: 1, explain: "$1.20 ÷ 3 = $0.40." },
        { cat: "numerical", topic: "Arithmetic", prompt: "What is 9² − 4²?", options: ["25", "49", "65", "97"], answer: 2, explain: "81 − 16 = 65." },
        { cat: "logical", topic: "Letter series", prompt: "What comes next?  <span class='mono'>B, D, F, H, ?</span>", options: ["I", "J", "K", "L"], answer: 1, explain: "Skip one letter each step: H → J." },
        { cat: "logical", topic: "Logic", prompt: "Some books are heavy. All heavy things are hard to carry. Which must be true?", options: ["Some books are hard to carry", "All books are heavy", "No books are heavy", "All heavy things are books"], answer: 0, explain: "The heavy books are hard to carry, so some books are hard to carry." },
        { cat: "logical", topic: "Logic", prompt: "If yesterday was Monday, what is the day after tomorrow?", options: ["Wednesday", "Thursday", "Friday", "Saturday"], answer: 1, explain: "Today is Tuesday; tomorrow Wednesday; the day after is Thursday." },
        { cat: "logical", topic: "Logic", prompt: "A is heavier than B. C is lighter than B. Who is heaviest?", options: ["A", "B", "C", "Cannot tell"], answer: 0, explain: "A > B and B > C, so A is heaviest." },
        { cat: "logical", topic: "Logic", prompt: "In a queue, P stands directly behind Q. Who is ahead in the line?", options: ["P", "Q", "Cannot tell", "Both equal"], answer: 1, explain: "P is behind Q, so Q is ahead." },
        { cat: "logical", topic: "Classification", prompt: "Which number does NOT belong?", options: ["12", "18", "20", "24"], answer: 2, explain: "12, 18 and 24 are divisible by 6; 20 is not." },
      ],
    },

    /* ===================== TEST 3 ===================== */
    {
      id: "form-3", name: "Test 3", blurb: "Squares, Fibonacci and syllogisms — pattern spotting at a quicker pace.",
      questions: [
        { cat: "verbal", topic: "Synonym", prompt: "Choose the word closest in meaning to <span class='mono'>GENUINE</span>.", options: ["Fake", "Authentic", "Cheap", "Rough"], answer: 1, explain: "Genuine means real or authentic." },
        { cat: "verbal", topic: "Synonym", prompt: "Choose the word closest in meaning to <span class='mono'>PERPLEX</span>.", options: ["Clarify", "Confuse", "Amuse", "Annoy"], answer: 1, explain: "To perplex is to confuse or puzzle." },
        { cat: "verbal", topic: "Synonym", prompt: "Choose the word closest in meaning to <span class='mono'>BRIEF</span>.", options: ["Long", "Short", "Loud", "Heavy"], answer: 1, explain: "Brief means short in duration or length." },
        { cat: "verbal", topic: "Antonym", prompt: "Choose the OPPOSITE of <span class='mono'>VICTORY</span>.", options: ["Triumph", "Defeat", "Battle", "Glory"], answer: 1, explain: "Victory is winning; defeat is losing." },
        { cat: "verbal", topic: "Antonym", prompt: "Choose the OPPOSITE of <span class='mono'>INCREASE</span>.", options: ["Expand", "Decrease", "Multiply", "Rise"], answer: 1, explain: "Increase means to grow; decrease means to shrink." },
        { cat: "verbal", topic: "Analogy", prompt: "Fish is to Water as Bird is to ___", options: ["Nest", "Air", "Feather", "Tree"], answer: 1, explain: "A fish lives in water as a bird lives in (the) air." },
        { cat: "verbal", topic: "Analogy", prompt: "Painter is to Brush as Writer is to ___", options: ["Pen", "Paper", "Word", "Story"], answer: 0, explain: "A painter works with a brush; a writer works with a pen." },
        { cat: "verbal", topic: "Analogy", prompt: "Day is to Night as Summer is to ___", options: ["Spring", "Winter", "Season", "Warm"], answer: 1, explain: "Day/night and summer/winter are opposite pairs." },
        { cat: "verbal", topic: "Analogy", prompt: "Wheel is to Car as Wing is to ___", options: ["Sky", "Airplane", "Feather", "Flight"], answer: 1, explain: "A wheel is part of a car; a wing is part of an airplane." },
        { cat: "verbal", topic: "Odd one out", prompt: "Which word does NOT belong with the others?", options: ["Triangle", "Square", "Circle", "Cube"], answer: 3, explain: "Triangle, square and circle are flat (2-D) shapes; a cube is a solid." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>2, 5, 8, 11, ?</span>", options: ["12", "13", "14", "15"], answer: 2, explain: "Add 3 each time: 11 + 3 = 14." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>81, 27, 9, 3, ?</span>", options: ["0", "1", "2", "3"], answer: 1, explain: "Divide by 3 each time: 3 ÷ 3 = 1." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>1, 1, 2, 3, 5, 8, ?</span>", options: ["11", "12", "13", "21"], answer: 2, explain: "Fibonacci: each term is the sum of the two before it, 5 + 8 = 13." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>4, 9, 16, 25, ?</span>", options: ["30", "32", "36", "49"], answer: 2, explain: "Squares 2², 3², 4², 5², 6² = 36." },
        { cat: "numerical", topic: "Arithmetic", prompt: "What is 144 ÷ 12?", options: ["11", "12", "14", "16"], answer: 1, explain: "144 ÷ 12 = 12." },
        { cat: "numerical", topic: "Arithmetic", prompt: "What is 25% of 80?", options: ["15", "20", "25", "40"], answer: 1, explain: "A quarter of 80 is 20." },
        { cat: "numerical", topic: "Word problem", prompt: "A rectangle measures 6 cm by 4 cm. What is its area?", options: ["10", "20", "24", "48"], answer: 2, explain: "Area = 6 × 4 = 24 cm²." },
        { cat: "numerical", topic: "Arithmetic", prompt: "What is 1 + 2 + 3 + 4 + 5?", options: ["10", "12", "15", "20"], answer: 2, explain: "The sum is 15." },
        { cat: "numerical", topic: "Word problem", prompt: "If 8 workers each work 6 days, how many worker-days of labour is that?", options: ["14", "42", "48", "54"], answer: 2, explain: "8 × 6 = 48 worker-days." },
        { cat: "logical", topic: "Letter series", prompt: "What comes next?  <span class='mono'>Z, X, V, T, ?</span>", options: ["S", "R", "Q", "U"], answer: 1, explain: "Step back two letters each time: T → R." },
        { cat: "logical", topic: "Logic", prompt: "All cats are animals. No animals are plants. Which must be true?", options: ["No cats are plants", "Some cats are plants", "All animals are cats", "Some plants are cats"], answer: 0, explain: "Cats are animals and no animals are plants, so no cats are plants." },
        { cat: "logical", topic: "Logic", prompt: "If the 3rd of a month falls on a Friday, what day is the 10th?", options: ["Thursday", "Friday", "Saturday", "Sunday"], answer: 1, explain: "The 10th is exactly 7 days later, so the same weekday — Friday." },
        { cat: "logical", topic: "Logic", prompt: "John is older than Mary but younger than Paul. Who is oldest?", options: ["John", "Mary", "Paul", "Cannot tell"], answer: 2, explain: "Paul > John > Mary, so Paul is oldest." },
        { cat: "logical", topic: "Logic", prompt: "Four cards lie in a row, left to right: red, blue, green, yellow. Which is second from the RIGHT?", options: ["Red", "Blue", "Green", "Yellow"], answer: 2, explain: "From the right: yellow is first, green is second." },
        { cat: "logical", topic: "Classification", prompt: "Which number does NOT belong?", options: ["64", "81", "100", "120"], answer: 3, explain: "64, 81 and 100 are perfect squares; 120 is not." },
      ],
    },

    /* ===================== TEST 4 ===================== */
    {
      id: "form-4", name: "Test 4", blurb: "Fractions, percentages and spatial logic alongside the usual word work.",
      questions: [
        { cat: "verbal", topic: "Synonym", prompt: "Choose the word closest in meaning to <span class='mono'>RAPID</span>.", options: ["Slow", "Quick", "Steady", "Loud"], answer: 1, explain: "Rapid means fast or quick." },
        { cat: "verbal", topic: "Synonym", prompt: "Choose the word closest in meaning to <span class='mono'>WEARY</span>.", options: ["Alert", "Tired", "Happy", "Strong"], answer: 1, explain: "Weary means tired or fatigued." },
        { cat: "verbal", topic: "Synonym", prompt: "Choose the word closest in meaning to <span class='mono'>CONCEAL</span>.", options: ["Reveal", "Hide", "Carry", "Break"], answer: 1, explain: "To conceal is to hide." },
        { cat: "verbal", topic: "Antonym", prompt: "Choose the OPPOSITE of <span class='mono'>PERMANENT</span>.", options: ["Lasting", "Temporary", "Fixed", "Stable"], answer: 1, explain: "Permanent means lasting; temporary is its opposite." },
        { cat: "verbal", topic: "Antonym", prompt: "Choose the OPPOSITE of <span class='mono'>HUMBLE</span>.", options: ["Modest", "Arrogant", "Quiet", "Poor"], answer: 1, explain: "Humble means modest; arrogant is the opposite." },
        { cat: "verbal", topic: "Analogy", prompt: "Library is to Books as Garage is to ___", options: ["Cars", "Tools", "Walls", "Roof"], answer: 0, explain: "A library stores books as a garage stores cars." },
        { cat: "verbal", topic: "Analogy", prompt: "Smoke is to Fire as Cloud is to ___", options: ["Rain", "Sky", "Wind", "Sun"], answer: 0, explain: "Smoke signals fire as a (storm) cloud signals rain." },
        { cat: "verbal", topic: "Analogy", prompt: "Foot is to Leg as Hand is to ___", options: ["Arm", "Finger", "Wrist", "Glove"], answer: 0, explain: "A foot is at the end of a leg as a hand is at the end of an arm." },
        { cat: "verbal", topic: "Analogy", prompt: "Lion is to Pride as Wolf is to ___", options: ["Herd", "Pack", "Flock", "School"], answer: 1, explain: "A group of lions is a pride; a group of wolves is a pack." },
        { cat: "verbal", topic: "Odd one out", prompt: "Which word does NOT belong with the others?", options: ["Apple", "Banana", "Carrot", "Grape"], answer: 2, explain: "Apple, banana and grape are fruits; a carrot is a vegetable." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>6, 12, 18, 24, ?</span>", options: ["28", "30", "32", "36"], answer: 1, explain: "Add 6 each time: 24 + 6 = 30." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>1, 3, 9, 27, ?</span>", options: ["54", "72", "81", "108"], answer: 2, explain: "Multiply by 3 each time: 27 × 3 = 81." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>50, 45, 40, 35, ?</span>", options: ["25", "28", "30", "32"], answer: 2, explain: "Subtract 5 each time: 35 − 5 = 30." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>2, 3, 5, 8, 12, ?</span>", options: ["15", "16", "17", "19"], answer: 2, explain: "Differences grow 1, 2, 3, 4, 5: 12 + 5 = 17." },
        { cat: "numerical", topic: "Arithmetic", prompt: "What is 7 × 6?", options: ["36", "42", "48", "49"], answer: 1, explain: "7 × 6 = 42." },
        { cat: "numerical", topic: "Arithmetic", prompt: "What is 30% of 150?", options: ["30", "40", "45", "50"], answer: 2, explain: "0.30 × 150 = 45." },
        { cat: "numerical", topic: "Word problem", prompt: "A pizza is cut into 8 slices and you eat 3. What fraction is left?", options: ["3/8", "5/8", "1/2", "5/3"], answer: 1, explain: "8 − 3 = 5 slices remain, i.e. 5/8." },
        { cat: "numerical", topic: "Word problem", prompt: "A book has 240 pages and you have read 60. What percentage have you read?", options: ["20%", "25%", "30%", "40%"], answer: 1, explain: "60 ÷ 240 = 0.25 = 25%." },
        { cat: "numerical", topic: "Arithmetic", prompt: "What is 1000 − 365?", options: ["625", "635", "645", "735"], answer: 1, explain: "1000 − 365 = 635." },
        { cat: "logical", topic: "Letter series", prompt: "What comes next?  <span class='mono'>A, B, D, G, K, ?</span>", options: ["N", "O", "P", "Q"], answer: 2, explain: "Steps grow +1, +2, +3, +4, +5: K (11) + 5 = P (16)." },
        { cat: "logical", topic: "Logic", prompt: "All squares are rectangles, and all rectangles have four sides. Therefore all squares ___", options: ["have four sides", "are circles", "have three sides", "are triangles"], answer: 0, explain: "Squares are rectangles, and rectangles have four sides, so squares do too." },
        { cat: "logical", topic: "Logic", prompt: "A clock reads 3:00. Through how many degrees does the HOUR hand move by 6:00?", options: ["45°", "60°", "90°", "180°"], answer: 2, explain: "The hour hand moves 30° per hour; 3 hours × 30° = 90°." },
        { cat: "logical", topic: "Logic", prompt: "Sarah sits between Tom and Uma, with Tom on the left. Who is on the right?", options: ["Tom", "Sarah", "Uma", "Cannot tell"], answer: 2, explain: "Left→right the order is Tom, Sarah, Uma, so Uma is on the right." },
        { cat: "logical", topic: "Logic", prompt: "It takes 3 minutes to boil one egg. How long to boil 4 eggs together in the same pot?", options: ["3 minutes", "6 minutes", "9 minutes", "12 minutes"], answer: 0, explain: "Boiled together, all four eggs cook in the same 3 minutes." },
        { cat: "logical", topic: "Classification", prompt: "Which number does NOT belong?", options: ["3", "5", "7", "9"], answer: 3, explain: "3, 5 and 7 are prime; 9 = 3 × 3 is not." },
      ],
    },

    /* ===================== TEST 5 ===================== */
    {
      id: "form-5", name: "Test 5", blurb: "Trickier sequences with changing rules, plus averages and geometry.",
      questions: [
        { cat: "verbal", topic: "Synonym", prompt: "Choose the word closest in meaning to <span class='mono'>ENORMOUS</span>.", options: ["Tiny", "Huge", "Average", "Narrow"], answer: 1, explain: "Enormous means extremely large — huge." },
        { cat: "verbal", topic: "Synonym", prompt: "Choose the word closest in meaning to <span class='mono'>FERTILE</span>.", options: ["Barren", "Productive", "Dry", "Hard"], answer: 1, explain: "Fertile land is productive." },
        { cat: "verbal", topic: "Synonym", prompt: "Choose the word closest in meaning to <span class='mono'>ASSIST</span>.", options: ["Hinder", "Help", "Ignore", "Watch"], answer: 1, explain: "To assist is to help." },
        { cat: "verbal", topic: "Antonym", prompt: "Choose the OPPOSITE of <span class='mono'>ACCEPT</span>.", options: ["Receive", "Reject", "Approve", "Hold"], answer: 1, explain: "To accept is to take in; to reject is the opposite." },
        { cat: "verbal", topic: "Antonym", prompt: "Choose the OPPOSITE of <span class='mono'>FREQUENT</span>.", options: ["Often", "Rare", "Regular", "Common"], answer: 1, explain: "Frequent means happening often; rare is the opposite." },
        { cat: "verbal", topic: "Analogy", prompt: "Eye is to See as Ear is to ___", options: ["Hear", "Nose", "Music", "Loud"], answer: 0, explain: "The eye is used to see; the ear is used to hear." },
        { cat: "verbal", topic: "Analogy", prompt: "Sheep is to Flock as Fish is to ___", options: ["Pack", "School", "Herd", "Swarm"], answer: 1, explain: "A group of sheep is a flock; a group of fish is a school." },
        { cat: "verbal", topic: "Analogy", prompt: "Glove is to Hand as Hat is to ___", options: ["Head", "Hair", "Coat", "Ear"], answer: 0, explain: "A glove is worn on the hand; a hat is worn on the head." },
        { cat: "verbal", topic: "Analogy", prompt: "Tall is to Short as Wide is to ___", options: ["Long", "Narrow", "Big", "Broad"], answer: 1, explain: "Tall/short and wide/narrow are opposite pairs." },
        { cat: "verbal", topic: "Odd one out", prompt: "Which word does NOT belong with the others?", options: ["Mercury", "Venus", "Mars", "Moon"], answer: 3, explain: "Mercury, Venus and Mars are planets; the Moon is a satellite." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>11, 22, 33, 44, ?</span>", options: ["50", "55", "66", "54"], answer: 1, explain: "Add 11 each time: 44 + 11 = 55." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>64, 32, 16, 8, ?</span>", options: ["2", "4", "6", "8"], answer: 1, explain: "Halve each time: 8 ÷ 2 = 4." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>1, 4, 10, 22, ?</span>", options: ["40", "44", "46", "48"], answer: 2, explain: "Rule is ×2 + 2: 22 × 2 + 2 = 46." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>3, 5, 9, 17, ?</span>", options: ["25", "30", "33", "34"], answer: 2, explain: "Differences double (2, 4, 8, 16): 17 + 16 = 33." },
        { cat: "numerical", topic: "Arithmetic", prompt: "What is 13 + 19?", options: ["30", "31", "32", "33"], answer: 2, explain: "13 + 19 = 32." },
        { cat: "numerical", topic: "Arithmetic", prompt: "What is 20% of 250?", options: ["40", "45", "50", "55"], answer: 2, explain: "0.20 × 250 = 50." },
        { cat: "numerical", topic: "Word problem", prompt: "A worker earns $15 per hour. What is the pay for a 7-hour shift?", options: ["$95", "$105", "$115", "$120"], answer: 1, explain: "15 × 7 = $105." },
        { cat: "numerical", topic: "Word problem", prompt: "What is the average of 10, 20 and 30?", options: ["15", "20", "25", "30"], answer: 1, explain: "(10 + 20 + 30) ÷ 3 = 60 ÷ 3 = 20." },
        { cat: "numerical", topic: "Word problem", prompt: "You buy 3 items at $4.50 each. What is the total?", options: ["$12.50", "$13.00", "$13.50", "$14.50"], answer: 2, explain: "3 × $4.50 = $13.50." },
        { cat: "logical", topic: "Letter series", prompt: "What comes next?  <span class='mono'>C, F, I, L, ?</span>", options: ["M", "N", "O", "P"], answer: 2, explain: "Add three letters each time: L → O." },
        { cat: "logical", topic: "Logic", prompt: "No reptiles are warm-blooded. All snakes are reptiles. Which must be true?", options: ["No snakes are warm-blooded", "Some snakes are warm-blooded", "All reptiles are snakes", "All snakes are warm-blooded"], answer: 0, explain: "Snakes are reptiles and no reptile is warm-blooded, so no snake is." },
        { cat: "logical", topic: "Logic", prompt: "If March 1st is a Sunday, what day is March 8th?", options: ["Saturday", "Sunday", "Monday", "Friday"], answer: 1, explain: "The 8th is exactly 7 days later, the same weekday — Sunday." },
        { cat: "logical", topic: "Logic", prompt: "Anya beats Bo. Bo beats Cy. Cy beats Dee. Who is faster, Anya or Cy?", options: ["Anya", "Cy", "They tie", "Cannot tell"], answer: 0, explain: "Anya > Bo > Cy, so Anya is faster than Cy." },
        { cat: "logical", topic: "Logic", prompt: "How many faces does a cube have?", options: ["4", "6", "8", "12"], answer: 1, explain: "A cube has 6 square faces." },
        { cat: "logical", topic: "Classification", prompt: "Which number does NOT belong?", options: ["4", "6", "8", "9"], answer: 3, explain: "4, 6 and 8 are even; 9 is odd." },
      ],
    },

    /* ===================== TEST 6 ===================== */
    {
      id: "form-6", name: "Test 6", blurb: "Cubes, accelerating differences and directional reasoning.",
      questions: [
        { cat: "verbal", topic: "Synonym", prompt: "Choose the word closest in meaning to <span class='mono'>COMMENCE</span>.", options: ["End", "Begin", "Pause", "Delay"], answer: 1, explain: "To commence is to begin." },
        { cat: "verbal", topic: "Synonym", prompt: "Choose the word closest in meaning to <span class='mono'>OBSTINATE</span>.", options: ["Flexible", "Stubborn", "Gentle", "Clever"], answer: 1, explain: "Obstinate means stubborn." },
        { cat: "verbal", topic: "Synonym", prompt: "Choose the word closest in meaning to <span class='mono'>TRANQUIL</span>.", options: ["Noisy", "Calm", "Busy", "Rough"], answer: 1, explain: "Tranquil means calm and peaceful." },
        { cat: "verbal", topic: "Antonym", prompt: "Choose the OPPOSITE of <span class='mono'>SUCCESS</span>.", options: ["Triumph", "Failure", "Reward", "Effort"], answer: 1, explain: "Success is achieving a goal; failure is the opposite." },
        { cat: "verbal", topic: "Antonym", prompt: "Choose the OPPOSITE of <span class='mono'>ARTIFICIAL</span>.", options: ["Fake", "Natural", "Plastic", "Modern"], answer: 1, explain: "Artificial means man-made; natural is the opposite." },
        { cat: "verbal", topic: "Analogy", prompt: "Cup is to Coffee as Bowl is to ___", options: ["Soup", "Spoon", "Plate", "Glass"], answer: 0, explain: "A cup holds coffee as a bowl holds soup." },
        { cat: "verbal", topic: "Analogy", prompt: "Teacher is to School as Judge is to ___", options: ["Court", "Law", "Jail", "Trial"], answer: 0, explain: "A teacher works in a school; a judge works in a court." },
        { cat: "verbal", topic: "Analogy", prompt: "Begin is to End as Birth is to ___", options: ["Death", "Baby", "Life", "Grow"], answer: 0, explain: "Begin/end and birth/death are opposite pairs marking start and finish." },
        { cat: "verbal", topic: "Analogy", prompt: "Petal is to Flower as Page is to ___", options: ["Book", "Word", "Read", "Cover"], answer: 0, explain: "A petal is part of a flower; a page is part of a book." },
        { cat: "verbal", topic: "Odd one out", prompt: "Which word does NOT belong with the others?", options: ["Hammer", "Saw", "Drill", "Nail"], answer: 3, explain: "Hammer, saw and drill are tools; a nail is a fastener." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>5, 11, 17, 23, ?</span>", options: ["27", "28", "29", "30"], answer: 2, explain: "Add 6 each time: 23 + 6 = 29." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>2, 6, 18, 54, ?</span>", options: ["108", "148", "162", "216"], answer: 2, explain: "Multiply by 3 each time: 54 × 3 = 162." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>100, 96, 88, 76, 60, ?</span>", options: ["36", "40", "44", "48"], answer: 1, explain: "Subtract 4, 8, 12, 16, then 20: 60 − 20 = 40." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>1, 8, 27, 64, ?</span>", options: ["100", "121", "125", "216"], answer: 2, explain: "Cubes 1³, 2³, 3³, 4³, 5³ = 125." },
        { cat: "numerical", topic: "Arithmetic", prompt: "What is 18 × 5?", options: ["80", "85", "90", "95"], answer: 2, explain: "18 × 5 = 90." },
        { cat: "numerical", topic: "Arithmetic", prompt: "What is ¾ of 60?", options: ["30", "40", "45", "48"], answer: 2, explain: "60 ÷ 4 = 15; 15 × 3 = 45." },
        { cat: "numerical", topic: "Word problem", prompt: "How many 250 ml cups can be filled from a 2-litre bottle?", options: ["4", "6", "8", "10"], answer: 2, explain: "2000 ml ÷ 250 ml = 8 cups." },
        { cat: "numerical", topic: "Word problem", prompt: "If 5 pens cost $7.50, what do 2 pens cost?", options: ["$2.50", "$3.00", "$3.50", "$4.00"], answer: 1, explain: "Each pen is $1.50; 2 × $1.50 = $3.00." },
        { cat: "numerical", topic: "Arithmetic", prompt: "What is 7² + 24?", options: ["63", "73", "83", "49"], answer: 1, explain: "49 + 24 = 73." },
        { cat: "logical", topic: "Letter series", prompt: "What comes next?  <span class='mono'>D, H, L, P, ?</span>", options: ["R", "S", "T", "U"], answer: 2, explain: "Add four letters each time: P (16) + 4 = T (20)." },
        { cat: "logical", topic: "Logic", prompt: "All managers attended the meeting. Raj did not attend. Which must be true?", options: ["Raj is not a manager", "Raj is a manager", "Everyone who attended is a manager", "Raj attended"], answer: 0, explain: "If every manager attended and Raj didn't, Raj cannot be a manager." },
        { cat: "logical", topic: "Logic", prompt: "A clock loses 2 minutes every hour. How many minutes does it lose in 6 hours?", options: ["8", "10", "12", "14"], answer: 2, explain: "2 minutes × 6 hours = 12 minutes." },
        { cat: "logical", topic: "Logic", prompt: "D is the heaviest box. C is heavier than A, and A is heavier than B. Which box is lightest?", options: ["A", "B", "C", "D"], answer: 1, explain: "Order is D > C > A > B, so B is lightest." },
        { cat: "logical", topic: "Logic", prompt: "You face north and turn 90° clockwise. Which way do you now face?", options: ["North", "East", "South", "West"], answer: 1, explain: "A 90° clockwise turn from north faces east." },
        { cat: "logical", topic: "Classification", prompt: "Which number does NOT belong?", options: ["21", "33", "44", "51"], answer: 2, explain: "21, 33 and 51 are divisible by 3; 44 is not." },
      ],
    },

    /* ===================== TEST 7 ===================== */
    {
      id: "form-7", name: "Test 7", blurb: "Rates, ages and chained inequalities — reasoning with a numeric edge.",
      questions: [
        { cat: "verbal", topic: "Synonym", prompt: "Choose the word closest in meaning to <span class='mono'>DIMINISH</span>.", options: ["Grow", "Reduce", "Repeat", "Hold"], answer: 1, explain: "To diminish is to reduce or make smaller." },
        { cat: "verbal", topic: "Synonym", prompt: "Choose the word closest in meaning to <span class='mono'>PECULIAR</span>.", options: ["Normal", "Strange", "Pleasant", "Common"], answer: 1, explain: "Peculiar means odd or strange." },
        { cat: "verbal", topic: "Synonym", prompt: "Choose the word closest in meaning to <span class='mono'>ESSENTIAL</span>.", options: ["Optional", "Necessary", "Useless", "Extra"], answer: 1, explain: "Essential means absolutely necessary." },
        { cat: "verbal", topic: "Antonym", prompt: "Choose the OPPOSITE of <span class='mono'>ABUNDANT</span>.", options: ["Plentiful", "Scarce", "Rich", "Full"], answer: 1, explain: "Abundant means plentiful; scarce is the opposite." },
        { cat: "verbal", topic: "Antonym", prompt: "Choose the OPPOSITE of <span class='mono'>ASCEND</span>.", options: ["Climb", "Descend", "Rise", "Lift"], answer: 1, explain: "To ascend is to go up; to descend is to go down." },
        { cat: "verbal", topic: "Analogy", prompt: "Spider is to Web as Bird is to ___", options: ["Nest", "Sky", "Egg", "Wing"], answer: 0, explain: "A spider builds a web; a bird builds a nest." },
        { cat: "verbal", topic: "Analogy", prompt: "Broom is to Sweep as Shovel is to ___", options: ["Dig", "Sand", "Lift", "Clean"], answer: 0, explain: "A broom is used to sweep; a shovel is used to dig." },
        { cat: "verbal", topic: "Analogy", prompt: "North is to South as East is to ___", options: ["West", "Up", "Left", "Down"], answer: 0, explain: "North/south and east/west are opposite compass points." },
        { cat: "verbal", topic: "Analogy", prompt: "Foal is to Horse as Lamb is to ___", options: ["Sheep", "Goat", "Cow", "Pig"], answer: 0, explain: "A foal is a young horse; a lamb is a young sheep." },
        { cat: "verbal", topic: "Odd one out", prompt: "Which word does NOT belong with the others?", options: ["Violin", "Flute", "Guitar", "Cello"], answer: 1, explain: "Violin, guitar and cello are string instruments; a flute is a wind instrument." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>4, 8, 12, 16, ?</span>", options: ["18", "20", "22", "24"], answer: 1, explain: "Add 4 each time: 16 + 4 = 20." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>3, 9, 27, 81, ?</span>", options: ["162", "200", "243", "324"], answer: 2, explain: "Multiply by 3 each time: 81 × 3 = 243." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>90, 80, 70, 60, ?</span>", options: ["40", "45", "50", "55"], answer: 2, explain: "Subtract 10 each time: 60 − 10 = 50." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>2, 4, 7, 11, 16, ?</span>", options: ["20", "21", "22", "23"], answer: 2, explain: "Differences grow 2, 3, 4, 5, 6: 16 + 6 = 22." },
        { cat: "numerical", topic: "Arithmetic", prompt: "What is 16 × 4?", options: ["48", "56", "64", "72"], answer: 2, explain: "16 × 4 = 64." },
        { cat: "numerical", topic: "Arithmetic", prompt: "What is 40% of 90?", options: ["32", "34", "36", "40"], answer: 2, explain: "0.40 × 90 = 36." },
        { cat: "numerical", topic: "Word problem", prompt: "A tank holds 60 litres and is one-third full. How many litres is that?", options: ["15", "20", "30", "40"], answer: 1, explain: "60 ÷ 3 = 20 litres." },
        { cat: "numerical", topic: "Word problem", prompt: "How long does a 180 km journey take at 90 km/h?", options: ["1.5 hours", "2 hours", "2.5 hours", "3 hours"], answer: 1, explain: "180 ÷ 90 = 2 hours." },
        { cat: "numerical", topic: "Arithmetic", prompt: "What is 250 + 175?", options: ["405", "415", "425", "435"], answer: 2, explain: "250 + 175 = 425." },
        { cat: "logical", topic: "Letter series", prompt: "What comes next?  <span class='mono'>B, E, H, K, ?</span>", options: ["L", "M", "N", "O"], answer: 2, explain: "Add three letters each time: K (11) + 3 = N (14)." },
        { cat: "logical", topic: "Logic", prompt: "Some athletes are swimmers. All swimmers can hold their breath. Which must be true?", options: ["Some athletes can hold their breath", "All athletes are swimmers", "No athletes swim", "All swimmers are athletes"], answer: 0, explain: "The athletes who are swimmers can all hold their breath, so some athletes can." },
        { cat: "logical", topic: "Logic", prompt: "If two days after tomorrow is Sunday, what day is today?", options: ["Wednesday", "Thursday", "Friday", "Saturday"], answer: 1, explain: "Tomorrow + 2 = Sunday ⇒ tomorrow is Friday ⇒ today is Thursday." },
        { cat: "logical", topic: "Logic", prompt: "P is 3 years older than Q. If Q is 10, how old is P?", options: ["8", "12", "13", "15"], answer: 2, explain: "P = 10 + 3 = 13." },
        { cat: "logical", topic: "Logic", prompt: "A square has a perimeter of 20 cm. How long is one side?", options: ["4 cm", "5 cm", "10 cm", "80 cm"], answer: 1, explain: "A square has 4 equal sides: 20 ÷ 4 = 5 cm." },
        { cat: "logical", topic: "Classification", prompt: "Which number does NOT belong?", options: ["8", "27", "64", "100"], answer: 3, explain: "8, 27 and 64 are perfect cubes; 100 is not." },
      ],
    },

    /* ===================== TEST 8 ===================== */
    {
      id: "form-8", name: "Test 8", blurb: "Triangular numbers, money sums and order puzzles.",
      questions: [
        { cat: "verbal", topic: "Synonym", prompt: "Choose the word closest in meaning to <span class='mono'>VITAL</span>.", options: ["Minor", "Crucial", "Optional", "Weak"], answer: 1, explain: "Vital means essential or crucial." },
        { cat: "verbal", topic: "Synonym", prompt: "Choose the word closest in meaning to <span class='mono'>LUMINOUS</span>.", options: ["Dark", "Bright", "Heavy", "Dull"], answer: 1, explain: "Luminous means giving off light — bright." },
        { cat: "verbal", topic: "Synonym", prompt: "Choose the word closest in meaning to <span class='mono'>MEND</span>.", options: ["Break", "Repair", "Lose", "Bend"], answer: 1, explain: "To mend is to repair." },
        { cat: "verbal", topic: "Antonym", prompt: "Choose the OPPOSITE of <span class='mono'>EXPENSIVE</span>.", options: ["Costly", "Cheap", "Valuable", "Rare"], answer: 1, explain: "Expensive means high-priced; cheap is the opposite." },
        { cat: "verbal", topic: "Antonym", prompt: "Choose the OPPOSITE of <span class='mono'>CRUEL</span>.", options: ["Mean", "Kind", "Harsh", "Strict"], answer: 1, explain: "Cruel means causing pain; kind is the opposite." },
        { cat: "verbal", topic: "Analogy", prompt: "Baker is to Bread as Chef is to ___", options: ["Meal", "Oven", "Recipe", "Kitchen"], answer: 0, explain: "A baker makes bread; a chef makes a meal." },
        { cat: "verbal", topic: "Analogy", prompt: "Clock is to Time as Ruler is to ___", options: ["Length", "Wood", "Lines", "School"], answer: 0, explain: "A clock measures time; a ruler measures length." },
        { cat: "verbal", topic: "Analogy", prompt: "Soft is to Hard as Light is to ___", options: ["Heavy", "Bright", "Dark", "Weak"], answer: 0, explain: "Soft/hard and light/heavy are opposite pairs (by weight)." },
        { cat: "verbal", topic: "Analogy", prompt: "Tree is to Forest as Star is to ___", options: ["Galaxy", "Sky", "Sun", "Night"], answer: 0, explain: "Many trees form a forest; many stars form a galaxy." },
        { cat: "verbal", topic: "Odd one out", prompt: "Which word does NOT belong with the others?", options: ["Square", "Rectangle", "Rhombus", "Sphere"], answer: 3, explain: "Square, rectangle and rhombus are flat four-sided shapes; a sphere is a solid." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>10, 20, 30, 40, ?</span>", options: ["45", "50", "55", "60"], answer: 1, explain: "Add 10 each time: 40 + 10 = 50." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>1, 2, 4, 8, 16, ?</span>", options: ["24", "30", "32", "48"], answer: 2, explain: "Each term doubles: 16 × 2 = 32." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>7, 12, 17, 22, ?</span>", options: ["25", "27", "29", "32"], answer: 1, explain: "Add 5 each time: 22 + 5 = 27." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>1, 3, 6, 10, 15, ?</span>", options: ["18", "20", "21", "24"], answer: 2, explain: "Triangular numbers; add 6: 15 + 6 = 21." },
        { cat: "numerical", topic: "Arithmetic", prompt: "What is 11 × 11?", options: ["111", "121", "131", "144"], answer: 1, explain: "11 × 11 = 121." },
        { cat: "numerical", topic: "Arithmetic", prompt: "What is 60% of 200?", options: ["100", "110", "120", "140"], answer: 2, explain: "0.60 × 200 = 120." },
        { cat: "numerical", topic: "Word problem", prompt: "You pay for a $32.50 item with $50. What is your change?", options: ["$16.50", "$17.50", "$18.50", "$22.50"], answer: 1, explain: "$50.00 − $32.50 = $17.50." },
        { cat: "numerical", topic: "Word problem", prompt: "A recipe for 4 people uses 200 g of flour. How much for 6 people?", options: ["250 g", "300 g", "350 g", "400 g"], answer: 1, explain: "50 g per person × 6 = 300 g." },
        { cat: "numerical", topic: "Arithmetic", prompt: "What is 12 × 12 − 44?", options: ["90", "100", "110", "120"], answer: 1, explain: "144 − 44 = 100." },
        { cat: "logical", topic: "Letter series", prompt: "What comes next?  <span class='mono'>A, A, B, B, C, C, D, ?</span>", options: ["C", "D", "E", "F"], answer: 1, explain: "Each letter repeats once; D appears again before E." },
        { cat: "logical", topic: "Logic", prompt: "All birds have feathers. A penguin is a bird. Which must be true?", options: ["A penguin has feathers", "A penguin can fly", "All feathered things are penguins", "Penguins are not birds"], answer: 0, explain: "All birds have feathers and a penguin is a bird, so it has feathers." },
        { cat: "logical", topic: "Logic", prompt: "How many minutes are there from 9:45 to 10:15?", options: ["20", "25", "30", "35"], answer: 2, explain: "15 minutes to 10:00, plus 15 more, = 30 minutes." },
        { cat: "logical", topic: "Logic", prompt: "Mara is older than Nia, Nia older than Omar, Omar older than Pia. Who is second oldest?", options: ["Mara", "Nia", "Omar", "Pia"], answer: 1, explain: "Order is Mara > Nia > Omar > Pia, so Nia is second oldest." },
        { cat: "logical", topic: "Logic", prompt: "You walk 3 blocks north, then 3 blocks south. How far are you from where you started?", options: ["0 blocks", "3 blocks", "6 blocks", "9 blocks"], answer: 0, explain: "Going out and back the same distance returns you to the start." },
        { cat: "logical", topic: "Classification", prompt: "Which number does NOT belong?", options: ["14", "21", "28", "30"], answer: 3, explain: "14, 21 and 28 are multiples of 7; 30 is not." },
      ],
    },

    /* ===================== TEST 9 ===================== */
    {
      id: "form-9", name: "Test 9", blurb: "Primes, two-letter patterns and contrapositive logic.",
      questions: [
        { cat: "verbal", topic: "Synonym", prompt: "Choose the word closest in meaning to <span class='mono'>RESILIENT</span>.", options: ["Fragile", "Tough", "Soft", "Weak"], answer: 1, explain: "Resilient means able to recover — tough or hardy." },
        { cat: "verbal", topic: "Synonym", prompt: "Choose the word closest in meaning to <span class='mono'>SCARCE</span>.", options: ["Plentiful", "Rare", "Cheap", "Heavy"], answer: 1, explain: "Scarce means in short supply — rare." },
        { cat: "verbal", topic: "Synonym", prompt: "Choose the word closest in meaning to <span class='mono'>PROHIBIT</span>.", options: ["Allow", "Forbid", "Permit", "Enable"], answer: 1, explain: "To prohibit is to forbid." },
        { cat: "verbal", topic: "Antonym", prompt: "Choose the OPPOSITE of <span class='mono'>MAJORITY</span>.", options: ["Most", "Minority", "Group", "Crowd"], answer: 1, explain: "Majority is the greater part; minority the smaller." },
        { cat: "verbal", topic: "Antonym", prompt: "Choose the OPPOSITE of <span class='mono'>OPTIMISTIC</span>.", options: ["Hopeful", "Pessimistic", "Cheerful", "Positive"], answer: 1, explain: "Optimistic expects good outcomes; pessimistic expects bad." },
        { cat: "verbal", topic: "Analogy", prompt: "Captain is to Ship as Pilot is to ___", options: ["Airplane", "Sky", "Engine", "Runway"], answer: 0, explain: "A captain commands a ship; a pilot flies an airplane." },
        { cat: "verbal", topic: "Analogy", prompt: "Hungry is to Eat as Tired is to ___", options: ["Sleep", "Run", "Read", "Work"], answer: 0, explain: "You eat to relieve hunger and sleep to relieve tiredness." },
        { cat: "verbal", topic: "Analogy", prompt: "Inhale is to Exhale as Import is to ___", options: ["Export", "Trade", "Buy", "Goods"], answer: 0, explain: "Inhale/exhale (in/out) mirrors import/export (in/out)." },
        { cat: "verbal", topic: "Analogy", prompt: "Second is to Minute as Minute is to ___", options: ["Hour", "Day", "Clock", "Time"], answer: 0, explain: "60 seconds make a minute as 60 minutes make an hour." },
        { cat: "verbal", topic: "Odd one out", prompt: "Which word does NOT belong with the others?", options: ["Whale", "Shark", "Dolphin", "Seal"], answer: 1, explain: "Whale, dolphin and seal are mammals; a shark is a fish." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>9, 18, 27, 36, ?</span>", options: ["42", "44", "45", "54"], answer: 2, explain: "Add 9 each time: 36 + 9 = 45." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>256, 128, 64, 32, ?</span>", options: ["8", "12", "16", "24"], answer: 2, explain: "Halve each time: 32 ÷ 2 = 16." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>2, 3, 5, 7, 11, ?</span>", options: ["12", "13", "14", "15"], answer: 1, explain: "These are the prime numbers; after 11 comes 13." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>5, 10, 30, 120, ?</span>", options: ["480", "600", "720", "360"], answer: 1, explain: "Multiply by 2, 3, 4, then 5: 120 × 5 = 600." },
        { cat: "numerical", topic: "Arithmetic", prompt: "What is 144 − 89?", options: ["45", "55", "65", "56"], answer: 1, explain: "144 − 89 = 55." },
        { cat: "numerical", topic: "Arithmetic", prompt: "What is 12.5% of 80?", options: ["8", "10", "12", "16"], answer: 1, explain: "12.5% is one-eighth: 80 ÷ 8 = 10." },
        { cat: "numerical", topic: "Word problem", prompt: "A car travels 240 km on 20 litres of fuel. How many km per litre?", options: ["10", "12", "14", "20"], answer: 1, explain: "240 ÷ 20 = 12 km per litre." },
        { cat: "numerical", topic: "Word problem", prompt: "If 4 tickets cost $26, what is the price of one ticket?", options: ["$6.00", "$6.50", "$7.00", "$7.50"], answer: 1, explain: "$26 ÷ 4 = $6.50." },
        { cat: "numerical", topic: "Arithmetic", prompt: "What is (15 × 4) ÷ 6?", options: ["8", "9", "10", "12"], answer: 2, explain: "15 × 4 = 60; 60 ÷ 6 = 10." },
        { cat: "logical", topic: "Letter series", prompt: "What comes next?  <span class='mono'>AZ, BY, CX, DW, ?</span>", options: ["EV", "EU", "FV", "EW"], answer: 0, explain: "First letter advances A→E; second retreats Z→V, giving EV." },
        { cat: "logical", topic: "Logic", prompt: "If it rains, the match is cancelled. The match was NOT cancelled. Which must be true?", options: ["It did not rain", "It rained", "The match was played in the rain", "Cannot tell"], answer: 0, explain: "Rain would force a cancellation; since there was none, it did not rain." },
        { cat: "logical", topic: "Logic", prompt: "Today is Friday. What day was it 10 days ago?", options: ["Monday", "Tuesday", "Wednesday", "Thursday"], answer: 1, explain: "10 days = 1 week + 3 days; 3 days before Friday is Tuesday." },
        { cat: "logical", topic: "Logic", prompt: "P is twice as old as Q. Q is 3 years older than R. If R is 5, how old is P?", options: ["10", "13", "16", "18"], answer: 2, explain: "Q = 5 + 3 = 8; P = 2 × 8 = 16." },
        { cat: "logical", topic: "Logic", prompt: "A triangle has angles of 90° and 30°. What is the third angle?", options: ["30°", "60°", "90°", "120°"], answer: 1, explain: "Angles total 180°: 180 − 90 − 30 = 60°." },
        { cat: "logical", topic: "Classification", prompt: "Which number does NOT belong?", options: ["11", "13", "15", "17"], answer: 2, explain: "11, 13 and 17 are prime; 15 = 3 × 5 is not." },
      ],
    },

    /* ===================== TEST 10 ===================== */
    {
      id: "form-10", name: "Test 10", blurb: "The toughest set — factorials, multi-rule sequences and harder vocabulary.",
      questions: [
        { cat: "verbal", topic: "Synonym", prompt: "Choose the word closest in meaning to <span class='mono'>ELABORATE</span>.", options: ["Simple", "Detailed", "Brief", "Plain"], answer: 1, explain: "Elaborate means worked out in great detail." },
        { cat: "verbal", topic: "Synonym", prompt: "Choose the word closest in meaning to <span class='mono'>ADVERSITY</span>.", options: ["Comfort", "Hardship", "Wealth", "Luck"], answer: 1, explain: "Adversity means difficulty or hardship." },
        { cat: "verbal", topic: "Synonym", prompt: "Choose the word closest in meaning to <span class='mono'>NOTORIOUS</span>.", options: ["Honourable", "Infamous", "Unknown", "Praised"], answer: 1, explain: "Notorious means famous for something bad — infamous." },
        { cat: "verbal", topic: "Antonym", prompt: "Choose the OPPOSITE of <span class='mono'>CONDENSE</span>.", options: ["Compress", "Expand", "Shrink", "Thicken"], answer: 1, explain: "To condense is to compress; to expand is the opposite." },
        { cat: "verbal", topic: "Antonym", prompt: "Choose the OPPOSITE of <span class='mono'>LENIENT</span>.", options: ["Easygoing", "Strict", "Gentle", "Fair"], answer: 1, explain: "Lenient means permissive; strict is the opposite." },
        { cat: "verbal", topic: "Analogy", prompt: "Sculptor is to Statue as Poet is to ___", options: ["Poem", "Word", "Pen", "Rhyme"], answer: 0, explain: "A sculptor creates a statue; a poet creates a poem." },
        { cat: "verbal", topic: "Analogy", prompt: "Drought is to Water as Famine is to ___", options: ["Food", "Rain", "Land", "People"], answer: 0, explain: "A drought is a shortage of water; a famine is a shortage of food." },
        { cat: "verbal", topic: "Analogy", prompt: "Novice is to Expert as Dawn is to ___", options: ["Dusk", "Morning", "Night", "Noon"], answer: 0, explain: "Novice→expert is beginning→end, as dawn→dusk is start→end of day." },
        { cat: "verbal", topic: "Analogy", prompt: "Cog is to Machine as Cell is to ___", options: ["Body", "Prison", "Phone", "Battery"], answer: 0, explain: "A cog is a small working part of a machine; a cell is the basic unit of a body." },
        { cat: "verbal", topic: "Odd one out", prompt: "Which word does NOT belong with the others?", options: ["Honesty", "Courage", "Patience", "Diamond"], answer: 3, explain: "Honesty, courage and patience are abstract virtues; a diamond is a physical object." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>13, 26, 39, 52, ?</span>", options: ["60", "62", "65", "78"], answer: 2, explain: "Add 13 each time: 52 + 13 = 65." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>1, 10, 100, 1000, ?</span>", options: ["5000", "9000", "10000", "100000"], answer: 2, explain: "Multiply by 10 each time: 1000 × 10 = 10,000." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>2, 5, 10, 17, 26, ?</span>", options: ["35", "36", "37", "38"], answer: 2, explain: "Differences grow 3, 5, 7, 9, 11: 26 + 11 = 37." },
        { cat: "numerical", topic: "Number series", prompt: "What comes next?  <span class='mono'>1, 2, 6, 24, 120, ?</span>", options: ["600", "720", "240", "840"], answer: 1, explain: "Factorials; multiply by 2, 3, 4, 5, then 6: 120 × 6 = 720." },
        { cat: "numerical", topic: "Arithmetic", prompt: "What is 19 × 21?", options: ["389", "399", "409", "419"], answer: 1, explain: "19 × 21 = (20 − 1)(20 + 1) = 400 − 1 = 399." },
        { cat: "numerical", topic: "Arithmetic", prompt: "What is 35% of 160?", options: ["48", "52", "56", "60"], answer: 2, explain: "0.35 × 160 = 56." },
        { cat: "numerical", topic: "Word problem", prompt: "A worker finishes one-quarter of a job each day. How many days to finish the whole job?", options: ["2", "3", "4", "5"], answer: 2, explain: "Four quarters make a whole, so 4 days." },
        { cat: "numerical", topic: "Word problem", prompt: "A price rises from $80 to $100. What is the percentage increase?", options: ["20%", "25%", "30%", "125%"], answer: 1, explain: "Increase of $20 on $80 is 20 ÷ 80 = 25%." },
        { cat: "numerical", topic: "Arithmetic", prompt: "What is (144 ÷ 12) × 5?", options: ["50", "55", "60", "72"], answer: 2, explain: "144 ÷ 12 = 12; 12 × 5 = 60." },
        { cat: "logical", topic: "Letter series", prompt: "What comes next?  <span class='mono'>Z, W, T, Q, ?</span>", options: ["O", "N", "M", "P"], answer: 1, explain: "Step back three letters each time: Q (17) − 3 = N (14)." },
        { cat: "logical", topic: "Logic", prompt: "Everyone who passed the exam studied. Mia did not study. Which must be true?", options: ["Mia did not pass", "Mia passed", "Studying guarantees passing", "Mia studied"], answer: 0, explain: "Passing required studying; since Mia did not study, she did not pass." },
        { cat: "logical", topic: "Logic", prompt: "A meeting starts at 2:50 PM and lasts 95 minutes. When does it end?", options: ["4:15 PM", "4:25 PM", "4:35 PM", "4:45 PM"], answer: 1, explain: "95 minutes = 1 hour 35 minutes; 2:50 + 1:35 = 4:25 PM." },
        { cat: "logical", topic: "Logic", prompt: "Six houses stand in a row numbered 1–6 from left to right. The red house is number 4. How many houses are to its right?", options: ["1", "2", "3", "4"], answer: 1, explain: "Houses 5 and 6 are to the right — that is 2 houses." },
        { cat: "logical", topic: "Logic", prompt: "A wheel makes 3 complete turns. Through how many degrees does it rotate in total?", options: ["360°", "720°", "1080°", "900°"], answer: 2, explain: "One turn is 360°; 3 × 360° = 1080°." },
        { cat: "logical", topic: "Classification", prompt: "Which number does NOT belong?", options: ["16", "25", "36", "50"], answer: 3, explain: "16, 25 and 36 are perfect squares; 50 is not." },
      ],
    },
  ],
};
