/* ============================================================
   MMAT — question bank (harder edition)

   All items ORIGINAL, written in the spirit of the McQuaig
   Mental Agility Test. Difficulty raised across the board:
   trickier series (changing rules, second differences),
   multi-step word problems, harder vocabulary, compound
   syllogisms, coding/directions/relations.

   The engine INTERLEAVES questions at runtime so no two
   adjacent items share a topic — authoring stays in blocks.

   Schema (consumed by app.js):
     cat     : "verbal" | "numerical" | "logical"
     topic   : sub-type (used for interleaving + weak-area analysis)
     diff    : 1 moderate · 2 hard · 3 very hard
     prompt  : question text (may contain inline HTML)
     options : 3–5 answer strings
     answer  : index of the correct option
     explain : one-line worked answer shown in review
   ============================================================ */
window.MMAT = {
  config: {
    durationSec: 900,       // full forms: 15 minutes
    freeDurationSec: 300,   // free taster: 5 minutes
    diffLabels: { 1: "Moderate", 2: "Hard", 3: "Very hard" },
  },

  categories: {
    verbal:    { label: "Verbal",    color: "#5aa9e6" },
    numerical: { label: "Numerical", color: "#46c98b" },
    logical:   { label: "Logical",   color: "#d9b25a" },
  },

  /* -------- FREE 5-minute taster (12 questions) -------- */
  freeTest: {
    id: "free", name: "Free 5-minute taster", free: true, durationSec: 300,
    blurb: "Twelve mixed questions in five minutes — a quick taste of the full test.",
    questions: [
      { cat: "verbal", topic: "Synonyms", diff: 1, prompt: "Choose the word closest in meaning to <span class='mono'>METICULOUS</span>.", options: ["Careless", "Thorough", "Hasty", "Loud"], answer: 1, explain: "Meticulous means showing great attention to detail — thorough." },
      { cat: "numerical", topic: "Number series", diff: 2, prompt: "What comes next?  <span class='mono'>2, 6, 12, 20, ?</span>", options: ["28", "30", "32", "42"], answer: 1, explain: "Differences grow 4, 6, 8, 10: 20 + 10 = 30 (it is n²+n)." },
      { cat: "logical", topic: "Syllogisms", diff: 2, prompt: "All engineers are logical. Some logical people are artists. Which MUST be true?", options: ["All engineers are artists", "Some engineers are artists", "Some artists are logical", "No engineers are artists"], answer: 2, explain: "'Some logical people are artists' reverses to 'some artists are logical'." },
      { cat: "verbal", topic: "Analogies", diff: 2, prompt: "Drizzle is to Downpour as Breeze is to ___", options: ["Gale", "Calm", "Cloud", "Storm"], answer: 0, explain: "Each pair is mild → intense: a gale is an intense breeze." },
      { cat: "numerical", topic: "Percentages", diff: 1, prompt: "What is 12% of 150?", options: ["15", "18", "21", "12"], answer: 1, explain: "0.12 × 150 = 18." },
      { cat: "logical", topic: "Letter series", diff: 2, prompt: "What comes next?  <span class='mono'>B, D, G, K, ?</span>", options: ["O", "P", "Q", "N"], answer: 1, explain: "Steps grow +2, +3, +4, +5: K (11) + 5 = P (16)." },
      { cat: "verbal", topic: "Antonyms", diff: 1, prompt: "Choose the OPPOSITE of <span class='mono'>ABUNDANT</span>.", options: ["Ample", "Scarce", "Plenty", "Lavish"], answer: 1, explain: "Abundant means plentiful; scarce is the opposite." },
      { cat: "numerical", topic: "Word problems", diff: 2, prompt: "A shirt costs $50 after a 20% discount. What was the original price?", options: ["$60.00", "$62.50", "$70.00", "$65.00"], answer: 1, explain: "$50 is 80% of the original: 50 ÷ 0.8 = $62.50." },
      { cat: "logical", topic: "Logical deduction", diff: 1, prompt: "P is taller than Q but shorter than R. S is taller than R. Who is tallest?", options: ["P", "R", "S", "Q"], answer: 2, explain: "S > R > P > Q, so S is tallest." },
      { cat: "verbal", topic: "Odd one out", diff: 1, prompt: "Which word does NOT belong with the others?", options: ["Square", "Circle", "Triangle", "Cube"], answer: 3, explain: "Square, circle and triangle are flat shapes; a cube is a solid." },
      { cat: "numerical", topic: "Ratio & proportion", diff: 2, prompt: "Two numbers are in the ratio 2:3 and add up to 60. What is the larger number?", options: ["24", "36", "30", "40"], answer: 1, explain: "5 parts = 60, so 1 part = 12; the larger is 3 × 12 = 36." },
      { cat: "logical", topic: "Syllogisms", diff: 1, prompt: "No mammals are cold-blooded. All whales are mammals. Therefore:", options: ["No whales are cold-blooded", "Some whales are cold-blooded", "All mammals are whales", "Whales are cold-blooded"], answer: 0, explain: "Whales are mammals and no mammal is cold-blooded, so no whale is." },
    ],
  },

  /* -------- TEN FULL FORMS (25 questions each) -------- */
  tests: [
    /* ===================== TEST 1 ===================== */
    { id: "form-1", name: "Test 1", locked: true, blurb: "Mixed difficulty across vocabulary, changing-rule series and compound logic.",
      questions: [
        { cat: "verbal", topic: "Synonyms", diff: 2, prompt: "Closest in meaning to <span class='mono'>GARRULOUS</span>:", options: ["Talkative", "Silent", "Rude", "Gloomy"], answer: 0, explain: "Garrulous means excessively talkative." },
        { cat: "verbal", topic: "Synonyms", diff: 2, prompt: "Closest in meaning to <span class='mono'>MITIGATE</span>:", options: ["Worsen", "Alleviate", "Ignore", "Provoke"], answer: 1, explain: "To mitigate is to make less severe — to alleviate." },
        { cat: "verbal", topic: "Synonyms", diff: 1, prompt: "Closest in meaning to <span class='mono'>PRUDENT</span>:", options: ["Reckless", "Cautious", "Wealthy", "Hasty"], answer: 1, explain: "Prudent means careful and cautious." },
        { cat: "verbal", topic: "Antonyms", diff: 2, prompt: "Choose the OPPOSITE of <span class='mono'>AUGMENT</span>:", options: ["Increase", "Diminish", "Expand", "Boost"], answer: 1, explain: "Augment means to increase; diminish is the opposite." },
        { cat: "verbal", topic: "Antonyms", diff: 1, prompt: "Choose the OPPOSITE of <span class='mono'>OPAQUE</span>:", options: ["Solid", "Transparent", "Dull", "Dense"], answer: 1, explain: "Opaque blocks light; transparent lets it through." },
        { cat: "verbal", topic: "Analogies", diff: 2, prompt: "Whisper is to Shout as Drizzle is to ___", options: ["Downpour", "Cloud", "Wet", "Storm"], answer: 0, explain: "Each pair goes from gentle to intense." },
        { cat: "verbal", topic: "Analogies", diff: 2, prompt: "Cartographer is to Map as Lexicographer is to ___", options: ["Dictionary", "Novel", "Library", "Word"], answer: 0, explain: "A cartographer makes maps; a lexicographer makes dictionaries." },
        { cat: "verbal", topic: "Analogies", diff: 2, prompt: "Oasis is to Desert as Island is to ___", options: ["Ocean", "Sand", "Tree", "Beach"], answer: 0, explain: "An oasis is land surrounded by desert; an island is land surrounded by ocean." },
        { cat: "verbal", topic: "Odd one out", diff: 2, prompt: "Which does NOT belong?", options: ["Rectangle", "Rhombus", "Trapezoid", "Pyramid"], answer: 3, explain: "The first three are flat quadrilaterals; a pyramid is a solid." },
        { cat: "verbal", topic: "Odd one out", diff: 2, prompt: "Which does NOT belong?", options: ["Hydrogen", "Oxygen", "Mercury", "Nitrogen"], answer: 2, explain: "Hydrogen, oxygen and nitrogen are gases; mercury is a liquid metal." },
        { cat: "numerical", topic: "Number series", diff: 2, prompt: "What comes next?  <span class='mono'>3, 7, 15, 31, ?</span>", options: ["47", "55", "63", "62"], answer: 2, explain: "Rule is ×2 + 1: 31 × 2 + 1 = 63." },
        { cat: "numerical", topic: "Number series", diff: 2, prompt: "What comes next?  <span class='mono'>2, 6, 12, 20, 30, ?</span>", options: ["40", "42", "44", "36"], answer: 1, explain: "Differences grow 4, 6, 8, 10, 12: 30 + 12 = 42." },
        { cat: "numerical", topic: "Number series", diff: 3, prompt: "What comes next?  <span class='mono'>5, 8, 17, 44, ?</span>", options: ["98", "125", "113", "131"], answer: 1, explain: "Rule is ×3 − 7: 44 × 3 − 7 = 125." },
        { cat: "numerical", topic: "Arithmetic", diff: 1, prompt: "What is (17 × 6) − 19?", options: ["79", "83", "87", "93"], answer: 1, explain: "102 − 19 = 83." },
        { cat: "numerical", topic: "Arithmetic", diff: 2, prompt: "What is √196 + √121?", options: ["23", "25", "27", "21"], answer: 1, explain: "14 + 11 = 25." },
        { cat: "numerical", topic: "Word problems", diff: 3, prompt: "A train covers 150 km at 50 km/h, then 150 km at 75 km/h. What is the average speed for the whole trip?", options: ["60 km/h", "62.5 km/h", "65 km/h", "55 km/h"], answer: 0, explain: "Total 300 km in 3 + 2 = 5 h → 60 km/h (not the simple average)." },
        { cat: "numerical", topic: "Word problems", diff: 2, prompt: "Four numbers average 18. A fifth number raises the average to 20. What is the fifth number?", options: ["24", "26", "28", "30"], answer: 2, explain: "Totals: 4×18 = 72 and 5×20 = 100, so the fifth = 28." },
        { cat: "numerical", topic: "Percentages", diff: 2, prompt: "After a 20% rise a price is $96. What was it before?", options: ["$76", "$80", "$84", "$76.80"], answer: 1, explain: "$96 is 120% of the original: 96 ÷ 1.2 = $80." },
        { cat: "numerical", topic: "Ratio & proportion", diff: 1, prompt: "Divide $84 in the ratio 3:4. What is the larger share?", options: ["$36", "$48", "$42", "$56"], answer: 1, explain: "7 parts = $84, so 1 part = $12; larger = 4 × 12 = $48." },
        { cat: "logical", topic: "Syllogisms", diff: 2, prompt: "All novels are books. Some books are heavy. Which MUST be true?", options: ["All novels are heavy", "Some novels are heavy", "All heavy things are books", "None necessarily follows"], answer: 3, explain: "The heavy books need not include any novel, so nothing certain follows." },
        { cat: "logical", topic: "Syllogisms", diff: 1, prompt: "No reptiles have fur. All snakes are reptiles. Therefore:", options: ["No snakes have fur", "Some snakes have fur", "All furry things are snakes", "Snakes are not reptiles"], answer: 0, explain: "Snakes are reptiles and no reptile has fur, so no snake has fur." },
        { cat: "logical", topic: "Logical deduction", diff: 1, prompt: "P is taller than Q. R is taller than P. S is shorter than Q. Who is tallest?", options: ["P", "Q", "R", "S"], answer: 2, explain: "R > P > Q > S, so R is tallest." },
        { cat: "logical", topic: "Logical deduction", diff: 2, prompt: "In a row of 7 people, X is 3rd from the left and Y is 3rd from the right. How many people sit between them?", options: ["0", "1", "2", "3"], answer: 1, explain: "X is at position 3 and Y at position 5; only position 4 is between them." },
        { cat: "logical", topic: "Letter series", diff: 2, prompt: "What comes next?  <span class='mono'>A, C, F, J, O, ?</span>", options: ["T", "U", "V", "W"], answer: 1, explain: "Steps grow +2, +3, +4, +5, +6: O (15) + 6 = U (21)." },
        { cat: "logical", topic: "Coding", diff: 2, prompt: "If COLD is written DPME (each letter +1), how is WIND written?", options: ["XJOE", "VHMC", "XKPE", "WJOE"], answer: 0, explain: "Shift each letter forward one: W→X, I→J, N→O, D→E = XJOE." },
      ],
    },

    /* ===================== TEST 2 ===================== */
    { id: "form-2", name: "Test 2", locked: true, blurb: "Worker-material analogies, geometric decay and direction tracking.",
      questions: [
        { cat: "verbal", topic: "Synonyms", diff: 2, prompt: "Closest in meaning to <span class='mono'>LACONIC</span>:", options: ["Wordy", "Concise", "Lazy", "Rude"], answer: 1, explain: "Laconic means using few words — concise." },
        { cat: "verbal", topic: "Synonyms", diff: 2, prompt: "Closest in meaning to <span class='mono'>ZEALOUS</span>:", options: ["Indifferent", "Fervent", "Tired", "Calm"], answer: 1, explain: "Zealous means full of zeal — fervent." },
        { cat: "verbal", topic: "Synonyms", diff: 1, prompt: "Closest in meaning to <span class='mono'>LUCID</span>:", options: ["Murky", "Clear", "Bright", "Dim"], answer: 1, explain: "Lucid means easy to understand — clear." },
        { cat: "verbal", topic: "Antonyms", diff: 2, prompt: "Choose the OPPOSITE of <span class='mono'>FRUGAL</span>:", options: ["Thrifty", "Wasteful", "Cheap", "Careful"], answer: 1, explain: "Frugal means sparing; wasteful is the opposite." },
        { cat: "verbal", topic: "Antonyms", diff: 2, prompt: "Choose the OPPOSITE of <span class='mono'>BENEVOLENT</span>:", options: ["Kind", "Malevolent", "Generous", "Gentle"], answer: 1, explain: "Benevolent means well-meaning; malevolent means ill-meaning." },
        { cat: "verbal", topic: "Analogies", diff: 2, prompt: "Sculptor is to Clay as Blacksmith is to ___", options: ["Iron", "Hammer", "Anvil", "Fire"], answer: 0, explain: "Each craftsman shapes the material: a blacksmith works iron." },
        { cat: "verbal", topic: "Analogies", diff: 2, prompt: "Library is to Books as Arboretum is to ___", options: ["Trees", "Animals", "Stars", "Art"], answer: 0, explain: "An arboretum is a collection of trees, as a library is of books." },
        { cat: "verbal", topic: "Analogies", diff: 1, prompt: "Novice is to Expert as Seed is to ___", options: ["Tree", "Soil", "Flower", "Root"], answer: 0, explain: "Each pair goes from an early stage to a mature one." },
        { cat: "verbal", topic: "Odd one out", diff: 2, prompt: "Which does NOT belong?", options: ["Lion", "Tiger", "Leopard", "Wolf"], answer: 3, explain: "Lion, tiger and leopard are big cats; a wolf is not." },
        { cat: "verbal", topic: "Odd one out", diff: 2, prompt: "Which does NOT belong?", options: ["Venus", "Mars", "Jupiter", "Sirius"], answer: 3, explain: "Venus, Mars and Jupiter are planets; Sirius is a star." },
        { cat: "numerical", topic: "Number series", diff: 2, prompt: "What comes next?  <span class='mono'>1, 3, 7, 13, 21, ?</span>", options: ["29", "31", "33", "30"], answer: 1, explain: "Differences grow 2, 4, 6, 8, 10: 21 + 10 = 31." },
        { cat: "numerical", topic: "Number series", diff: 2, prompt: "What comes next?  <span class='mono'>2, 3, 5, 9, 17, ?</span>", options: ["31", "33", "35", "34"], answer: 1, explain: "Rule is ×2 − 1: 17 × 2 − 1 = 33." },
        { cat: "numerical", topic: "Number series", diff: 3, prompt: "What comes next?  <span class='mono'>81, 54, 36, 24, ?</span>", options: ["16", "18", "20", "12"], answer: 0, explain: "Each term is two-thirds of the previous: 24 × 2/3 = 16." },
        { cat: "numerical", topic: "Arithmetic", diff: 2, prompt: "What is 13² − 12²?", options: ["23", "25", "27", "29"], answer: 1, explain: "(13−12)(13+12) = 1 × 25 = 25." },
        { cat: "numerical", topic: "Arithmetic", diff: 1, prompt: "What is (144 ÷ 12) + (7 × 8)?", options: ["66", "68", "70", "72"], answer: 1, explain: "12 + 56 = 68." },
        { cat: "numerical", topic: "Word problems", diff: 2, prompt: "If 6 workers build a wall in 8 days, how long would 4 workers take at the same rate?", options: ["10 days", "12 days", "14 days", "16 days"], answer: 1, explain: "6 × 8 = 48 worker-days; 48 ÷ 4 = 12 days." },
        { cat: "numerical", topic: "Word problems", diff: 2, prompt: "A car loses 10% of its value each year. What is a $20,000 car worth after 2 years?", options: ["$16,000", "$16,200", "$18,000", "$16,400"], answer: 1, explain: "20,000 × 0.9 × 0.9 = $16,200." },
        { cat: "numerical", topic: "Percentages", diff: 2, prompt: "30 is what percent of 240?", options: ["10%", "12.5%", "15%", "20%"], answer: 1, explain: "30 ÷ 240 = 0.125 = 12.5%." },
        { cat: "numerical", topic: "Ratio & proportion", diff: 2, prompt: "A recipe uses flour and sugar in the ratio 5:2. With 750 g of flour, how much sugar is needed?", options: ["250 g", "300 g", "350 g", "375 g"], answer: 1, explain: "750 ÷ 5 = 150 per part; sugar = 2 × 150 = 300 g." },
        { cat: "logical", topic: "Syllogisms", diff: 2, prompt: "Some doctors are runners. All runners are fit. Which MUST be true?", options: ["All doctors are fit", "Some doctors are fit", "All runners are doctors", "No doctors are fit"], answer: 1, explain: "The doctors who run are fit, so some doctors are fit." },
        { cat: "logical", topic: "Syllogisms", diff: 1, prompt: "All squares are rhombuses. No rhombus is a circle. Therefore:", options: ["No square is a circle", "Some squares are circles", "All rhombuses are squares", "Some circles are squares"], answer: 0, explain: "Squares are rhombuses and no rhombus is a circle, so no square is a circle." },
        { cat: "logical", topic: "Logical deduction", diff: 1, prompt: "If today is two days after Monday, what day is it tomorrow?", options: ["Wednesday", "Thursday", "Friday", "Tuesday"], answer: 1, explain: "Two days after Monday is Wednesday, so tomorrow is Thursday." },
        { cat: "logical", topic: "Logical deduction", diff: 2, prompt: "Red is heavier than Blue. Green is lighter than Blue. Yellow is heavier than Red. Which is lightest?", options: ["Red", "Blue", "Green", "Yellow"], answer: 2, explain: "Yellow > Red > Blue > Green, so Green is lightest." },
        { cat: "logical", topic: "Letter series", diff: 3, prompt: "What comes next?  <span class='mono'>Z, W, S, N, ?</span>", options: ["H", "I", "G", "J"], answer: 0, explain: "Steps back grow −3, −4, −5, −6: N (14) − 6 = H (8)." },
        { cat: "logical", topic: "Directions", diff: 2, prompt: "You walk 4 km east, turn left and walk 3 km, then turn left and walk 4 km. How far are you from the start?", options: ["3 km", "4 km", "5 km", "7 km"], answer: 0, explain: "East 4 and west 4 cancel; you are 3 km north of start." },
      ],
    },

    /* ===================== TEST 3 ===================== */
    { id: "form-3", name: "Test 3", locked: true, blurb: "Doubling-rule series, pipes-and-cisterns and relationship logic.",
      questions: [
        { cat: "verbal", topic: "Synonyms", diff: 3, prompt: "Closest in meaning to <span class='mono'>EPHEMERAL</span>:", options: ["Eternal", "Fleeting", "Solid", "Heavy"], answer: 1, explain: "Ephemeral means lasting a very short time — fleeting." },
        { cat: "verbal", topic: "Synonyms", diff: 1, prompt: "Closest in meaning to <span class='mono'>OBSOLETE</span>:", options: ["Modern", "Outdated", "Useful", "Rare"], answer: 1, explain: "Obsolete means no longer in use — outdated." },
        { cat: "verbal", topic: "Synonyms", diff: 1, prompt: "Closest in meaning to <span class='mono'>CANDID</span>:", options: ["Sly", "Frank", "Shy", "Vague"], answer: 1, explain: "Candid means open and honest — frank." },
        { cat: "verbal", topic: "Antonyms", diff: 2, prompt: "Choose the OPPOSITE of <span class='mono'>VERBOSE</span>:", options: ["Wordy", "Concise", "Loud", "Plain"], answer: 1, explain: "Verbose means using too many words; concise is the opposite." },
        { cat: "verbal", topic: "Antonyms", diff: 3, prompt: "Choose the OPPOSITE of <span class='mono'>EXACERBATE</span>:", options: ["Worsen", "Alleviate", "Inflame", "Agitate"], answer: 1, explain: "To exacerbate is to make worse; to alleviate is to ease." },
        { cat: "verbal", topic: "Analogies", diff: 2, prompt: "Doctor is to Disease as Detective is to ___", options: ["Crime", "Police", "Clue", "Court"], answer: 0, explain: "Each fights the second term: a detective combats crime." },
        { cat: "verbal", topic: "Analogies", diff: 3, prompt: "Aviary is to Birds as Apiary is to ___", options: ["Bees", "Fish", "Snakes", "Horses"], answer: 0, explain: "An aviary keeps birds; an apiary keeps bees." },
        { cat: "verbal", topic: "Analogies", diff: 2, prompt: "Sponge is to Absorb as Sieve is to ___", options: ["Strain", "Soak", "Hold", "Fill"], answer: 0, explain: "A sponge absorbs; a sieve strains." },
        { cat: "verbal", topic: "Odd one out", diff: 3, prompt: "Which does NOT belong?", options: ["Copper", "Bronze", "Iron", "Gold"], answer: 1, explain: "Copper, iron and gold are elements; bronze is an alloy." },
        { cat: "verbal", topic: "Odd one out", diff: 1, prompt: "Which does NOT belong?", options: ["Triangle", "Pentagon", "Hexagon", "Sphere"], answer: 3, explain: "The first three are flat polygons; a sphere is a solid." },
        { cat: "numerical", topic: "Number series", diff: 1, prompt: "What comes next?  <span class='mono'>4, 9, 16, 25, 36, ?</span>", options: ["42", "45", "49", "48"], answer: 2, explain: "Squares of 2,3,4,5,6,7 → 7² = 49." },
        { cat: "numerical", topic: "Number series", diff: 2, prompt: "What comes next?  <span class='mono'>6, 11, 21, 41, ?</span>", options: ["61", "71", "81", "82"], answer: 2, explain: "Rule is ×2 − 1: 41 × 2 − 1 = 81." },
        { cat: "numerical", topic: "Number series", diff: 3, prompt: "What comes next?  <span class='mono'>7, 9, 13, 21, 37, ?</span>", options: ["53", "69", "73", "68"], answer: 1, explain: "Differences double 2, 4, 8, 16, 32: 37 + 32 = 69." },
        { cat: "numerical", topic: "Arithmetic", diff: 1, prompt: "What is 15 × 14?", options: ["196", "210", "225", "205"], answer: 1, explain: "15 × 14 = 210." },
        { cat: "numerical", topic: "Arithmetic", diff: 2, prompt: "What is 2³ + 3³ + 4³?", options: ["89", "99", "109", "100"], answer: 1, explain: "8 + 27 + 64 = 99." },
        { cat: "numerical", topic: "Word problems", diff: 2, prompt: "A shop buys an item for $40 and sells it for $50. What is the profit percentage?", options: ["20%", "25%", "10%", "12.5%"], answer: 1, explain: "Profit $10 on cost $40 = 25%." },
        { cat: "numerical", topic: "Word problems", diff: 3, prompt: "A pipe fills a tank in 6 hours; a drain empties it in 12 hours. With both open, how long to fill?", options: ["6 hours", "8 hours", "12 hours", "18 hours"], answer: 2, explain: "Net rate = 1/6 − 1/12 = 1/12 per hour, so 12 hours." },
        { cat: "numerical", topic: "Percentages", diff: 2, prompt: "A number increased by 25% becomes 75. What was the number?", options: ["50", "55", "60", "65"], answer: 2, explain: "75 ÷ 1.25 = 60." },
        { cat: "numerical", topic: "Ratio & proportion", diff: 2, prompt: "Two numbers are in the ratio 7:5 and differ by 18. What is the larger number?", options: ["63", "45", "49", "56"], answer: 0, explain: "Difference of 2 parts = 18, so 1 part = 9; larger = 7 × 9 = 63." },
        { cat: "logical", topic: "Syllogisms", diff: 1, prompt: "All cats are mammals. All mammals are animals. Therefore:", options: ["All cats are animals", "Some animals are not cats", "All animals are cats", "No cats are animals"], answer: 0, explain: "The chain gives: all cats are animals." },
        { cat: "logical", topic: "Syllogisms", diff: 2, prompt: "No heroes are cowards. Some soldiers are heroes. Which MUST be true?", options: ["Some soldiers are not cowards", "All soldiers are heroes", "Some soldiers are cowards", "No soldiers are cowards"], answer: 0, explain: "The hero-soldiers are not cowards, so some soldiers are not cowards." },
        { cat: "logical", topic: "Blood relations", diff: 2, prompt: "A is the father of B. C is the mother of A. What is C to B?", options: ["Mother", "Grandmother", "Aunt", "Sister"], answer: 1, explain: "C is A's mother, and A is B's father, so C is B's grandmother." },
        { cat: "logical", topic: "Logical deduction", diff: 2, prompt: "M scored higher than N. O scored lower than N. P scored higher than M. Q scored between M and N. Who scored highest?", options: ["M", "N", "P", "Q"], answer: 2, explain: "P > M > Q > N > O, so P is highest." },
        { cat: "logical", topic: "Letter series", diff: 2, prompt: "What comes next?  <span class='mono'>C, E, H, L, Q, ?</span>", options: ["V", "W", "X", "U"], answer: 1, explain: "Steps grow +2, +3, +4, +5, +6: Q (17) + 6 = W (23)." },
        { cat: "logical", topic: "Coding", diff: 2, prompt: "If CAT = 24 (3+1+20 by letter position), what is DOG?", options: ["24", "26", "28", "30"], answer: 1, explain: "D+O+G = 4 + 15 + 7 = 26." },
      ],
    },

    /* ===================== TEST 4 ===================== */
    { id: "form-4", name: "Test 4", locked: true, blurb: "Fibonacci-style series, successive discounts and a family riddle.",
      questions: [
        { cat: "verbal", topic: "Synonyms", diff: 3, prompt: "Closest in meaning to <span class='mono'>UBIQUITOUS</span>:", options: ["Rare", "Widespread", "Hidden", "Unique"], answer: 1, explain: "Ubiquitous means found everywhere — widespread." },
        { cat: "verbal", topic: "Synonyms", diff: 2, prompt: "Closest in meaning to <span class='mono'>PLACATE</span>:", options: ["Anger", "Appease", "Ignore", "Confuse"], answer: 1, explain: "To placate is to soothe — appease." },
        { cat: "verbal", topic: "Synonyms", diff: 2, prompt: "Closest in meaning to <span class='mono'>TENACIOUS</span>:", options: ["Weak", "Persistent", "Brief", "Loose"], answer: 1, explain: "Tenacious means holding firmly — persistent." },
        { cat: "verbal", topic: "Antonyms", diff: 2, prompt: "Choose the OPPOSITE of <span class='mono'>LETHARGIC</span>:", options: ["Sluggish", "Energetic", "Tired", "Calm"], answer: 1, explain: "Lethargic means sluggish; energetic is the opposite." },
        { cat: "verbal", topic: "Antonyms", diff: 1, prompt: "Choose the OPPOSITE of <span class='mono'>SCARCITY</span>:", options: ["Lack", "Abundance", "Few", "Drought"], answer: 1, explain: "Scarcity is shortage; abundance is plenty." },
        { cat: "verbal", topic: "Analogies", diff: 1, prompt: "Hammer is to Nail as Screwdriver is to ___", options: ["Screw", "Wood", "Tool", "Drill"], answer: 0, explain: "A hammer drives a nail; a screwdriver drives a screw." },
        { cat: "verbal", topic: "Analogies", diff: 2, prompt: "Mountain is to Peak as Wave is to ___", options: ["Crest", "Ocean", "Tide", "Foam"], answer: 0, explain: "The highest point of a mountain is its peak; of a wave, its crest." },
        { cat: "verbal", topic: "Analogies", diff: 2, prompt: "Author is to Manuscript as Architect is to ___", options: ["Blueprint", "Building", "Bricks", "City"], answer: 0, explain: "Each produces the plan: an architect draws a blueprint." },
        { cat: "verbal", topic: "Odd one out", diff: 2, prompt: "Which does NOT belong?", options: ["Inch", "Pound", "Yard", "Mile"], answer: 1, explain: "Inch, yard and mile measure length; a pound measures weight." },
        { cat: "verbal", topic: "Odd one out", diff: 1, prompt: "Which does NOT belong?", options: ["Square", "Cube", "Triangle", "Circle"], answer: 1, explain: "Square, triangle and circle are flat; a cube is a solid." },
        { cat: "numerical", topic: "Number series", diff: 2, prompt: "What comes next?  <span class='mono'>3, 4, 7, 11, 18, 29, ?</span>", options: ["40", "47", "45", "48"], answer: 1, explain: "Each term is the sum of the previous two: 18 + 29 = 47." },
        { cat: "numerical", topic: "Number series", diff: 3, prompt: "What comes next?  <span class='mono'>2, 8, 18, 32, 50, ?</span>", options: ["64", "72", "68", "70"], answer: 1, explain: "Each term is 2 × a square (2, 8, 18, 32, 50, 72)." },
        { cat: "numerical", topic: "Number series", diff: 2, prompt: "What comes next?  <span class='mono'>11, 13, 17, 19, 23, ?</span>", options: ["25", "27", "29", "31"], answer: 2, explain: "These are consecutive primes; after 23 comes 29." },
        { cat: "numerical", topic: "Arithmetic", diff: 1, prompt: "What is 25 × 16?", options: ["380", "400", "420", "360"], answer: 1, explain: "25 × 16 = 400." },
        { cat: "numerical", topic: "Arithmetic", diff: 1, prompt: "What is (9 × 7) − (48 ÷ 6)?", options: ["53", "55", "57", "47"], answer: 1, explain: "63 − 8 = 55." },
        { cat: "numerical", topic: "Word problems", diff: 2, prompt: "On a 240-km trip, you drive the first 120 km at 40 km/h and the next 120 km at 60 km/h. Total time?", options: ["4 hours", "5 hours", "6 hours", "4.5 hours"], answer: 1, explain: "120/40 + 120/60 = 3 + 2 = 5 hours." },
        { cat: "numerical", topic: "Word problems", diff: 2, prompt: "A $200 item gets two successive discounts of 10% then 20%. What is the final price?", options: ["$140", "$144", "$150", "$136"], answer: 1, explain: "200 × 0.9 = 180; 180 × 0.8 = $144." },
        { cat: "numerical", topic: "Percentages", diff: 3, prompt: "If 40% of x is 60, what is 75% of x?", options: ["100", "112.5", "120", "90"], answer: 1, explain: "x = 150, so 75% of 150 = 112.5." },
        { cat: "numerical", topic: "Ratio & proportion", diff: 2, prompt: "15 litres of a mixture are in the ratio water:juice = 3:2. How much juice is there?", options: ["5 L", "6 L", "9 L", "4 L"], answer: 1, explain: "5 parts = 15 L, so 1 part = 3 L; juice = 2 × 3 = 6 L." },
        { cat: "logical", topic: "Syllogisms", diff: 2, prompt: "All roses fade. Some flowers are roses. Which MUST be true?", options: ["Some flowers fade", "All flowers fade", "All roses are flowers", "No flowers fade"], answer: 0, explain: "The flowers that are roses fade, so some flowers fade." },
        { cat: "logical", topic: "Syllogisms", diff: 1, prompt: "If all A are B, and no B are C, then:", options: ["No A are C", "Some A are C", "All C are A", "All B are A"], answer: 0, explain: "A is inside B, and B excludes C, so no A are C." },
        { cat: "logical", topic: "Blood relations", diff: 3, prompt: "In a photo, a man says: \"She is the daughter of my grandfather's only son.\" Who is she to him?", options: ["Sister", "Mother", "Aunt", "Daughter"], answer: 0, explain: "Grandfather's only son is the man's father; his father's daughter is the man's sister." },
        { cat: "logical", topic: "Coding", diff: 2, prompt: "MONDAY is coded by shifting each letter +2 (M→O, O→Q …). What does the F in FRIDAY become?", options: ["G", "H", "I", "E"], answer: 1, explain: "F shifted forward two letters is H." },
        { cat: "logical", topic: "Letter series", diff: 2, prompt: "What comes next?  <span class='mono'>B, D, H, N, ?</span>", options: ["T", "V", "X", "U"], answer: 1, explain: "Steps grow +2, +4, +6, +8: N (14) + 8 = V (22)." },
        { cat: "logical", topic: "Directions", diff: 2, prompt: "Facing south, you turn 90° clockwise, then turn 180°. Which way do you now face?", options: ["North", "East", "South", "West"], answer: 1, explain: "South → (cw 90°) West → (180°) East." },
      ],
    },

    /* ===================== TEST 5 ===================== */
    { id: "form-5", name: "Test 5", locked: true, blurb: "Multiply-and-add series, percentage-change traps and stacking logic.",
      questions: [
        { cat: "verbal", topic: "Synonyms", diff: 3, prompt: "Closest in meaning to <span class='mono'>PERFUNCTORY</span>:", options: ["Thorough", "Cursory", "Careful", "Eager"], answer: 1, explain: "Perfunctory means done with little care — cursory." },
        { cat: "verbal", topic: "Synonyms", diff: 2, prompt: "Closest in meaning to <span class='mono'>GREGARIOUS</span>:", options: ["Shy", "Sociable", "Hostile", "Quiet"], answer: 1, explain: "Gregarious means fond of company — sociable." },
        { cat: "verbal", topic: "Synonyms", diff: 2, prompt: "Closest in meaning to <span class='mono'>ABATE</span>:", options: ["Grow", "Subside", "Begin", "Rush"], answer: 1, explain: "To abate is to lessen — subside." },
        { cat: "verbal", topic: "Antonyms", diff: 3, prompt: "Choose the OPPOSITE of <span class='mono'>TACITURN</span>:", options: ["Silent", "Talkative", "Reserved", "Gloomy"], answer: 1, explain: "Taciturn means saying little; talkative is the opposite." },
        { cat: "verbal", topic: "Antonyms", diff: 1, prompt: "Choose the OPPOSITE of <span class='mono'>CONDEMN</span>:", options: ["Blame", "Praise", "Punish", "Accuse"], answer: 1, explain: "To condemn is to criticise harshly; to praise is the opposite." },
        { cat: "verbal", topic: "Analogies", diff: 2, prompt: "Glove is to Hand as Holster is to ___", options: ["Gun", "Belt", "Leather", "Pocket"], answer: 0, explain: "A glove sheathes a hand; a holster sheathes a gun." },
        { cat: "verbal", topic: "Analogies", diff: 3, prompt: "Calf is to Cow as Cygnet is to ___", options: ["Swan", "Goose", "Duck", "Eagle"], answer: 0, explain: "A calf is a young cow; a cygnet is a young swan." },
        { cat: "verbal", topic: "Analogies", diff: 2, prompt: "Thermometer is to Temperature as Barometer is to ___", options: ["Pressure", "Heat", "Wind", "Rain"], answer: 0, explain: "A barometer measures atmospheric pressure." },
        { cat: "verbal", topic: "Odd one out", diff: 2, prompt: "Which does NOT belong?", options: ["Square", "Rectangle", "Parallelogram", "Triangle"], answer: 3, explain: "The first three are four-sided; a triangle has three sides." },
        { cat: "verbal", topic: "Odd one out", diff: 2, prompt: "Which does NOT belong?", options: ["Eagle", "Bat", "Sparrow", "Hawk"], answer: 1, explain: "Eagle, sparrow and hawk are birds; a bat is a mammal." },
        { cat: "numerical", topic: "Number series", diff: 1, prompt: "What comes next?  <span class='mono'>5, 10, 20, 40, 80, ?</span>", options: ["120", "160", "150", "100"], answer: 1, explain: "Each term doubles: 80 × 2 = 160." },
        { cat: "numerical", topic: "Number series", diff: 3, prompt: "What comes next?  <span class='mono'>1, 4, 13, 40, ?</span>", options: ["101", "121", "118", "124"], answer: 1, explain: "Rule is ×3 + 1: 40 × 3 + 1 = 121." },
        { cat: "numerical", topic: "Number series", diff: 2, prompt: "What comes next?  <span class='mono'>2, 5, 11, 23, 47, ?</span>", options: ["93", "95", "94", "97"], answer: 1, explain: "Rule is ×2 + 1: 47 × 2 + 1 = 95." },
        { cat: "numerical", topic: "Arithmetic", diff: 1, prompt: "What is 144 ÷ 9?", options: ["14", "16", "18", "12"], answer: 1, explain: "144 ÷ 9 = 16." },
        { cat: "numerical", topic: "Arithmetic", diff: 2, prompt: "What is 17 × 99?", options: ["1683", "1717", "1666", "1700"], answer: 0, explain: "17 × 100 − 17 = 1700 − 17 = 1683." },
        { cat: "numerical", topic: "Word problems", diff: 3, prompt: "5 machines make 5 widgets in 5 minutes. How long for 100 machines to make 100 widgets?", options: ["5 minutes", "20 minutes", "100 minutes", "1 minute"], answer: 0, explain: "Each machine makes 1 widget in 5 minutes, so 100 machines make 100 in 5 minutes." },
        { cat: "numerical", topic: "Word problems", diff: 3, prompt: "A's salary is 20% more than B's. By what percent is B's salary less than A's?", options: ["20%", "16.67%", "25%", "18%"], answer: 1, explain: "If B = 100 then A = 120; (120−100)/120 = 16.67%." },
        { cat: "numerical", topic: "Percentages", diff: 2, prompt: "A shirt costs $45 after a 25% discount. What was the original price?", options: ["$56", "$60", "$64", "$58"], answer: 1, explain: "$45 is 75% of the original: 45 ÷ 0.75 = $60." },
        { cat: "numerical", topic: "Ratio & proportion", diff: 2, prompt: "If 3 pens cost the same as 2 notebooks, and a notebook costs $6, what does one pen cost?", options: ["$4", "$3", "$6", "$9"], answer: 0, explain: "2 notebooks = $12 = 3 pens, so a pen is $4." },
        { cat: "logical", topic: "Syllogisms", diff: 1, prompt: "All planets orbit the sun. Mars is a planet. Therefore:", options: ["Mars orbits the sun", "All orbiting things are planets", "Mars is the sun", "Some planets do not orbit"], answer: 0, explain: "Mars is a planet and all planets orbit the sun." },
        { cat: "logical", topic: "Syllogisms", diff: 2, prompt: "Some books are interesting. No interesting thing is boring. Which MUST be true?", options: ["Some books are not boring", "All books are interesting", "Some books are boring", "No books are interesting"], answer: 0, explain: "The interesting books are not boring, so some books are not boring." },
        { cat: "logical", topic: "Logical deduction", diff: 2, prompt: "Houses stand in a row. Green is at position 2. Blue is immediately right of Green, and Red is immediately right of Blue. What is Red's position?", options: ["3", "4", "5", "6"], answer: 1, explain: "Green 2, Blue 3, Red 4." },
        { cat: "logical", topic: "Blood relations", diff: 2, prompt: "A is B's sister. C is A's father. D is C's mother. What is D to A?", options: ["Mother", "Grandmother", "Aunt", "Sister"], answer: 1, explain: "C is A's father and D is C's mother, so D is A's grandmother." },
        { cat: "logical", topic: "Letter series", diff: 2, prompt: "What comes next?  <span class='mono'>A, B, D, H, ?</span>", options: ["N", "P", "O", "M"], answer: 1, explain: "Letter positions double 1, 2, 4, 8, 16 → P." },
        { cat: "logical", topic: "Coding", diff: 2, prompt: "If FACE = 15 (6+1+3+5 by position), what is HEAD?", options: ["16", "18", "20", "15"], answer: 1, explain: "H+E+A+D = 8 + 5 + 1 + 4 = 18." },
      ],
    },

    /* ===================== TEST 6 ===================== */
    { id: "form-6", name: "Test 6", locked: true, blurb: "Second-difference series, overtime pay and symbol substitution.",
      questions: [
        { cat: "verbal", topic: "Synonyms", diff: 3, prompt: "Closest in meaning to <span class='mono'>INDIGENT</span>:", options: ["Wealthy", "Poor", "Native", "Angry"], answer: 1, explain: "Indigent means lacking means — poor (not to be confused with indigenous)." },
        { cat: "verbal", topic: "Synonyms", diff: 2, prompt: "Closest in meaning to <span class='mono'>RELINQUISH</span>:", options: ["Seize", "Surrender", "Hold", "Claim"], answer: 1, explain: "To relinquish is to give up — surrender." },
        { cat: "verbal", topic: "Synonyms", diff: 3, prompt: "Closest in meaning to <span class='mono'>AMELIORATE</span>:", options: ["Worsen", "Improve", "Ignore", "Repeat"], answer: 1, explain: "To ameliorate is to make better — improve." },
        { cat: "verbal", topic: "Antonyms", diff: 3, prompt: "Choose the OPPOSITE of <span class='mono'>PROLIFIC</span>:", options: ["Fertile", "Unproductive", "Abundant", "Creative"], answer: 1, explain: "Prolific means highly productive; unproductive is the opposite." },
        { cat: "verbal", topic: "Antonyms", diff: 1, prompt: "Choose the OPPOSITE of <span class='mono'>HUMBLE</span>:", options: ["Modest", "Arrogant", "Meek", "Shy"], answer: 1, explain: "Humble means modest; arrogant is the opposite." },
        { cat: "verbal", topic: "Analogies", diff: 2, prompt: "Pen is to Poet as Chisel is to ___", options: ["Sculptor", "Stone", "Statue", "Hammer"], answer: 0, explain: "A poet's tool is a pen; a sculptor's is a chisel." },
        { cat: "verbal", topic: "Analogies", diff: 2, prompt: "Drought is to Rain as Famine is to ___", options: ["Food", "Hunger", "Land", "Crops"], answer: 0, explain: "A drought is a shortage of rain; a famine is a shortage of food." },
        { cat: "verbal", topic: "Analogies", diff: 2, prompt: "Kitten is to Cat as Joey is to ___", options: ["Kangaroo", "Dog", "Bear", "Horse"], answer: 0, explain: "A kitten is a young cat; a joey is a young kangaroo." },
        { cat: "verbal", topic: "Odd one out", diff: 1, prompt: "Which does NOT belong?", options: ["January", "March", "July", "Sunday"], answer: 3, explain: "The first three are months; Sunday is a day." },
        { cat: "verbal", topic: "Odd one out", diff: 2, prompt: "Which does NOT belong?", options: ["2", "3", "5", "9"], answer: 3, explain: "2, 3 and 5 are prime; 9 = 3 × 3 is not." },
        { cat: "numerical", topic: "Number series", diff: 1, prompt: "What comes next?  <span class='mono'>1, 2, 4, 7, 11, 16, 22, ?</span>", options: ["28", "29", "30", "27"], answer: 1, explain: "Differences are 1, 2, 3, 4, 5, 6, 7: 22 + 7 = 29." },
        { cat: "numerical", topic: "Number series", diff: 2, prompt: "What comes next?  <span class='mono'>3, 12, 48, 192, ?</span>", options: ["576", "768", "720", "800"], answer: 1, explain: "Each term ×4: 192 × 4 = 768." },
        { cat: "numerical", topic: "Number series", diff: 3, prompt: "What comes next?  <span class='mono'>1, 3, 8, 16, 27, ?</span>", options: ["38", "41", "39", "42"], answer: 1, explain: "Differences grow 2, 5, 8, 11, 14 (step +3): 27 + 14 = 41." },
        { cat: "numerical", topic: "Arithmetic", diff: 1, prompt: "What is 37 + 48 + 55?", options: ["130", "135", "140", "145"], answer: 2, explain: "37 + 48 = 85; 85 + 55 = 140." },
        { cat: "numerical", topic: "Arithmetic", diff: 1, prompt: "What is (12 × 11) − 11?", options: ["110", "121", "132", "111"], answer: 1, explain: "132 − 11 = 121 (i.e. 11 × 11)." },
        { cat: "numerical", topic: "Word problems", diff: 3, prompt: "A worker earns $18/hour, plus time-and-a-half beyond 40 hours. What is the pay for a 46-hour week?", options: ["$828", "$882", "$900", "$846"], answer: 1, explain: "40 × 18 + 6 × 27 = 720 + 162 = $882." },
        { cat: "numerical", topic: "Word problems", diff: 2, prompt: "Two trains 300 km apart move toward each other at 50 and 70 km/h. How long until they meet?", options: ["2 hours", "2.5 hours", "3 hours", "2.25 hours"], answer: 1, explain: "Closing speed 120 km/h; 300 ÷ 120 = 2.5 hours." },
        { cat: "numerical", topic: "Percentages", diff: 2, prompt: "A town of 8,000 grows 5% one year and 5% the next. What is the population after two years?", options: ["8,800", "8,820", "8,400", "8,810"], answer: 1, explain: "8,000 × 1.05 × 1.05 = 8,820." },
        { cat: "numerical", topic: "Ratio & proportion", diff: 2, prompt: "Money is split A:B:C = 2:3:5. If C receives $150, what is the total?", options: ["$250", "$300", "$350", "$450"], answer: 1, explain: "C's 5 parts = $150 → 1 part = $30; total 10 parts = $300." },
        { cat: "logical", topic: "Syllogisms", diff: 2, prompt: "No fish are mammals. All whales are mammals. Therefore:", options: ["No whales are fish", "Some whales are fish", "All mammals are whales", "Whales are fish"], answer: 0, explain: "Whales are mammals, and no mammal is a fish, so no whale is a fish." },
        { cat: "logical", topic: "Syllogisms", diff: 2, prompt: "All diamonds are precious. Some stones are diamonds. Which MUST be true?", options: ["Some stones are precious", "All stones are precious", "All precious things are stones", "No stones are precious"], answer: 0, explain: "The stones that are diamonds are precious, so some stones are precious." },
        { cat: "logical", topic: "Logical deduction", diff: 2, prompt: "Tom finished before Sam, Sam before Uma, and Uma before Ravi but after Pat. Who finished last?", options: ["Sam", "Uma", "Ravi", "Pat"], answer: 2, explain: "Order: Tom, Sam, Pat, Uma, Ravi — Ravi is last." },
        { cat: "logical", topic: "Coding", diff: 3, prompt: "If '+' means ×, '×' means −, '−' means ÷, and '÷' means +, what is 6 + 2 × 4 − 2 ÷ 3?", options: ["10", "13", "15", "9"], answer: 1, explain: "It becomes 6×2 − 4÷2 + 3 = 12 − 2 + 3 = 13." },
        { cat: "logical", topic: "Letter series", diff: 3, prompt: "What comes next?  <span class='mono'>AZ, CX, EV, GT, ?</span>", options: ["IR", "HS", "IS", "JR"], answer: 0, explain: "First letter +2 (A,C,E,G,I); second −2 (Z,X,V,T,R) → IR." },
        { cat: "logical", topic: "Directions", diff: 2, prompt: "You face north, turn right and walk, turn right and walk, then turn left. Which way do you now face?", options: ["North", "East", "South", "West"], answer: 1, explain: "N → right E → right S → left E." },
      ],
    },

    /* ===================== TEST 7 ===================== */
    { id: "form-7", name: "Test 7", locked: true, blurb: "Shrinking-gap series, probability, inverse proportion and a grid direction.",
      questions: [
        { cat: "verbal", topic: "Synonyms", diff: 3, prompt: "Closest in meaning to <span class='mono'>VINDICATE</span>:", options: ["Accuse", "Exonerate", "Blame", "Punish"], answer: 1, explain: "To vindicate is to clear of blame — exonerate." },
        { cat: "verbal", topic: "Synonyms", diff: 1, prompt: "Closest in meaning to <span class='mono'>NOVICE</span>:", options: ["Expert", "Beginner", "Master", "Veteran"], answer: 1, explain: "A novice is a beginner." },
        { cat: "verbal", topic: "Synonyms", diff: 2, prompt: "Closest in meaning to <span class='mono'>AUSTERE</span>:", options: ["Lavish", "Severe", "Gentle", "Warm"], answer: 1, explain: "Austere means stern or plain — severe." },
        { cat: "verbal", topic: "Antonyms", diff: 1, prompt: "Choose the OPPOSITE of <span class='mono'>TRANSPARENT</span>:", options: ["Clear", "Opaque", "Sheer", "Visible"], answer: 1, explain: "Transparent lets light through; opaque does not." },
        { cat: "verbal", topic: "Antonyms", diff: 2, prompt: "Choose the OPPOSITE of <span class='mono'>MAGNIFY</span>:", options: ["Enlarge", "Diminish", "Expand", "Stretch"], answer: 1, explain: "To magnify is to enlarge; to diminish is the opposite." },
        { cat: "verbal", topic: "Analogies", diff: 2, prompt: "Caterpillar is to Butterfly as Tadpole is to ___", options: ["Frog", "Fish", "Snake", "Newt"], answer: 0, explain: "Each is an immature form of the adult: a tadpole becomes a frog." },
        { cat: "verbal", topic: "Analogies", diff: 2, prompt: "Editor is to Magazine as Director is to ___", options: ["Film", "Actor", "Camera", "Script"], answer: 0, explain: "An editor leads a magazine; a director leads a film." },
        { cat: "verbal", topic: "Analogies", diff: 2, prompt: "Pride is to Lions as Pack is to ___", options: ["Wolves", "Sheep", "Birds", "Fish"], answer: 0, explain: "A group of lions is a pride; of wolves, a pack." },
        { cat: "verbal", topic: "Odd one out", diff: 2, prompt: "Which does NOT belong?", options: ["Heart", "Liver", "Kidney", "Bone"], answer: 3, explain: "Heart, liver and kidney are soft internal organs; a bone is skeletal." },
        { cat: "verbal", topic: "Odd one out", diff: 1, prompt: "Which does NOT belong?", options: ["Red", "Green", "Blue", "Bright"], answer: 3, explain: "Red, green and blue are colours; bright describes intensity." },
        { cat: "numerical", topic: "Number series", diff: 3, prompt: "What comes next?  <span class='mono'>100, 99, 96, 91, 84, ?</span>", options: ["76", "75", "74", "77"], answer: 1, explain: "Subtract 1, 3, 5, 7, 9: 84 − 9 = 75." },
        { cat: "numerical", topic: "Number series", diff: 1, prompt: "What comes next?  <span class='mono'>4, 8, 16, 32, ?</span>", options: ["48", "56", "64", "60"], answer: 2, explain: "Each term doubles: 32 × 2 = 64." },
        { cat: "numerical", topic: "Number series", diff: 1, prompt: "What comes next?  <span class='mono'>1, 8, 27, 64, 125, ?</span>", options: ["180", "200", "216", "343"], answer: 2, explain: "Cubes of 1–6: 6³ = 216." },
        { cat: "numerical", topic: "Arithmetic", diff: 1, prompt: "What is (15 + 9) × (12 − 4)?", options: ["180", "192", "196", "200"], answer: 1, explain: "24 × 8 = 192." },
        { cat: "numerical", topic: "Arithmetic", diff: 2, prompt: "What is √81 × √64?", options: ["64", "72", "81", "56"], answer: 1, explain: "9 × 8 = 72." },
        { cat: "numerical", topic: "Word problems", diff: 2, prompt: "A bag holds 3 red and 2 blue balls. What is the probability of drawing a red?", options: ["2/5", "3/5", "1/2", "3/2"], answer: 1, explain: "3 of the 5 balls are red, so 3/5." },
        { cat: "numerical", topic: "Word problems", diff: 2, prompt: "An item costs $80 and is sold at a 15% loss. What is the selling price?", options: ["$68", "$72", "$65", "$70"], answer: 0, explain: "80 × 0.85 = $68." },
        { cat: "numerical", topic: "Percentages", diff: 3, prompt: "What is 60% of 80% of 200?", options: ["80", "96", "100", "120"], answer: 1, explain: "0.6 × 0.8 × 200 = 96." },
        { cat: "numerical", topic: "Ratio & proportion", diff: 3, prompt: "The speeds of A and B are in the ratio 4:5. If A takes 25 minutes for a route, how long does B take?", options: ["20 minutes", "30 minutes", "31 minutes", "22 minutes"], answer: 0, explain: "Time is inverse to speed: 25 × 4/5 = 20 minutes." },
        { cat: "logical", topic: "Syllogisms", diff: 1, prompt: "All metals conduct electricity. Copper is a metal. Therefore:", options: ["Copper conducts electricity", "All conductors are metals", "Copper is not a metal", "Some metals do not conduct"], answer: 0, explain: "Copper is a metal and all metals conduct, so copper conducts." },
        { cat: "logical", topic: "Syllogisms", diff: 2, prompt: "Some teachers are poets. All poets are dreamers. Which MUST be true?", options: ["Some teachers are dreamers", "All teachers are dreamers", "All dreamers are teachers", "No teachers are poets"], answer: 0, explain: "The teacher-poets are dreamers, so some teachers are dreamers." },
        { cat: "logical", topic: "Logical deduction", diff: 2, prompt: "Which pair breaks the pattern?  (2,4), (3,9), (4,16), (5,30)", options: ["(2,4)", "(3,9)", "(4,16)", "(5,30)"], answer: 3, explain: "Each second number should be the square of the first; 5² = 25, not 30." },
        { cat: "logical", topic: "Directions", diff: 3, prompt: "Q is east of P. R is north of Q. S is west of R, the same distance Q is from P. In which direction is S from P?", options: ["North", "South", "East", "West"], answer: 0, explain: "S sits directly above P, so S is north of P." },
        { cat: "logical", topic: "Letter series", diff: 3, prompt: "What comes next?  <span class='mono'>DCXW, FEVU, HGTS, ?</span>", options: ["JIRQ", "JIRP", "KIRQ", "JHRQ"], answer: 0, explain: "Columns advance D,F,H,J · C,E,G,I · X,V,T,R · W,U,S,Q → JIRQ." },
        { cat: "logical", topic: "Coding", diff: 2, prompt: "If SUN is coded TVO (each letter +1), how is MOON coded?", options: ["NPPO", "LNNM", "NPQO", "NOPP"], answer: 0, explain: "Shift each letter +1: M→N, O→P, O→P, N→O = NPPO." },
      ],
    },

    /* ===================== TEST 8 ===================== */
    { id: "form-8", name: "Test 8", locked: true, blurb: "Clock angles, painted-cube counting and a layered family puzzle.",
      questions: [
        { cat: "verbal", topic: "Synonyms", diff: 3, prompt: "Closest in meaning to <span class='mono'>INNOCUOUS</span>:", options: ["Dangerous", "Harmless", "Toxic", "Bold"], answer: 1, explain: "Innocuous means not harmful — harmless." },
        { cat: "verbal", topic: "Synonyms", diff: 2, prompt: "Closest in meaning to <span class='mono'>DETER</span>:", options: ["Encourage", "Discourage", "Allow", "Assist"], answer: 1, explain: "To deter is to discourage." },
        { cat: "verbal", topic: "Synonyms", diff: 2, prompt: "Closest in meaning to <span class='mono'>SUCCINCT</span>:", options: ["Lengthy", "Brief", "Vague", "Rambling"], answer: 1, explain: "Succinct means briefly and clearly expressed." },
        { cat: "verbal", topic: "Antonyms", diff: 2, prompt: "Choose the OPPOSITE of <span class='mono'>EXPEDITE</span>:", options: ["Hasten", "Delay", "Rush", "Speed"], answer: 1, explain: "To expedite is to speed up; to delay is the opposite." },
        { cat: "verbal", topic: "Antonyms", diff: 2, prompt: "Choose the OPPOSITE of <span class='mono'>GENERIC</span>:", options: ["Common", "Specific", "General", "Usual"], answer: 1, explain: "Generic means general; specific is the opposite." },
        { cat: "verbal", topic: "Analogies", diff: 2, prompt: "Ship is to Fleet as Wolf is to ___", options: ["Pack", "Herd", "Flock", "School"], answer: 0, explain: "A group of ships is a fleet; of wolves, a pack." },
        { cat: "verbal", topic: "Analogies", diff: 2, prompt: "Page is to Book as Scene is to ___", options: ["Play", "Actor", "Stage", "Story"], answer: 0, explain: "A page is part of a book; a scene is part of a play." },
        { cat: "verbal", topic: "Analogies", diff: 2, prompt: "Astronomer is to Telescope as Biologist is to ___", options: ["Microscope", "Cell", "Lab", "Plant"], answer: 0, explain: "Each uses the instrument: a biologist uses a microscope." },
        { cat: "verbal", topic: "Odd one out", diff: 3, prompt: "Which does NOT belong?", options: ["Walk", "Run", "Sprint", "Jog"], answer: 0, explain: "Run, sprint and jog are all forms of running; walking is not." },
        { cat: "verbal", topic: "Odd one out", diff: 2, prompt: "Which does NOT belong?", options: ["Circle", "Sphere", "Cylinder", "Cone"], answer: 0, explain: "Sphere, cylinder and cone are solids; a circle is flat." },
        { cat: "numerical", topic: "Number series", diff: 1, prompt: "What comes next?  <span class='mono'>2, 4, 8, 16, 32, ?</span>", options: ["48", "64", "56", "60"], answer: 1, explain: "Each term doubles: 32 × 2 = 64." },
        { cat: "numerical", topic: "Number series", diff: 1, prompt: "What comes next?  <span class='mono'>1, 4, 9, 16, 25, 36, ?</span>", options: ["42", "45", "49", "48"], answer: 2, explain: "Squares of 1–7: 7² = 49." },
        { cat: "numerical", topic: "Number series", diff: 3, prompt: "What comes next?  <span class='mono'>6, 9, 15, 27, 51, ?</span>", options: ["95", "99", "97", "93"], answer: 1, explain: "Rule is ×2 − 3: 51 × 2 − 3 = 99." },
        { cat: "numerical", topic: "Arithmetic", diff: 1, prompt: "What is 144 + 256?", options: ["380", "400", "420", "360"], answer: 1, explain: "144 + 256 = 400." },
        { cat: "numerical", topic: "Arithmetic", diff: 1, prompt: "What is 18 × 25?", options: ["400", "450", "475", "425"], answer: 1, explain: "18 × 25 = 450." },
        { cat: "numerical", topic: "Word problems", diff: 3, prompt: "What is the angle between the hands of a clock at 3:15?", options: ["0°", "7.5°", "15°", "30°"], answer: 1, explain: "Hour hand at 97.5°, minute hand at 90°; difference 7.5°." },
        { cat: "numerical", topic: "Word problems", diff: 2, prompt: "If 8 men dig a trench in 12 days, how many men are needed to dig it in 8 days?", options: ["10", "12", "14", "16"], answer: 1, explain: "8 × 12 = 96 man-days; 96 ÷ 8 = 12 men." },
        { cat: "numerical", topic: "Percentages", diff: 2, prompt: "A price reduced by 20% is now $48. What was the original price?", options: ["$56", "$58", "$60", "$64"], answer: 2, explain: "$48 is 80% of the original: 48 ÷ 0.8 = $60." },
        { cat: "numerical", topic: "Ratio & proportion", diff: 1, prompt: "Boys and girls are in the ratio 5:3 in a class of 40. How many boys?", options: ["20", "24", "25", "30"], answer: 2, explain: "8 parts = 40 → 1 part = 5; boys = 5 × 5 = 25." },
        { cat: "logical", topic: "Syllogisms", diff: 3, prompt: "All squares have four equal sides. This shape has four equal sides. Therefore:", options: ["It must be a square", "It is not a square", "It is not necessarily a square", "It has three sides"], answer: 2, explain: "Four equal sides could also be a rhombus, so it is not necessarily a square." },
        { cat: "logical", topic: "Syllogisms", diff: 1, prompt: "No A are B. All C are A. Therefore:", options: ["No C are B", "Some C are B", "All B are C", "All A are C"], answer: 0, explain: "C is inside A, and A excludes B, so no C are B." },
        { cat: "logical", topic: "Blood relations", diff: 3, prompt: "P's son is Q. Q's sister is R. R's mother is S. What is S to P?", options: ["Wife", "Sister", "Daughter", "Mother"], answer: 0, explain: "Q and R are P's children, and S is their mother, so S is P's wife." },
        { cat: "logical", topic: "Logical deduction", diff: 3, prompt: "A cube painted on all faces is cut into 27 equal small cubes. How many small cubes have exactly two painted faces?", options: ["6", "8", "12", "24"], answer: 2, explain: "The 12 edge cubes (one per edge) each show exactly two painted faces." },
        { cat: "logical", topic: "Letter series", diff: 2, prompt: "What comes next?  <span class='mono'>P, M, J, G, ?</span>", options: ["E", "D", "F", "C"], answer: 1, explain: "Step back three letters each time: G (7) − 3 = D (4)." },
        { cat: "logical", topic: "Coding", diff: 2, prompt: "With A=1, B=2 … , what is the sum of the letters in ICE?", options: ["15", "17", "19", "21"], answer: 1, explain: "I+C+E = 9 + 3 + 5 = 17." },
      ],
    },

    /* ===================== TEST 9 ===================== */
    { id: "form-9", name: "Test 9", locked: true, blurb: "Tribonacci, age algebra, chained ratios and a stacking puzzle.",
      questions: [
        { cat: "verbal", topic: "Synonyms", diff: 3, prompt: "Closest in meaning to <span class='mono'>OSTENTATIOUS</span>:", options: ["Modest", "Showy", "Plain", "Quiet"], answer: 1, explain: "Ostentatious means designed to impress — showy." },
        { cat: "verbal", topic: "Synonyms", diff: 3, prompt: "Closest in meaning to <span class='mono'>CORROBORATE</span>:", options: ["Deny", "Confirm", "Doubt", "Weaken"], answer: 1, explain: "To corroborate is to support or confirm." },
        { cat: "verbal", topic: "Synonyms", diff: 2, prompt: "Closest in meaning to <span class='mono'>BREVITY</span>:", options: ["Length", "Conciseness", "Delay", "Width"], answer: 1, explain: "Brevity is shortness — conciseness." },
        { cat: "verbal", topic: "Antonyms", diff: 2, prompt: "Choose the OPPOSITE of <span class='mono'>AMBIGUOUS</span>:", options: ["Vague", "Clear", "Unclear", "Hidden"], answer: 1, explain: "Ambiguous means open to interpretation; clear is the opposite." },
        { cat: "verbal", topic: "Antonyms", diff: 2, prompt: "Choose the OPPOSITE of <span class='mono'>SQUANDER</span>:", options: ["Waste", "Save", "Spend", "Lose"], answer: 1, explain: "To squander is to waste; to save is the opposite." },
        { cat: "verbal", topic: "Analogies", diff: 1, prompt: "Watch is to Wrist as Ring is to ___", options: ["Finger", "Hand", "Gold", "Jewel"], answer: 0, explain: "A watch is worn on the wrist; a ring on the finger." },
        { cat: "verbal", topic: "Analogies", diff: 2, prompt: "Piglet is to Pig as Gosling is to ___", options: ["Goose", "Duck", "Hen", "Swan"], answer: 0, explain: "A piglet is a young pig; a gosling is a young goose." },
        { cat: "verbal", topic: "Analogies", diff: 2, prompt: "Scalpel is to Surgeon as Gavel is to ___", options: ["Judge", "Lawyer", "Court", "Jury"], answer: 0, explain: "A scalpel is a surgeon's tool; a gavel is a judge's." },
        { cat: "verbal", topic: "Odd one out", diff: 2, prompt: "Which does NOT belong?", options: ["Mile", "Litre", "Gallon", "Pint"], answer: 0, explain: "Litre, gallon and pint are volumes; a mile is a distance." },
        { cat: "verbal", topic: "Odd one out", diff: 2, prompt: "Which does NOT belong?", options: ["64", "36", "49", "50"], answer: 3, explain: "64, 36 and 49 are perfect squares; 50 is not." },
        { cat: "numerical", topic: "Number series", diff: 3, prompt: "What comes next?  <span class='mono'>5, 7, 11, 19, 35, ?</span>", options: ["63", "67", "65", "70"], answer: 1, explain: "Rule is ×2 − 3: 35 × 2 − 3 = 67." },
        { cat: "numerical", topic: "Number series", diff: 1, prompt: "What comes next?  <span class='mono'>9, 18, 36, 72, ?</span>", options: ["108", "120", "144", "128"], answer: 2, explain: "Each term doubles: 72 × 2 = 144." },
        { cat: "numerical", topic: "Number series", diff: 3, prompt: "What comes next?  <span class='mono'>0, 1, 1, 2, 4, 7, 13, ?</span>", options: ["21", "24", "26", "20"], answer: 1, explain: "Each term is the sum of the previous three: 4 + 7 + 13 = 24." },
        { cat: "numerical", topic: "Arithmetic", diff: 2, prompt: "What is 23 × 23?", options: ["509", "529", "539", "549"], answer: 1, explain: "23² = 529." },
        { cat: "numerical", topic: "Arithmetic", diff: 2, prompt: "What is 1000 − 7 × 8?", options: ["944", "952", "936", "994"], answer: 0, explain: "Do the multiply first: 1000 − 56 = 944." },
        { cat: "numerical", topic: "Word problems", diff: 3, prompt: "A father is 3 times as old as his son. In 12 years he will be twice as old. How old is the son now?", options: ["10", "12", "14", "16"], answer: 1, explain: "3s + 12 = 2(s + 12) gives s = 12." },
        { cat: "numerical", topic: "Word problems", diff: 2, prompt: "A car travels 60 km in 45 minutes. What is its speed in km/h?", options: ["75", "80", "90", "72"], answer: 1, explain: "60 km in 0.75 h = 80 km/h." },
        { cat: "numerical", topic: "Percentages", diff: 2, prompt: "After spending 75% of his money, John has $90 left. How much did he start with?", options: ["$300", "$360", "$400", "$320"], answer: 1, explain: "$90 is the remaining 25%: 90 ÷ 0.25 = $360." },
        { cat: "numerical", topic: "Ratio & proportion", diff: 3, prompt: "If a:b = 2:3 and b:c = 4:5, what is a:c?", options: ["8:15", "2:5", "6:5", "8:12"], answer: 0, explain: "Make b common: a:b = 8:12, b:c = 12:15, so a:c = 8:15." },
        { cat: "logical", topic: "Syllogisms", diff: 2, prompt: "All birds lay eggs. A platypus lays eggs. Therefore the platypus:", options: ["is a bird", "is not necessarily a bird", "is not a bird", "must be a reptile"], answer: 1, explain: "Laying eggs does not make something a bird, so we cannot conclude it is one." },
        { cat: "logical", topic: "Syllogisms", diff: 2, prompt: "No liars are trustworthy. Some politicians are liars. Which MUST be true?", options: ["Some politicians are not trustworthy", "All politicians are liars", "Some politicians are trustworthy", "No politicians are trustworthy"], answer: 0, explain: "The lying politicians are not trustworthy, so some politicians are not." },
        { cat: "logical", topic: "Logical deduction", diff: 2, prompt: "Discs are stacked: Red above Blue, Green below Blue, Yellow at the very bottom, White above Red. Which disc is on top?", options: ["White", "Red", "Blue", "Yellow"], answer: 0, explain: "Top to bottom: White, Red, Blue, Green, Yellow — White is on top." },
        { cat: "logical", topic: "Coding", diff: 2, prompt: "If MONDAY is written in reverse as YADNOM, how is FRIDAY written?", options: ["YADIRF", "YADRIF", "FADIRY", "YADIRG"], answer: 0, explain: "Reverse the letters of FRIDAY → YADIRF." },
        { cat: "logical", topic: "Letter series", diff: 2, prompt: "What comes next?  <span class='mono'>B, F, K, Q, ?</span>", options: ["W", "X", "Y", "V"], answer: 1, explain: "Steps grow +4, +5, +6, +7: Q (17) + 7 = X (24)." },
        { cat: "logical", topic: "Coding", diff: 2, prompt: "In a code CAB = 312 (C=3, A=1, B=2). What is BAD? (D=4)", options: ["214", "234", "124", "241"], answer: 0, explain: "B=2, A=1, D=4 → 214." },
      ],
    },

    /* ===================== TEST 10 ===================== */
    { id: "form-10", name: "Test 10", locked: true, blurb: "The toughest form — n²(n+1) series, mixtures, area scaling and abstract logic.",
      questions: [
        { cat: "verbal", topic: "Synonyms", diff: 3, prompt: "Closest in meaning to <span class='mono'>PERNICIOUS</span>:", options: ["Beneficial", "Harmful", "Neutral", "Mild"], answer: 1, explain: "Pernicious means having a harmful effect." },
        { cat: "verbal", topic: "Synonyms", diff: 3, prompt: "Closest in meaning to <span class='mono'>ALACRITY</span>:", options: ["Reluctance", "Eagerness", "Sloth", "Delay"], answer: 1, explain: "Alacrity means brisk, cheerful readiness — eagerness." },
        { cat: "verbal", topic: "Synonyms", diff: 3, prompt: "Closest in meaning to <span class='mono'>ENERVATE</span>:", options: ["Strengthen", "Weaken", "Excite", "Energize"], answer: 1, explain: "To enervate is to drain of energy — to weaken (despite sounding like 'energize')." },
        { cat: "verbal", topic: "Antonyms", diff: 3, prompt: "Choose the OPPOSITE of <span class='mono'>ZENITH</span>:", options: ["Peak", "Nadir", "Summit", "Apex"], answer: 1, explain: "Zenith is the highest point; nadir is the lowest." },
        { cat: "verbal", topic: "Antonyms", diff: 3, prompt: "Choose the OPPOSITE of <span class='mono'>LACONIC</span>:", options: ["Brief", "Verbose", "Terse", "Curt"], answer: 1, explain: "Laconic means using few words; verbose means using too many." },
        { cat: "verbal", topic: "Analogies", diff: 3, prompt: "Penury is to Wealth as Malady is to ___", options: ["Health", "Sickness", "Doctor", "Cure"], answer: 0, explain: "Penury is the absence of wealth; a malady is the absence of health." },
        { cat: "verbal", topic: "Analogies", diff: 3, prompt: "Filly is to Mare as Colt is to ___", options: ["Stallion", "Foal", "Horse", "Pony"], answer: 0, explain: "A filly grows into a mare (female); a colt grows into a stallion (male)." },
        { cat: "verbal", topic: "Analogies", diff: 3, prompt: "Cobbler is to Shoes as Cooper is to ___", options: ["Barrels", "Wood", "Cups", "Chickens"], answer: 0, explain: "A cobbler makes shoes; a cooper makes barrels." },
        { cat: "verbal", topic: "Odd one out", diff: 3, prompt: "Which does NOT belong?", options: ["Iron", "Aluminium", "Brass", "Zinc"], answer: 2, explain: "Iron, aluminium and zinc are elements; brass is an alloy." },
        { cat: "verbal", topic: "Odd one out", diff: 2, prompt: "Which does NOT belong?", options: ["121", "144", "169", "150"], answer: 3, explain: "121, 144 and 169 are squares (11², 12², 13²); 150 is not." },
        { cat: "numerical", topic: "Number series", diff: 3, prompt: "What comes next?  <span class='mono'>2, 12, 36, 80, 150, ?</span>", options: ["240", "252", "210", "224"], answer: 1, explain: "Each term is n²(n+1): for n=6, 36 × 7 = 252." },
        { cat: "numerical", topic: "Number series", diff: 1, prompt: "What comes next?  <span class='mono'>1, 3, 6, 10, 15, 21, ?</span>", options: ["27", "28", "29", "26"], answer: 1, explain: "Triangular numbers; add 7: 21 + 7 = 28." },
        { cat: "numerical", topic: "Number series", diff: 2, prompt: "What comes next?  <span class='mono'>3, 5, 9, 17, 33, ?</span>", options: ["63", "65", "64", "67"], answer: 1, explain: "Rule is ×2 − 1: 33 × 2 − 1 = 65." },
        { cat: "numerical", topic: "Arithmetic", diff: 2, prompt: "What is 7 × 8 × 9?", options: ["496", "504", "512", "486"], answer: 1, explain: "56 × 9 = 504." },
        { cat: "numerical", topic: "Arithmetic", diff: 2, prompt: "What is (½ + ⅓ + ⅙) × 12?", options: ["10", "12", "11", "6"], answer: 1, explain: "½ + ⅓ + ⅙ = 1, and 1 × 12 = 12." },
        { cat: "numerical", topic: "Word problems", diff: 3, prompt: "At 5% simple interest, a sum grows to $1,100 in 2 years. What was the principal?", options: ["$900", "$1,000", "$1,050", "$950"], answer: 1, explain: "Amount = P(1 + 0.05×2) = 1.1P = 1100, so P = $1,000." },
        { cat: "numerical", topic: "Word problems", diff: 3, prompt: "40 litres of mixture is 10% acid. How much water must be added to make it 8% acid?", options: ["5 L", "10 L", "8 L", "12 L"], answer: 1, explain: "Acid is 4 L; 4 ÷ (40 + x) = 0.08 gives x = 10 L." },
        { cat: "numerical", topic: "Percentages", diff: 3, prompt: "If the side of a square is increased by 20%, by what percent does its area increase?", options: ["20%", "40%", "44%", "21%"], answer: 2, explain: "1.2² = 1.44, an increase of 44%." },
        { cat: "numerical", topic: "Ratio & proportion", diff: 2, prompt: "Profit is shared A:B = 3:2. If B receives $4,000, what is the total profit?", options: ["$6,000", "$10,000", "$8,000", "$12,000"], answer: 1, explain: "B's 2 parts = $4,000 → 1 part = $2,000; total 5 parts = $10,000." },
        { cat: "logical", topic: "Syllogisms", diff: 2, prompt: "All wizards are wise. No fool is wise. Therefore:", options: ["No wizard is a fool", "Some wizards are fools", "All wise are wizards", "Some fools are wise"], answer: 0, explain: "Wizards are wise and no fool is wise, so no wizard is a fool." },
        { cat: "logical", topic: "Syllogisms", diff: 3, prompt: "Some X are Y. All Y are Z. No Z are W. Which MUST be true?", options: ["Some X are not W", "All X are W", "Some X are W", "No X are Z"], answer: 0, explain: "Some X are Y ⊆ Z, and no Z are W, so those X are not W — some X are not W." },
        { cat: "logical", topic: "Logical deduction", diff: 2, prompt: "Amy, Ben and Cara own a cat, a dog and a fish (one each). Amy doesn't own the cat. Ben owns the fish. Who owns the cat?", options: ["Amy", "Ben", "Cara", "Cannot tell"], answer: 2, explain: "Ben has the fish and Amy isn't the cat owner, so Amy has the dog and Cara the cat." },
        { cat: "logical", topic: "Blood relations", diff: 3, prompt: "A is the brother of B. B is the sister of C. C is the son of D. What is D to A?", options: ["Father", "Mother", "Parent", "Brother"], answer: 2, explain: "A, B and C are siblings and D is their parent — but the gender isn't given, so 'parent' is the safest answer." },
        { cat: "logical", topic: "Letter series", diff: 3, prompt: "What comes next?  <span class='mono'>ADG, BEH, CFI, ?</span>", options: ["DGJ", "DGK", "EGJ", "DHJ"], answer: 0, explain: "Each column advances by one: A,B,C,D · D,E,F,G · G,H,I,J → DGJ." },
        { cat: "logical", topic: "Coding", diff: 2, prompt: "If BEAD is coded DGCF (each letter +2), how is FACE coded?", options: ["HCEG", "HCGE", "GBDF", "HDEG"], answer: 0, explain: "Shift each letter +2: F→H, A→C, C→E, E→G = HCEG." },
      ],
    },
  ],
};
